{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.684.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"截止日期\",\"X5\",\"MD_XIANGMUXINXI\",\"fx_List_生成字段更名列表\",\"项目信息\",\"临时设施标准合同库\",\"额外标准合同\",\"内部交易\",\"GSPM_CHUSHIMUBIAOCBZB（初始目标成本主表）\",\"GSPM_CHUSHIMUBIAOCBFJ（初始目标成本分解从表）\",\"GSPM_CHUSHIMUBIAOCBFJ（初始目标成本分解从表排除部分）)\",\"初始目标成本\",\"GSPM_TZMUBIAOCBZB（调整目标成本主表）\",\"GSPM_TZMUBIAOCBFJ（调整目标成本分解从表）\",\"GSPM_TZMUBIAOCBFJ（调整目标成本分解从表排除部分）\",\"调整目标成本\",\"收入成本分析\",\"度量值\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "zh-CN",
    "cultures": [
      {
        "name": "zh-CN",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "截止日期",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "expression": "#datetime(2023, 10, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "02388c94-a1ba-43b6-a0e2-afad49b00212",
        "queryGroup": "成本分析\\参数"
      },
      {
        "name": "X5",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true])",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "9fd7841e-611c-4770-a05f-8a65304cad59",
        "queryGroup": "成本分析\\辅助表"
      },
      {
        "name": "MD_XIANGMUXINXI",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = X5,",
          "    MD = 源{[Schema=\"MD\"]}[Data],",
          "    MD_XIANGMUXINXI = MD{[Name=\"MD_XIANGMUXINXI\"]}[Data],",
          "    重命名的列 = Table.RenameColumns(MD_XIANGMUXINXI,fx_List_生成字段更名列表(\"MD\",\"MD_XIANGMUXINXI\")),",
          "    #\"停止折叠（取消后续会出错）\" = Table.StopFolding(重命名的列)",
          "in",
          "    #\"停止折叠（取消后续会出错）\""
        ],
        "kind": "m",
        "lineageTag": "036b5c0b-706f-4bb4-875d-e9c32754d3a1",
        "queryGroup": "成本分析\\辅助表"
      },
      {
        "name": "fx_List_生成字段更名列表",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    源 = (OWNER as text,TABLE_NAME as text) as list => let",
          "        源 =  X5,",
          "        源1=Value.NativeQuery(源,\"select COLUMN_NAME,COMMENTS from all_col_comments where OWNER = '\" & OWNER &\"' and TABLE_NAME = '\" & TABLE_NAME & \"'\"),",
          "        替换的值 = Table.ReplaceValue(源1,null, each [COLUMN_NAME],Replacer.ReplaceValue,{\"COMMENTS\"}),",
          "        更改的类型 = Table.TransformColumnTypes(替换的值,{{\"COMMENTS\", type text}}),",
          "        删除的副本 = Table.Distinct(更改的类型, {\"COMMENTS\"}),",
          "        缩短说明字段长度=Table.TransformColumns(删除的副本, {{\"COMMENTS\", each Text.Start(_,15), type text}}),",
          "        自定义1 = List.Zip({缩短说明字段长度[COLUMN_NAME],缩短说明字段长度[COMMENTS]})",
          "    in",
          "        自定义1",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "a786b248-ba79-45d2-9c1b-585bf3407b2a",
        "queryGroup": "成本分析\\辅助表"
      },
      {
        "name": "项目信息",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = MD_XIANGMUXINXI,",
          "    计算责任体 = Table.AddColumn(源, \"责任体\", each if [京内外分布] = \"国际\" then \"海外\" else if [厂房事业部] <> null then [厂房事业部] else if [直管机构] <> \"公司\" then [直管机构] else if [城市公司] <> null then [城市公司] else \"公司直营\", type text),",
          "    #\"筛选的行（去掉纯机电/基础设施项目）\" = Table.SelectRows(计算责任体, each [投标管理部门] = \"营销管理中心\"),",
          "    重命名的列1 = Table.RenameColumns(#\"筛选的行（去掉纯机电/基础设施项目）\",{{\"fYWBK\", \"业务板块\"}}),",
          "    删除的其他列 = Table.SelectColumns(重命名的列1,{\"项目编码\", \"项目名称\", \"专业分类\", \"项目性质\", \"签约单位\", \"工程类别[一级]\", \"工程类别[二级]\", \"经营类型\", \"业务板块\", \"投标管理部门\", \"股份财务一体化项目编码\", \"股份一体化利润中心编码\", \"责任体\"})",
          "in",
          "    删除的其他列"
        ],
        "kind": "m",
        "lineageTag": "37a44e63-c11c-4c96-a039-1932ca7bf3c9",
        "queryGroup": "成本分析\\辅助表"
      },
      {
        "name": "临时设施标准合同库",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CHUSHIMUBIAOCBCB1 = GSPM{[Name=\"GSPM_BIAOZHUNHETONG2020\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_CHUSHIMUBIAOCBCB1, each ([FDYSDZB] = \"临时设施费\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FBIAOZHUNHETONGBH\"}),",
          "    删除的副本 = Table.Distinct(删除的其他列, {\"FBIAOZHUNHETONGBH\"})",
          "in",
          "    删除的副本"
        ],
        "kind": "m",
        "lineageTag": "7cbef4fc-5bf4-4ada-99eb-3d47f1ed5c96",
        "queryGroup": "成本分析\\辅助表"
      },
      {
        "name": "额外标准合同",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WcorydtI1NDRRitWBcQzMlWJjAQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [FBIAOZHUNHETONGBH = _t])",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "eccf85bb-60c6-462e-ad97-01ddc11d9cf8",
        "queryGroup": "成本分析\\辅助表"
      },
      {
        "name": "内部交易",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lVFNCoJgFLyL68ADiXcp0sQfzDYapVJmZKEWIWlKeZh836e3SP1auElr94aZecy8xzAUjfQHxHuccTgTkHqqYRndaayewZkWuYUkt8YUO/oqRbqAlirhBqQQisB7P0mLJELGrQyfBPdudc3KiAgHjg3SZsBQWXbXg/lDXaA3TKogf4s0v8y1oTAzv1p7EOz+yAPmpUik13jSDjIp3cAsxcECi0e84sg9Pg9pBb0b4yuESkN4Msyl2gCu0Pkm+wY=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [商务科目 = _t]),",
          "    已添加自定义 = Table.AddColumn(源, \"自定义\", each 额外标准合同),",
          "    #\"展开的“自定义”\" = Table.ExpandTableColumn(已添加自定义, \"自定义\", {\"FBIAOZHUNHETONGBH\"}, {\"FBIAOZHUNHETONGBH\"}),",
          "    重命名的列 = Table.RenameColumns(#\"展开的“自定义”\",{{\"FBIAOZHUNHETONGBH\", \"标准合同编号\"}}),",
          "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"标准合同编号\", type text}})",
          "in",
          "    更改的类型"
        ],
        "kind": "m",
        "lineageTag": "eee29949-52ce-4c73-a89e-5345e3bcdee6",
        "queryGroup": "成本分析\\辅助表"
      },
      {
        "name": "GSPM_CHUSHIMUBIAOCBZB（初始目标成本主表）",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CHUSHIMUBIAOCBZB1 = GSPM{[Name=\"GSPM_CHUSHIMUBIAOCBZB\"]}[Data],",
          "    #\"筛选的行（完成单据）\" = Table.SelectRows(GSPM_CHUSHIMUBIAOCBZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    #\"筛选的行（截止日期）\" = Table.SelectRows(#\"筛选的行（完成单据）\", each [FPINGSHENJIESHURIQI] < 截止日期),",
          "    删除的其他列 = Table.SelectColumns(#\"筛选的行（截止日期）\",{\"FID\", \"FXIANGMUMINGCHENG\", \"FXIANGMUBIANMA\", \"FJIANZHUMIANJI\", \"FHETONGE\", \"FMBCBZSR\", \"FMBCBZZC\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGE\", \"累计合同额\"}, {\"FMBCBZSR\", \"累计自施收入\"}, {\"FMBCBZZC\", \"累计目标成本\"}, {\"FJIANZHUMIANJI\", \"建筑面积\"}, {\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "cdacd68d-acd6-4e68-a7b8-6c387de8d94b",
        "queryGroup": "成本分析\\初始"
      },
      {
        "name": "GSPM_CHUSHIMUBIAOCBFJ（初始目标成本分解从表）",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CHUSHIMUBIAOCBCB1 = GSPM{[Name=\"GSPM_CHUSHIMUBIAOCBFJ\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_CHUSHIMUBIAOCBCB1,{\"FZBID\", \"FBIAOZHUNHETONGCODE\", \"FSRJE\", \"FCSMBCBCBHJ\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FSRJE\", \"临设费收入（累计）\"}, {\"FCSMBCBCBHJ\", \"临设费目标成本（累计）\"}}),",
          "    #\"合并的查询（通过标准合同取临时设施）\" = Table.NestedJoin(重命名的列, {\"FBIAOZHUNHETONGCODE\"}, 临时设施标准合同库, {\"FBIAOZHUNHETONGBH\"}, \"临时设施标准合同库\", JoinKind.Inner),",
          "    删除的其他列1 = Table.SelectColumns(#\"合并的查询（通过标准合同取临时设施）\",{\"FZBID\", \"临设费收入（累计）\", \"临设费目标成本（累计）\"}),",
          "    #\"追加的查询（追加排除部分）\" = Table.Combine({删除的其他列1, #\"GSPM_CHUSHIMUBIAOCBFJ（初始目标成本分解从表排除部分）)\"}),",
          "    分组的行 = Table.Group(#\"追加的查询（追加排除部分）\", {\"FZBID\"}, {{\"临设费收入（累计）\", each List.Sum([#\"临设费收入（累计）\"]), type nullable number}, {\"临设费目标成本（累计）\", each List.Sum([#\"临设费目标成本（累计）\"]), type nullable number}})",
          "in",
          "    分组的行"
        ],
        "kind": "m",
        "lineageTag": "7fa00560-f849-47f1-b1be-ea6f3d4f395f",
        "queryGroup": "成本分析\\初始"
      },
      {
        "name": "GSPM_CHUSHIMUBIAOCBFJ（初始目标成本分解从表排除部分）)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CHUSHIMUBIAOCBCB1 = GSPM{[Name=\"GSPM_CHUSHIMUBIAOCBFJ\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_CHUSHIMUBIAOCBCB1,{\"FZBID\", \"FBIAOZHUNHETONGCODE\", \"FSRJE\", \"FCSMBCBCBHJ\", \"FSHANGWUKEMUFNAME\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FSRJE\", \"临设费收入（累计）\"}, {\"FCSMBCBCBHJ\", \"临设费目标成本（累计）\"}}),",
          "    #\"合并的查询（通过商务科目、标准合同取临时设施）\" = Table.NestedJoin(重命名的列, {\"FSHANGWUKEMUFNAME\", \"FBIAOZHUNHETONGCODE\"}, 内部交易, {\"商务科目\", \"标准合同编号\"}, \"临时设施标准合同库\", JoinKind.Inner),",
          "    删除的其他列1 = Table.SelectColumns(#\"合并的查询（通过商务科目、标准合同取临时设施）\",{\"FZBID\", \"临设费收入（累计）\", \"临设费目标成本（累计）\"})",
          "in",
          "    删除的其他列1"
        ],
        "kind": "m",
        "lineageTag": "00e192e5-9b81-4826-bcff-cd413fa9f064",
        "queryGroup": "成本分析\\初始"
      },
      {
        "name": "初始目标成本",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = #\"GSPM_CHUSHIMUBIAOCBZB（初始目标成本主表）\",",
          "    #\"合并的查询（排除有调整的项目）\" = Table.NestedJoin(源, {\"项目编码\"}, #\"GSPM_TZMUBIAOCBZB（调整目标成本主表）\", {\"项目编码\"}, \"调整目标成本主表\", JoinKind.LeftAnti),",
          "    删除的列 = Table.RemoveColumns(#\"合并的查询（排除有调整的项目）\",{\"调整目标成本主表\"}),",
          "    合并的查询1 = Table.NestedJoin(删除的列, {\"FID\"}, #\"GSPM_CHUSHIMUBIAOCBFJ（初始目标成本分解从表）\", {\"FZBID\"}, \"初始目标成本从表\", JoinKind.LeftOuter),",
          "    #\"展开的“初始目标成本从表”\" = Table.ExpandTableColumn(合并的查询1, \"初始目标成本从表\", {\"临设费收入（累计）\", \"临设费目标成本（累计）\"}, {\"临设费收入（累计）\", \"临设费目标成本（累计）\"})",
          "in",
          "    #\"展开的“初始目标成本从表”\""
        ],
        "kind": "m",
        "lineageTag": "ffe6caf7-5ac3-4e42-bf5a-7795597b450f",
        "queryGroup": "成本分析\\初始"
      },
      {
        "name": "GSPM_TZMUBIAOCBZB（调整目标成本主表）",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = X5,",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_TZMUBIAOCBZB1 = GSPM{[Name=\"GSPM_TZMUBIAOCBZB\"]}[Data],",
          "    #\"筛选的行(完成单据）\" = Table.SelectRows(GSPM_TZMUBIAOCBZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    #\"筛选的行（截止日期）\" = Table.SelectRows(#\"筛选的行(完成单据）\", each [FPINGSHENJIESHURIQI] < 截止日期),",
          "    删除的其他列 = Table.SelectColumns(#\"筛选的行（截止日期）\",{\"FID\", \"FXIANGMUMINGCHENG\", \"FXIANGMUBIANMA\", \"FJIANZHUMIANJI\", \"FHETONGE\", \"FSR\", \"FMBCBHBC\", \"SCREATETIME\"}),",
          "    重命名的列1 = Table.RenameColumns(删除的其他列,{{\"FHETONGE\", \"累计合同额\"}, {\"FSR\", \"累计收入\"}, {\"FMBCBHBC\", \"累计目标成本\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FJIANZHUMIANJI\", \"建筑面积\"}}),",
          "    排序的行 = Table.Sort(重命名的列1,{{\"项目编码\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"项目编码\"}),",
          "    删除的列 = Table.RemoveColumns(删除的副本,{\"SCREATETIME\", \"索引\"}),",
          "    重命名的列 = Table.RenameColumns(删除的列,{{\"累计收入\", \"累计自施收入\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "8f8a356b-5bc0-4ec3-bcb5-b076889364ca",
        "queryGroup": "成本分析\\调整"
      },
      {
        "name": "GSPM_TZMUBIAOCBFJ（调整目标成本分解从表）",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = X5,",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CBFENXIPD1 = GSPM{[Name=\"GSPM_TZMUBIAOCBFJ\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_CBFENXIPD1,{\"FZBID\", \"FBIAOZHUNHETONGCODE\", \"FSRJE\", \"FCSMBCBCBHJ\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FSRJE\", \"临设费收入（累计）\"}, {\"FCSMBCBCBHJ\", \"临设费目标成本（累计）\"}}),",
          "    #\"合并的查询（通过标准合同取临设）\" = Table.NestedJoin(重命名的列, {\"FBIAOZHUNHETONGCODE\"}, 临时设施标准合同库, {\"FBIAOZHUNHETONGBH\"}, \"临时设施标准合同库\", JoinKind.Inner),",
          "    删除的其他列1 = Table.SelectColumns(#\"合并的查询（通过标准合同取临设）\",{\"FZBID\", \"临设费收入（累计）\", \"临设费目标成本（累计）\"}),",
          "    #\"追加的查询（醉驾排除部分）\" = Table.Combine({删除的其他列1, #\"GSPM_TZMUBIAOCBFJ（调整目标成本分解从表排除部分）\"}),",
          "    分组的行 = Table.Group(#\"追加的查询（醉驾排除部分）\", {\"FZBID\"}, {{\"临设费收入（累计）\", each List.Sum([#\"临设费收入（累计）\"]), type nullable number}, {\"临设费目标成本（累计）\", each List.Sum([#\"临设费目标成本（累计）\"]), type nullable number}})",
          "in",
          "    分组的行"
        ],
        "kind": "m",
        "lineageTag": "9c5aa00e-69af-49ba-b61c-e292fbd34cdf",
        "queryGroup": "成本分析\\调整"
      },
      {
        "name": "GSPM_TZMUBIAOCBFJ（调整目标成本分解从表排除部分）",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = X5,",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CBFENXIPD1 = GSPM{[Name=\"GSPM_TZMUBIAOCBFJ\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_CBFENXIPD1,{\"FZBID\", \"FBIAOZHUNHETONGCODE\", \"FSRJE\", \"FCSMBCBCBHJ\", \"FSHANGWUKEMUFNAME\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FSRJE\", \"临设费收入（累计）\"}, {\"FCSMBCBCBHJ\", \"临设费目标成本（累计）\"}}),",
          "    #\"合并的查询（通过标准合同取临设）\" = Table.NestedJoin(重命名的列, {\"FSHANGWUKEMUFNAME\", \"FBIAOZHUNHETONGCODE\"}, 内部交易, {\"商务科目\", \"标准合同编号\"}, \"临时设施标准合同库\", JoinKind.Inner),",
          "    删除的其他列1 = Table.SelectColumns(#\"合并的查询（通过标准合同取临设）\",{\"FZBID\", \"临设费收入（累计）\", \"临设费目标成本（累计）\"})",
          "in",
          "    删除的其他列1"
        ],
        "kind": "m",
        "lineageTag": "a0cb0752-7287-48e1-bcda-32d1e1e49d50",
        "queryGroup": "成本分析\\调整"
      },
      {
        "name": "调整目标成本",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.NestedJoin(#\"GSPM_TZMUBIAOCBZB（调整目标成本主表）\", {\"FID\"}, #\"GSPM_TZMUBIAOCBFJ（调整目标成本分解从表）\", {\"FZBID\"}, \"调整从表\", JoinKind.LeftOuter),",
          "    #\"展开的“调整从表”\" = Table.ExpandTableColumn(源, \"调整从表\", {\"临设费收入（累计）\", \"临设费目标成本（累计）\"}, {\"临设费收入（累计）\", \"临设费目标成本（累计）\"})",
          "in",
          "    #\"展开的“调整从表”\""
        ],
        "kind": "m",
        "lineageTag": "6ad45d28-aafb-4847-acf6-e52570298b23",
        "queryGroup": "成本分析\\调整"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "成本分析"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "成本分析\\参数"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "成本分析\\辅助表"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "成本分析\\初始"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "3"
          }
        ],
        "folder": "成本分析\\调整"
      }
    ],
    "sourceQueryCulture": "zh-CN",
    "tables": [
      {
        "name": "度量值",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "99de241f-7a72-4a6f-a4af-c690c5ef2db1",
        "measures": [
          {
            "name": "【超平均值项目数】",
            "displayFolder": "度量值",
            "expression": "CALCULATE([【项目数】],FILTER('收入成本分析',[【平均值】]>[【公司平均值】]))",
            "formatString": "0",
            "lineageTag": "fff005f0-7520-496c-b07f-6af8694e43a2"
          },
          {
            "name": "【公司平均值】",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "度量值",
            "expression": [
              "",
              "CALCULATE([【平均值】], ALLEXCEPT('收入成本分析','收入成本分析'[项目性质 (组)]))"
            ],
            "extendedProperties": [
              {
                "name": "MeasureTemplate",
                "type": "json",
                "value": {
                  "daxTemplateName": "TotalForAllCategory",
                  "version": 0
                }
              }
            ],
            "formatString": "#,0.0000",
            "lineageTag": "44a38d56-9911-4656-ac59-6d78cf329044"
          },
          {
            "name": "【临建占比】",
            "displayFolder": "度量值",
            "expression": "max('收入成本分析'[临建占比])",
            "formatString": "#,0.0000",
            "lineageTag": "8a8f5a44-db92-417c-ba4b-e2bbcd34173f"
          },
          {
            "name": "【排名后5】",
            "displayFolder": "度量值",
            "expression": "IF(ISINSCOPE('收入成本分析'[项目全径]),RANK(DENSE,ALLSELECTED('收入成本分析'[项目全径]),ORDERBY([【临建占比】],DESC BLANKS LAST)))",
            "formatString": "0",
            "lineageTag": "d04a828a-cee5-4220-a9d1-b1dfdbcd54e6"
          },
          {
            "name": "【排名前5】",
            "displayFolder": "度量值",
            "expression": "IF(ISINSCOPE('收入成本分析'[项目全径]),RANK(DENSE,ALLSELECTED('收入成本分析'[项目全径]),ORDERBY([【临建占比】],ASC BLANKS LAST)))",
            "formatString": "0",
            "lineageTag": "532dece3-4051-4c82-92ce-391510875b47"
          },
          {
            "name": "【平均值】",
            "displayFolder": "度量值",
            "expression": "ROUND(AVERAGE('收入成本分析'[临建占比]),4)",
            "formatString": "#,0.0000",
            "lineageTag": "9c7af73e-a1f0-493e-95b5-a52466407c02"
          },
          {
            "name": "【项目数】",
            "displayFolder": "度量值",
            "expression": "DISTINCTCOUNT('收入成本分析'[项目名称])",
            "formatString": "0",
            "lineageTag": "17791b96-36b2-4961-96f5-c3d007554ed6"
          },
          {
            "name": "度量值",
            "displayFolder": "度量值",
            "expression": "AVERAGEX(VALUES('收入成本分析'[责任体]),[【平均值】])",
            "formatString": "#,0.0000",
            "lineageTag": "0b3b782b-075d-4f1b-a140-4af32391a382"
          }
        ],
        "partitions": [
          {
            "name": "度量值",
            "mode": "import",
            "queryGroup": "成本分析",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"列 1\" = _t]),",
                "    删除的列 = Table.RemoveColumns(源,{\"列 1\"})",
                "in",
                "    删除的列"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "收入成本分析",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ceb7e27-c097-4ebc-a3a1-0c8368e0d2e7",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd8bd056-7cc4-4e52-a4a9-5d03e12bfb4f",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          },
          {
            "name": "责任体",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c8cea2d-d605-45ba-99ee-ba3708cfce15",
            "sourceColumn": "责任体",
            "summarizeBy": "none"
          },
          {
            "name": "项目性质",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "__PBI_SemanticLinks",
                "value": "[{\"LinkTarget\":{\"TableName\":\"收入成本分析\",\"TableItemName\":\"项目性质 (组)\",\"ObjectType\":4},\"LinkType\":\"UsedInGroup\"}]"
              }
            ],
            "dataType": "string",
            "lineageTag": "0eb7c48a-4de1-4776-afcf-2a6c21d8d748",
            "sourceColumn": "项目性质",
            "summarizeBy": "none"
          },
          {
            "name": "工程类别[一级]",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ec7bf24-db0b-44cc-a65b-7c5bb96cb00d",
            "sourceColumn": "工程类别[一级]",
            "summarizeBy": "none"
          },
          {
            "name": "工程类别[二级]",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f690e473-35e4-42d5-b481-7b9f1289c1ca",
            "sourceColumn": "工程类别[二级]",
            "summarizeBy": "none"
          },
          {
            "name": "建筑面积",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aa99a92d-09be-4cfb-88d5-41c6f799cb55",
            "sourceColumn": "建筑面积",
            "summarizeBy": "sum"
          },
          {
            "name": "累计合同额",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c0517ff4-a2ed-48a6-81a7-782f5426d809",
            "sourceColumn": "累计合同额",
            "summarizeBy": "sum"
          },
          {
            "name": "累计自施收入",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ab3276dd-df78-4409-bcd8-7ff582bf5a04",
            "sourceColumn": "累计自施收入",
            "summarizeBy": "sum"
          },
          {
            "name": "累计目标成本",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dc7f506e-7d15-41bf-901b-0c0219262b93",
            "sourceColumn": "累计目标成本",
            "summarizeBy": "sum"
          },
          {
            "name": "临设费收入（累计）",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "30c93373-6f8d-490d-a15e-303d1a657dc6",
            "sourceColumn": "临设费收入（累计）",
            "summarizeBy": "sum"
          },
          {
            "name": "临设费目标成本（累计）",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "46f28c20-daa3-4da4-a43f-e335d7dc0632",
            "sourceColumn": "临设费目标成本（累计）",
            "summarizeBy": "sum"
          },
          {
            "name": "临设费收入（累计）单方造价",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7cb9260b-29f0-4971-9e15-23b8e668d031",
            "sourceColumn": "临设费收入（累计）单方造价",
            "summarizeBy": "sum"
          },
          {
            "name": "临设费成本（累计）单方造价",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "538dc844-caa3-4dfc-b58d-4839ea0b65a9",
            "sourceColumn": "临设费成本（累计）单方造价",
            "summarizeBy": "sum"
          },
          {
            "name": "临建标准",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a911d76f-f6c8-4f97-b5b2-ca325bd7d3c1",
            "sourceColumn": "临建标准",
            "summarizeBy": "sum"
          },
          {
            "name": "临建占比",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "15cfba16-d1b5-47d7-8b78-88f1f97900ae",
            "sourceColumn": "临建占比",
            "summarizeBy": "sum"
          },
          {
            "name": "投标管理部门",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d233a2b1-6bb2-4b34-8593-2aafb87845a6",
            "sourceColumn": "投标管理部门",
            "summarizeBy": "none"
          },
          {
            "name": "项目全径",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "323609f9-63c8-4317-9cfa-ec848adc3e76",
            "sourceColumn": "项目全径",
            "summarizeBy": "none"
          },
          {
            "name": "项目性质 (组)",
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"收\",\"Entity\":\"收入成本分析\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"收\"}},\"Property\":\"项目性质\"}}],\"GroupItems\":[{\"DisplayName\":\"(空白)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"工业厂房\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"收\"}},\"Property\":\"项目性质\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'工业厂房'\"}}]]}}},{\"DisplayName\":\"公共建筑\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"收\"}},\"Property\":\"项目性质\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'公共建筑'\"}}]]}}},{\"DisplayName\":\"其它\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"收\"}},\"Property\":\"项目性质\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'基础设施'\"}}],[{\"Literal\":{\"Value\":\"'其他'\"}}],[{\"Literal\":{\"Value\":\"'其他专业类施工（装修、改造、土方、桩基等）'\"}}]]}}},{\"DisplayName\":\"住宅\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"收\"}},\"Property\":\"项目性质\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'住宅'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(",
              "\tTRUE,",
              "\tISBLANK('收入成本分析'[项目性质]),",
              "\t\"(空白)\",",
              "\t'收入成本分析'[项目性质] IN {\"工业厂房\"},",
              "\t\"工业厂房\",",
              "\t'收入成本分析'[项目性质] IN {\"公共建筑\"},",
              "\t\"公共建筑\",",
              "\t'收入成本分析'[项目性质] IN {\"基础设施\",",
              "\t\t\"其他\",",
              "\t\t\"其他专业类施工（装修、改造、土方、桩基等）\"},",
              "\t\"其它\",",
              "\t'收入成本分析'[项目性质] IN {\"住宅\"},",
              "\t\"住宅\",",
              "\t'收入成本分析'[项目性质]",
              ")"
            ],
            "extendedProperties": [
              {
                "name": "GroupingMetadata",
                "type": "json",
                "value": {
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "收入成本分析"
                          }
                        },
                        "Property": "项目性质"
                      }
                    }
                  ],
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "lineageTag": "dc01e1c8-38ea-4b86-a482-720528ef147f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "0fc6b601-862d-4984-b96f-42d01785b7c0",
        "partitions": [
          {
            "name": "收入成本分析",
            "mode": "import",
            "queryGroup": "成本分析",
            "source": {
              "expression": [
                "let",
                "    源 = Table.Combine({初始目标成本, 调整目标成本}),",
                "    #\"已添加条件列（临设费收入（累计）单方造价）\" = Table.AddColumn(源, \"临设费收入（累计）单方造价\", each if [建筑面积] = 0 then 0 else Number.Round([#\"临设费收入（累计）\"]/[建筑面积],2),type number),",
                "    #\"已添加条件列（临设费成本（累计）单方造价）\" = Table.AddColumn(#\"已添加条件列（临设费收入（累计）单方造价）\", \"临设费成本（累计）单方造价\", each if [建筑面积] = 0 then 0 else Number.Round([#\"临设费目标成本（累计）\"]/[建筑面积],2),type number),",
                "    #\"添加的条件列（合同额临建标准）\" = Table.AddColumn(#\"已添加条件列（临设费成本（累计）单方造价）\", \"合同额临建标准\", each if [累计自施收入] > 10000000000 then 0.004 else if [累计自施收入] >= 5000000000 then 0.005 else if [累计自施收入] >= 3000000000 then 0.006 else if [累计自施收入] >= 2000000000 then 0.008 else if [累计自施收入] >= 1500000000 then 0.01 else if [累计自施收入] >= 1000000000 then 0.011 else if [累计自施收入] >= 800000000 then 0.012 else if [累计自施收入] >= 500000000 then 0.013 else if [累计自施收入] >= 300000000 then 0.015 else 0, type number),",
                "    #\"添加的条件列（建筑面积临建标准）\" = Table.AddColumn(#\"添加的条件列（合同额临建标准）\", \"建筑面积临建标准\", each if [建筑面积] > 3000000 then 0.004 else if [建筑面积] >= 2000000 then 0.005 else if [建筑面积] >= 1500000 then 0.006 else if [建筑面积] >= 1000000 then 0.008 else if [建筑面积] >= 750000 then 0.01 else if [建筑面积] >= 500000 then 0.011 else if [建筑面积] >= 400000 then 0.012 else if [建筑面积] >= 250000 then 0.013 else if [建筑面积] >= 150000 then 0.015 else 0, type number),",
                "    #\"已添加自定义（临建标准）\" = Table.AddColumn(#\"添加的条件列（建筑面积临建标准）\", \"临建标准\", each List.Max({[合同额临建标准],[建筑面积临建标准]}),type number),",
                "    #\"替换的值（临建标准为0，固定450万）\" = Table.ReplaceValue(#\"已添加自定义（临建标准）\",0,4500000,Replacer.ReplaceValue,{\"临建标准\"}),",
                "    #\"已添加自定义（临建占比）\" = Table.AddColumn(#\"替换的值（临建标准为0，固定450万）\", \"临建占比\", each Number.Round([#\"临设费目标成本（累计）\"]/[累计目标成本],4),type number),",
                "    删除的列1 = Table.RemoveColumns(#\"已添加自定义（临建占比）\",{\"合同额临建标准\", \"建筑面积临建标准\", \"FID\"}),",
                "    #\"合并的查询（取营销管理中心的项目）\" = Table.NestedJoin(删除的列1, {\"项目编码\"}, 项目信息, {\"项目编码\"}, \"项目信息\", JoinKind.LeftOuter),",
                "    #\"展开的“项目信息”\" = Table.ExpandTableColumn(#\"合并的查询（取营销管理中心的项目）\", \"项目信息\", {\"工程类别[二级]\", \"工程类别[一级]\", \"投标管理部门\", \"项目性质\", \"责任体\"}, {\"工程类别[二级]\", \"工程类别[一级]\", \"投标管理部门\", \"项目性质\", \"责任体\"}),",
                "    筛选的行 = Table.SelectRows(#\"展开的“项目信息”\", each ([投标管理部门] <> null)),",
                "    已添加自定义 = Table.AddColumn(筛选的行, \"项目全径\", each [项目名称]&\" （\"&[责任体]&\"）\",type text),",
                "    重排序的列 = Table.ReorderColumns(已添加自定义,{\"项目名称\", \"项目编码\", \"责任体\", \"项目性质\", \"工程类别[一级]\", \"工程类别[二级]\", \"建筑面积\", \"累计合同额\", \"累计自施收入\", \"累计目标成本\", \"临设费收入（累计）\", \"临设费目标成本（累计）\", \"临设费收入（累计）单方造价\", \"临设费成本（累计）单方造价\", \"临建标准\", \"临建占比\", \"投标管理部门\"})",
                "in",
                "    重排序的列"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}