{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "name": "模型",
    "culture": "zh-CN",
    "dataSources": [
      {
        "type": "structured",
        "name": "Oracle/172 16 8 78/oracledb",
        "connectionDetails": {
          "protocol": "oracle",
          "address": {
            "server": "172.16.8.78/oracledb"
          },
          "authentication": null,
          "query": null
        },
        "options": {
          "hierarchicalNavigation": true
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "Oracle",
          "path": "172.16.8.78/oracledb",
          "Username": "gspm"
        }
      }
    ],
    "tables": [
      {
        "name": "成本分析标准合同-末期目标成本标准合同",
        "columns": [
          {
            "name": "FBIAOZHUNHETONGCODE",
            "dataType": "string",
            "sourceColumn": "FBIAOZHUNHETONGCODE"
          },
          {
            "name": "FBIAOZHUNHETONG",
            "dataType": "string",
            "sourceColumn": "FBIAOZHUNHETONG"
          },
          {
            "name": "FHETONGLEIXING",
            "dataType": "string",
            "sourceColumn": "FHETONGLEIXING"
          },
          {
            "name": "FSRJE",
            "dataType": "double",
            "sourceColumn": "FSRJE"
          },
          {
            "name": "FCSMBCBCBHJ",
            "dataType": "double",
            "sourceColumn": "FCSMBCBCBHJ"
          },
          {
            "name": "FZBSJ",
            "dataType": "dateTime",
            "sourceColumn": "FZBSJ"
          },
          {
            "name": "FJCSJ",
            "dataType": "dateTime",
            "sourceColumn": "FJCSJ"
          },
          {
            "name": "FFBXS",
            "dataType": "string",
            "sourceColumn": "FFBXS"
          },
          {
            "name": "FSHANGWUKEMUID",
            "dataType": "string",
            "sourceColumn": "FSHANGWUKEMUID"
          },
          {
            "name": "FSHANGWUKEMUFNAME",
            "dataType": "string",
            "sourceColumn": "FSHANGWUKEMUFNAME"
          },
          {
            "name": "FSJLY",
            "dataType": "string",
            "sourceColumn": "FSJLY"
          },
          {
            "name": "FXIANGMUBIANMA",
            "dataType": "string",
            "sourceColumn": "FXIANGMUBIANMA"
          },
          {
            "name": "FSFWCYJJFCBFXDXNHT",
            "dataType": "string",
            "sourceColumn": "FSFWCYJJFCBFXDXNHT"
          },
          {
            "name": "FBZHTSFMEQY",
            "dataType": "string",
            "sourceColumn": "FBZHTSFMEQY"
          },
          {
            "name": "FYFSFJWZCZ",
            "dataType": "double",
            "sourceColumn": "FYFSFJWZCZ"
          },
          {
            "name": "FYFSSYWZCZ",
            "dataType": "double",
            "sourceColumn": "FYFSSYWZCZ"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Table.NestedJoin(初始与调整成本标准合同合并, {\"FBIAOZHUNHETONGCODE\"}, 标准合同库, {\"FBIAOZHUNHETONGBH\"}, \"标准合同库\", JoinKind.LeftOuter),",
                "    #\"展开的“标准合同库”\" = Table.ExpandTableColumn(源, \"标准合同库\", {\"FSFWCYJJFCBFXDXNHT\"}, {\"FSFWCYJJFCBFXDXNHT\"}),",
                "    筛选的行 = Table.SelectRows(#\"展开的“标准合同库”\", each ([FSFWCYJJFCBFXDXNHT] = \"否\")),",
                "    已添加自定义 = Table.AddColumn(筛选的行, \"自定义\", each 1),",
                "    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{\"自定义\", Int64.Type}}),",
                "    删除的列 = Table.RemoveColumns(更改的类型,{\"FZBID\"}),",
                "    追加的查询 = Table.Combine({删除的列, 下游合同追加行}),",
                "    排序的行 = Table.Sort(追加的查询,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"FSHANGWUKEMUID\", Order.Ascending}, {\"FBIAOZHUNHETONGCODE\", Order.Ascending}, {\"自定义\", Order.Ascending}}),",
                "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
                "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}),",
                "    删除的列1 = Table.RemoveColumns(删除的副本,{\"自定义\", \"FJISHUIFANGSHI\", \"fLJQYEHZT\", \"索引\"}),",
                "    合并的查询2 = Table.NestedJoin(删除的列1, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}, 标准合同满额标记表, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}, \"标准合同满额标记表\", JoinKind.LeftOuter),",
                "    #\"展开的“标准合同满额标记表”\" = Table.ExpandTableColumn(合并的查询2, \"标准合同满额标记表\", {\"FBZHTSFMEQY\"}, {\"FBZHTSFMEQY\"}),",
                "    合并的查询3 = Table.NestedJoin(#\"展开的“标准合同满额标记表”\", {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}, 项目标准合同维度的废旧物资处置, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}, \"项目标准合同维度的废旧物资处置\", JoinKind.LeftOuter),",
                "    #\"展开的“项目标准合同维度的废旧物资处置”\" = Table.ExpandTableColumn(合并的查询3, \"项目标准合同维度的废旧物资处置\", {\"FYFSFJWZCZ\"}, {\"FYFSFJWZCZ\"}),",
                "    合并的查询 = Table.NestedJoin(#\"展开的“项目标准合同维度的废旧物资处置”\", {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}, 项目标准合同维度的调拨, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}, \"项目标准合同维度的调拨\", JoinKind.LeftOuter),",
                "    #\"展开的“项目标准合同维度的调拨”\" = Table.ExpandTableColumn(合并的查询, \"项目标准合同维度的调拨\", {\"FYFSSYWZCZ\"}, {\"FYFSSYWZCZ\"})",
                "in",
                "    #\"展开的“项目标准合同维度的调拨”\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "度量值 1",
            "expression": "1"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "GSPM_CHUSHIMUBIAOCBFJ",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CHUSHIMUBIAOCBFJ1 = GSPM{[Name=\"GSPM_CHUSHIMUBIAOCBFJ\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_CHUSHIMUBIAOCBFJ1,{\"FZBID\", \"FBIAOZHUNHETONGCODE\", \"FBIAOZHUNHETONG\", \"FHETONGLEIXING\", \"FSRJE\", \"FCSMBCBCBHJ\", \"FZBSJ\", \"FJCSJ\", \"FFBXS\", \"FSHANGWUKEMUID\", \"FSHANGWUKEMUFNAME\"}),",
          "    已添加自定义 = Table.AddColumn(删除的其他列, \"FSJLY\", each \"初始目标成本\")",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "GSPM_TZMUBIAOCBFJ",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_TZMUBIAOCBFJ1 = GSPM{[Name=\"GSPM_TZMUBIAOCBFJ\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_TZMUBIAOCBFJ1,{\"FZBID\", \"FBIAOZHUNHETONGCODE\", \"FBIAOZHUNHETONG\", \"FHETONGLEIXING\", \"FSRJE\", \"FCSMBCBCBHJ\", \"FZBSJ\", \"FJCSJ\", \"FFBXS\", \"FSHANGWUKEMUID\", \"FSHANGWUKEMUFNAME\"}),",
          "    已添加自定义 = Table.AddColumn(删除的其他列, \"FSJLY\", each \"目标成本调整\")",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "初始与调整成本标准合同合并",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Table.Combine({GSPM_CHUSHIMUBIAOCBFJ, GSPM_TZMUBIAOCBFJ}),",
          "    合并的查询 = Table.NestedJoin(源, {\"FZBID\"}, #\"成本分析主表-初始目标主表含调整\", {\"FID\"}, \"初始目标主表（含调整）\", JoinKind.LeftOuter),",
          "    #\"展开的“初始目标主表（含调整）”\" = Table.ExpandTableColumn(合并的查询, \"初始目标主表（含调整）\", {\"FXIANGMUBIANMA\"}, {\"FXIANGMUBIANMA\"}),",
          "    筛选的行 = Table.SelectRows(#\"展开的“初始目标主表（含调整）”\", each ([FXIANGMUBIANMA] <> null))",
          "in",
          "    筛选的行"
        ]
      },
      {
        "name": "成本分析主表-初始目标主表含调整",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CHUSHIMUBIAOCBZB1 = GSPM{[Name=\"GSPM_CHUSHIMUBIAOCBZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_CHUSHIMUBIAOCBZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FXIANGMUBIANMA\", \"FTBXFL\", \"FXMSZDQDESYL\", \"FMBCBSYLBC\", \"FTJMBCBSYLBC\", \"FJDMBCBSYLBC\", \"FBHCHCYYYFX\", \"FCBJLQK\", \"FCBJJQK\", \"FMBCBBZXZJY\", \"FMBCBXZGLF\", \"SCREATETIME\"}),",
          "    追加的查询 = Table.Combine({删除的其他列, 调整目标主表}),",
          "    排序的行 = Table.Sort(追加的查询,{{\"FXIANGMUBIANMA\", Order.Descending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 1, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\"}),",
          "    合并的查询 = Table.NestedJoin(删除的副本, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    删除的列1 = Table.RemoveColumns(合并的查询,{\"FTBXFL\", \"FXMSZDQDESYL\"}),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(删除的列1, \"MD_XIANGMUXINXI\", {\"FXMQUANCHENG\", \"FXMXINGZHI\", \"FJISHUIFANGSHI\", \"FJIANZHUMJ\", \"FTUJIANHEDINGSYLJZ\", \"FJIDIANHEDINGSYLJZ\", \"FTBGLBM\", \"FLC\", \"FTUJIANHEDINGSYL\", \"FJIDIANHEDINGSYL\", \"FZONGHEHEDINGSYL\", \"FJDHLXTJ\"}, {\"FXMQUANCHENG\", \"FXMXINGZHI\", \"FJISHUIFANGSHI\", \"FJIANZHUMJ\", \"FTUJIANHEDINGSYLJZ\", \"FJIDIANHEDINGSYLJZ\", \"FTBGLBM\", \"FLC\", \"FTUJIANHEDINGSYL\", \"FJIDIANHEDINGSYL\", \"FZONGHEHEDINGSYL\", \"FJDHLXTJ\"}),",
          "    替换的值 = Table.ReplaceValue(#\"展开的“MD_XIANGMUXINXI”\",null,0,Replacer.ReplaceValue,{\"FJIANZHUMJ\"}),",
          "    替换的值1 = Table.ReplaceValue(替换的值,null,0,Replacer.ReplaceValue,{\"FLC\"}),",
          "    已添加条件列 = Table.AddColumn(替换的值1, \"shigongmianjiorlc\", each if [FJIANZHUMJ] = 0 then [FLC] else [FJIANZHUMJ]),",
          "    更改的类型 = Table.TransformColumnTypes(已添加条件列,{{\"shigongmianjiorlc\", type number}}),",
          "    删除的列 = Table.RemoveColumns(更改的类型,{\"FJIANZHUMJ\", \"FLC\"}),",
          "    重命名的列 = Table.RenameColumns(删除的列,{{\"shigongmianjiorlc\", \"FJIANZHUMIANJI\"}, {\"FXMXINGZHI\", \"FXIANGMULEIXING\"}, {\"FZONGHEHEDINGSYL\", \"FZHHDSYL\"}, {\"FTUJIANHEDINGSYL\", \"FTJZSHDSYL\"}, {\"FJIDIANHEDINGSYL\", \"FJDZSHDSYL\"}, {\"FTUJIANHEDINGSYLJZ\", \"FTJZDHDSYL\"}, {\"FJIDIANHEDINGSYLJZ\", \"FJDZDHDSYL\"}}),",
          "    已添加条件列1 = Table.AddColumn(重命名的列, \"MBCBQDLB\", each if [FTBGLBM] = \"基础设施部\" then \"gspm-mubiaocbfenlei-03\" else if [FTBGLBM] = \"机电事业部\" and [FJDHLXTJ] = \"否\" then \"gspm-mubiaocbfenlei-02\" else \"gspm-mubiaocbfenlei-01\"),",
          "    合并的查询1 = Table.NestedJoin(已添加条件列1, {\"FXIANGMUBIANMA\"}, 项目维度的调拨, {\"FXIANGMUBIANMA\"}, \"项目维度的调拨\", JoinKind.LeftOuter),",
          "    #\"展开的“项目维度的调拨”\" = Table.ExpandTableColumn(合并的查询1, \"项目维度的调拨\", {\"FYFSSYWZCZ\", \"FSYWZCZBHS\"}, {\"FYFSSYWZCZ\", \"FSYWZCZBHS\"}),",
          "    合并的查询2 = Table.NestedJoin(#\"展开的“项目维度的调拨”\", {\"FXIANGMUBIANMA\"}, 项目维度废旧物资处置, {\"FXIANGMUBIANMA\"}, \"项目维度废旧物资处置\", JoinKind.LeftOuter),",
          "    #\"展开的“项目维度废旧物资处置”\" = Table.ExpandTableColumn(合并的查询2, \"项目维度废旧物资处置\", {\"FYFSFJWZCZ\"}, {\"FYFSFJWZCZ\"}),",
          "    合并的查询3 = Table.NestedJoin(#\"展开的“项目维度废旧物资处置”\", {\"FXIANGMUBIANMA\"}, 标前成本主表含调整, {\"FXIANGMUBIANMA\"}, \"标前成本主表含调整\", JoinKind.LeftOuter),",
          "    #\"展开的“标前成本主表含调整”\" = Table.ExpandTableColumn(合并的查询3, \"标前成本主表含调整\", {\"FTBXFL\", \"FXMSZDQDESYL\", \"FBQSYLBHCH\", \"FTJBQSYLBHCH\", \"FJDBQSYLBHCH\"}, {\"FTBXFL\", \"FXMSZDQDESYL\", \"FBQSYLBHCH\", \"FTJBQSYLBHCH\", \"FJDBQSYLBHCH\"}),",
          "    重命名的列1 = Table.RenameColumns(#\"展开的“标前成本主表含调整”\",{{\"FBQSYLBHCH\", \"FBIAOQIANSHOUYILV\"}, {\"FTJBQSYLBHCH\", \"FTJBQSYLBC\"}, {\"FJDBQSYLBHCH\", \"FJDBQSYLBC\"}}),",
          "    合并的查询4 = Table.NestedJoin(重命名的列1, {\"FXIANGMUBIANMA\"}, 初始目标主表, {\"FXIANGMUBIANMA\"}, \"初始目标主表\", JoinKind.LeftOuter),",
          "    #\"展开的“初始目标主表”\" = Table.ExpandTableColumn(合并的查询4, \"初始目标主表\", {\"FMBCBZSR\", \"FMBCBZZC\", \"FMBCBJFZGED\", \"FMBCBGLWYHYJ\", \"FSWCHSRZJ\", \"FSWCHCBJS\", \"FSWCHSYL\", \"FSWCHSRZJYSX\", \"FSWCHCBJSYSX\", \"FSWCHSYLYSX\", \"FBQSYLBHCH\", \"FTJBQSYLBHCH\", \"FJDBQSYLBHCH\"}, {\"FMBCBZSR\", \"FMBCBZZC\", \"FMBCBJFZGED\", \"FMBCBGLWYHYJ\", \"FSWCHSRZJ\", \"FSWCHCBJS\", \"FSWCHSYL\", \"FSWCHSRZJYSX\", \"FSWCHCBJSYSX\", \"FSWCHSYLYSX\", \"FBQSYLBHCH\", \"FTJBQSYLBHCH\", \"FJDBQSYLBHCH\"}),",
          "    重命名的列2 = Table.RenameColumns(#\"展开的“初始目标主表”\",{{\"FSWCHSRZJYSX\", \"FCSCHSRYSX\"}, {\"FSWCHCBJSYSX\", \"FCSCHCBYSX\"}, {\"FSWCHSYLYSX\", \"FCSCHSYLYSX\"}})",
          "in",
          "    重命名的列2"
        ]
      },
      {
        "name": "调整目标主表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_TZMUBIAOCBZB1 = GSPM{[Name=\"GSPM_TZMUBIAOCBZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_TZMUBIAOCBZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FXIANGMUBIANMA\", \"FJIJIAMOSHI\", \"FTBXFL\", \"FXMSZDQDESYL\", \"FMBCBSYLBC\", \"FTJMBCBSYLBC\", \"FJDMBCBSYLBC\", \"FBHCHCYYYFX\", \"FCBJLQK\", \"FCBJJQK\", \"FMBCBBZXZJY\", \"FMBCBXZGLF\", \"SCREATETIME\", \"FQINGDANMOSHI\"}),",
          "    排序的行 = Table.Sort(删除的其他列,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}})",
          "in",
          "    排序的行"
        ]
      },
      {
        "name": "MD_XIANGMUXINXI",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    MD = 源{[Schema=\"MD\"]}[Data],",
          "    MD_XIANGMUXINXI1 = MD{[Name=\"MD_XIANGMUXINXI\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(MD_XIANGMUXINXI1,{\"FXMBIANMA\", \"FXMQUANCHENG\", \"FXMXINGZHI\", \"FJISHUIFANGSHI\", \"FJNWFB\", \"FJIANZHUMJ\", \"FXMSSZT\", \"FXMJSZT\", \"FTUJIANHEDINGSYLJZ\", \"FJIDIANHEDINGSYLJZ\", \"FTBGLBM\", \"FGFYTHLRZXBM\", \"FLC\", \"FSFSXWZEQ\", \"FTUJIANHEDINGSYL\", \"FJIDIANHEDINGSYL\", \"FZONGHEHEDINGSYL\", \"FJDHLXTJ\"})",
          "in",
          "    删除的其他列"
        ]
      },
      {
        "name": "项目维度的调拨",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_V_XM_XYBZHTDIAOBO1 = GSPM{[Name=\"FXV_XM_XYBZHTDIAOBO\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_V_XM_XYBZHTDIAOBO1,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHSJE\", \"FBHSJE\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    分组的行 = Table.Group(筛选的行, {\"FXIANGMUBIANMA\"}, {{\"FHSJE\", each List.Sum([FHSJE]), type nullable number}, {\"FBHSJE\", each List.Sum([FBHSJE]), type nullable number}}),",
          "    重命名的列 = Table.RenameColumns(分组的行,{{\"FHSJE\", \"FYFSSYWZCZ\"}, {\"FBHSJE\", \"FSYWZCZBHS\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "项目维度废旧物资处置",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_V_XM_XYBZHTFJWZ1 = GSPM{[Name=\"FXV_XM_XYBZHTFJWZ\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_V_XM_XYBZHTFJWZ1,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHSJE\", \"FBHSJE\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    分组的行 = Table.Group(筛选的行, {\"FXIANGMUBIANMA\"}, {{\"FYFSFJWZCZ\", each List.Sum([FHSJE]), type nullable number}, {\"FYFSFJWZCZBHS\", each List.Sum([FBHSJE]), type nullable number}})",
          "in",
          "    分组的行"
        ]
      },
      {
        "name": "标前成本主表含调整",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_BIAOQIANCHENGBENZB1 = GSPM{[Name=\"GSPM_BIAOQIANCHENGBENZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_BIAOQIANCHENGBENZB1, each [FPINGSHENZHUANGTAI] = \"已完成\"),",
          "    删除的其他列1 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"SCREATETIME\", \"FTBXFL\", \"FXMSZDQDESYL\", \"FBQSYLBHCH\", \"FTJBQSYLBHCH\", \"FJDBQSYLBHCH\"}),",
          "    追加的查询 = Table.Combine({删除的其他列1, 调整标前成本主表}),",
          "    排序的行 = Table.Sort(追加的查询,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 1, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\"})",
          "in",
          "    删除的副本"
        ]
      },
      {
        "name": "调整标前成本主表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_BIAOQIANCHENGBENTZZB1 = GSPM{[Name=\"GSPM_BIAOQIANCHENGBENTZZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_BIAOQIANCHENGBENTZZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"SCREATETIME\", \"FTBXFL\", \"FXMSZDQDESYL\", \"FBQSYLBHCH\", \"FTJBQSYLBHCH\", \"FJDBQSYLBHCH\"})",
          "in",
          "    删除的其他列"
        ]
      },
      {
        "name": "初始目标主表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CHUSHIMUBIAOCBZB1 = GSPM{[Name=\"GSPM_CHUSHIMUBIAOCBZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_CHUSHIMUBIAOCBZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FXIANGMUBIANMA\", \"FMBCBZSR\", \"FMBCBZZC\", \"FMBCBJFZGED\", \"FMBCBGLWYHYJ\", \"FSWCHSRZJ\", \"FSWCHCBJS\", \"FSWCHSYL\", \"FSWCHSRZJYSX\", \"FSWCHCBJSYSX\", \"FSWCHSYLYSX\"}),",
          "    合并的查询 = Table.NestedJoin(删除的其他列, {\"FXIANGMUBIANMA\"}, 标前成本主表含调整, {\"FXIANGMUBIANMA\"}, \"标前成本主表含调整\", JoinKind.LeftOuter),",
          "    #\"展开的“标前成本主表（含调整）”\" = Table.ExpandTableColumn(合并的查询, \"标前成本主表含调整\", {\"FBQSYLBHCH\", \"FTJBQSYLBHCH\", \"FJDBQSYLBHCH\"}, {\"FBQSYLBHCH\", \"FTJBQSYLBHCH\", \"FJDBQSYLBHCH\"})",
          "in",
          "    #\"展开的“标前成本主表（含调整）”\""
        ]
      },
      {
        "name": "标准合同库",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_BIAOZHUNHETONG1 = GSPM{[Name=\"GSPM_BIAOZHUNHETONG2020\"]}[Data]",
          "in",
          "    GSPM_BIAOZHUNHETONG1"
        ]
      },
      {
        "name": "物资合同-集采补充追加行数据",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGBUCHONG1 = GSPM{[Name=\"GSPM_WUZIHETONGBUCHONG\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGBUCHONG1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSFJRXM] = \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行3 = Table.SelectRows(筛选的行2, each [FSFJZDXM] = \"是\"),",
          "    筛选的行4 = Table.SelectRows(筛选的行3, each [FHETONGPINGSHENTYPE] = \"统一转账补充合同\" or [FHETONGPINGSHENTYPE] = \"集采租赁补充合同\"),",
          "    筛选的行5 = Table.SelectRows(筛选的行4, each [FBIAOZHUNHETONGCODE] <> null ),",
          "    删除的其他列 = Table.SelectColumns(筛选的行5,{\"FHETONGPINGSHENTYPE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FXMBM\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FXMBM\", \"FXIANGMUBIANMA\"}}),",
          "    已添加条件列 = Table.AddColumn(重命名的列, \"FSJLY\", each if [FHETONGPINGSHENTYPE] = \"统一转账补充合同\" then \"物资合同\" else if [FHETONGPINGSHENTYPE] = \"集采租赁补充合同\" then \"租赁合同\" else null),",
          "    删除的列 = Table.RemoveColumns(已添加条件列,{\"FHETONGPINGSHENTYPE\"})",
          "in",
          "    删除的列"
        ]
      },
      {
        "name": "物资合同-单项和指定追加行数据",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGXINXI1 = GSPM{[Name=\"GSPM_WUZIHETONGXINXI\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGXINXI1, each [FSFJRXM] = \"是\"),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each [FHETONGPINGSHENTYPE] = \"消耗材料专项采购合同\" or [FHETONGPINGSHENTYPE] = \"周转材料租赁合同\" or [FHETONGPINGSHENTYPE] = \"指定物资采购合同\" or [FHETONGPINGSHENTYPE] = \"指定物资租赁合同\"),",
          "    筛选的行3 = Table.SelectRows(筛选的行2, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    删除的其他列 = Table.SelectColumns(筛选的行3,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FHETONGPINGSHENTYPE\"}),",
          "    已添加条件列 = Table.AddColumn(删除的其他列, \"FSJLY\", each if [FHETONGPINGSHENTYPE] = \"消耗材料专项采购合同\" then \"物资合同\" else if [FHETONGPINGSHENTYPE] = \"指定物资采购合同\" then \"物资合同\" else if [FHETONGPINGSHENTYPE] = \"周转材料租赁合同\" then \"租赁合同\" else if [FHETONGPINGSHENTYPE] = \"指定物资租赁合同\" then \"租赁合同\" else null),",
          "    删除的列 = Table.RemoveColumns(已添加条件列,{\"FHETONGPINGSHENTYPE\"})",
          "in",
          "    删除的列"
        ]
      },
      {
        "name": "分包合同-集采补充追加行数据",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOBUCHONGPINGSHEN1 = GSPM{[Name=\"GSPM_FENBAOBUCHONGPINGSHEN\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FENBAOBUCHONGPINGSHEN1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each [FSFJZDXM] = \"是\"),",
          "    筛选的行3 = Table.SelectRows(筛选的行2, each [FSFJRXM] = \"是\"),",
          "    筛选的行4 = Table.SelectRows(筛选的行3, each [FYEWULEIBIE] = \"集采分包补充合同评审\"),",
          "    删除的其他列 = Table.SelectColumns(筛选的行4,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}),",
          "    已添加自定义 = Table.AddColumn(删除的其他列, \"FSJLY\", each \"分包合同\")",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "分包合同-单项和指定追加行数据",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_HETONGXINXI1 = GSPM{[Name=\"GSPM_HETONGXINXI\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_HETONGXINXI1, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSFJRXM] = \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each [FYEWULEIBIE] = \"项目组织分包合同评审\" or [FYEWULEIBIE] = \"指定分包合同评审\"),",
          "    筛选的行3 = Table.SelectRows(筛选的行2, each ([FDAIQIANHETONGBIANMA] <> null)),",
          "    删除的其他列 = Table.SelectColumns(筛选的行3,{\"FXIANGMUBIANMA\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FDAIQIANHETONGBIANMA\", \"FBIAOZHUNHETONGCODE\"}}),",
          "    已添加自定义 = Table.AddColumn(重命名的列, \"FSJLY\", each \"分包合同\")",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "下游合同追加行",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Table.Combine({#\"物资合同-集采补充追加行数据\", #\"物资合同-单项和指定追加行数据\", #\"分包合同-集采补充追加行数据\", #\"分包合同-单项和指定追加行数据\"}),",
          "    合并的查询 = Table.NestedJoin(源, {\"FBIAOZHUNHETONGCODE\"}, 标准合同库, {\"FBIAOZHUNHETONGBH\"}, \"标准合同库\", JoinKind.LeftOuter),",
          "    #\"展开的“标准合同库”\" = Table.ExpandTableColumn(合并的查询, \"标准合同库\", {\"FBIAOZHUNHETONGMC\", \"FSHANGWUKEMUFNAME\", \"FHTFLFW\"}, {\"FBIAOZHUNHETONGMC\", \"FSHANGWUKEMUFNAME\", \"FHTFLFW\"}),",
          "    已添加自定义 = Table.AddColumn(#\"展开的“标准合同库”\", \"自定义\", each 2),",
          "    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{\"自定义\", Int64.Type}}),",
          "    重命名的列 = Table.RenameColumns(更改的类型,{{\"FHTFLFW\", \"FHETONGLEIXING\"}, {\"FBIAOZHUNHETONGMC\", \"FBIAOZHUNHETONG\"}}),",
          "    筛选的行 = Table.SelectRows(重命名的列, each [FBIAOZHUNHETONG] <> null ),",
          "    追加的查询 = Table.Combine({筛选的行, #\"生成BZKB-101标准合同行\", #\"生成BZKB-105标准合同行\"})",
          "in",
          "    追加的查询"
        ]
      },
      {
        "name": "初始目标主表原始",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CHUSHIMUBIAOCBZB1 = GSPM{[Name=\"GSPM_CHUSHIMUBIAOCBZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_CHUSHIMUBIAOCBZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\"})",
          "in",
          "    删除的其他列"
        ]
      },
      {
        "name": "生成BZKB-101标准合同行",
        "kind": "m",
        "expression": [
          "let",
          "    源 = 初始目标主表原始,",
          "    已添加自定义 = Table.AddColumn(源, \"FBIAOZHUNHETONGCODE\", each \"BZKB-101\"),",
          "    合并的查询 = Table.NestedJoin(已添加自定义, {\"FBIAOZHUNHETONGCODE\"}, 标准合同库, {\"FBIAOZHUNHETONGBH\"}, \"标准合同库\", JoinKind.LeftOuter),",
          "    #\"展开的“标准合同库”\" = Table.ExpandTableColumn(合并的查询, \"标准合同库\", {\"FSHANGWUKEMUID\"}, {\"FSHANGWUKEMUID\"}),",
          "    已添加自定义1 = Table.AddColumn(#\"展开的“标准合同库”\", \"FSJLY\", each \"零星采购进场\"),",
          "    合并的查询1 = Table.NestedJoin(已添加自定义1, {\"FSHANGWUKEMUID\"}, 标准合同库, {\"FSHANGWUKEMUID\"}, \"标准合同库\", JoinKind.LeftOuter),",
          "    #\"展开的“标准合同库”1\" = Table.ExpandTableColumn(合并的查询1, \"标准合同库\", {\"FBIAOZHUNHETONGMC\", \"FSHANGWUKEMUFNAME\", \"FHTFLFW\"}, {\"FBIAOZHUNHETONGMC\", \"FSHANGWUKEMUFNAME\", \"FHTFLFW\"}),",
          "    重命名的列 = Table.RenameColumns(#\"展开的“标准合同库”1\",{{\"FHTFLFW\", \"FHETONGLEIXING\"}, {\"FBIAOZHUNHETONGMC\", \"FBIAOZHUNHETONG\"}}),",
          "    已添加自定义2 = Table.AddColumn(重命名的列, \"自定义\", each 3),",
          "    合并的查询2 = Table.NestedJoin(已添加自定义2, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询2, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"})",
          "in",
          "    #\"展开的“MD_XIANGMUXINXI”\""
        ]
      },
      {
        "name": "GSPM_GUDINGZICHANZLCB",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_GUDINGZICHANZLCB1 = GSPM{[Name=\"GSPM_GUDINGZICHANZLCB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_GUDINGZICHANZLCB1, each [FGSGDZCZLF] > 0),",
          "    已添加自定义 = Table.AddColumn(筛选的行, \"FBIAOZHUNHETONGCODE\", each \"BZKB-105\")",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "生成BZKB-105标准合同行",
        "kind": "m",
        "expression": [
          "let",
          "    源 = GSPM_GUDINGZICHANZLCB,",
          "    合并的查询 = Table.NestedJoin(源, {\"FZBID\"}, GSPM_DAIQIANHETONGJIEZHUANZB, {\"FID\"}, \"GSPM_DAIQIANHETONGJIEZHUANZB\", JoinKind.LeftOuter),",
          "    #\"展开的“GSPM_DAIQIANHETONGJIEZHUANZB”\" = Table.ExpandTableColumn(合并的查询, \"GSPM_DAIQIANHETONGJIEZHUANZB\", {\"FXIANGMUBIANMA\"}, {\"FXIANGMUBIANMA\"}),",
          "    删除的其他列 = Table.SelectColumns(#\"展开的“GSPM_DAIQIANHETONGJIEZHUANZB”\",{\"FSHANGWUKEMUID\", \"FGSGDZCZLF\", \"FBIAOZHUNHETONGCODE\", \"FXIANGMUBIANMA\"}),",
          "    已添加自定义 = Table.AddColumn(删除的其他列, \"FSJLY\", each \"已签合同结转\"),",
          "    合并的查询1 = Table.NestedJoin(已添加自定义, {\"FBIAOZHUNHETONGCODE\"}, 标准合同库, {\"FBIAOZHUNHETONGBH\"}, \"标准合同库\", JoinKind.LeftOuter),",
          "    #\"展开的“标准合同库”\" = Table.ExpandTableColumn(合并的查询1, \"标准合同库\", {\"FBIAOZHUNHETONGMC\", \"FHTFLFW\"}, {\"FBIAOZHUNHETONGMC\", \"FHTFLFW\"}),",
          "    重命名的列 = Table.RenameColumns(#\"展开的“标准合同库”\",{{\"FHTFLFW\", \"FHETONGLEIXING\"}, {\"FBIAOZHUNHETONGMC\", \"FBIAOZHUNHETONG\"}, {\"FGSGDZCZLF\", \"fLJQYEHZT\"}}),",
          "    已添加自定义1 = Table.AddColumn(重命名的列, \"自定义\", each 4),",
          "    合并的查询2 = Table.NestedJoin(已添加自定义1, {\"FSHANGWUKEMUID\"}, 商务科目表, {\"FID\"}, \"商务科目表\", JoinKind.LeftOuter),",
          "    #\"展开的“商务科目表”\" = Table.ExpandTableColumn(合并的查询2, \"商务科目表\", {\"FFULLNAME\"}, {\"FFULLNAME\"}),",
          "    重命名的列1 = Table.RenameColumns(#\"展开的“商务科目表”\",{{\"FFULLNAME\", \"FSHANGWUKEMUFNAME\"}})",
          "in",
          "    重命名的列1"
        ]
      },
      {
        "name": "GSPM_DAIQIANHETONGJIEZHUANZB",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_DAIQIANHETONGJIEZHUANZB1 = GSPM{[Name=\"GSPM_DAIQIANHETONGJIEZHUANZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_DAIQIANHETONGJIEZHUANZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    排序的行 = Table.Sort(筛选的行,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\"})",
          "in",
          "    删除的副本"
        ]
      },
      {
        "name": "商务科目表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    MD = 源{[Schema=\"MD\"]}[Data],",
          "    MD_SHANGWUKEMU1 = MD{[Name=\"MD_SHANGWUKEMU2020\"]}[Data]",
          "in",
          "    MD_SHANGWUKEMU1"
        ]
      },
      {
        "name": "标准合同满额标记表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_MBCB_MEQY1 = GSPM{[Name=\"GSPM_MBCB_MEQY\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_MBCB_MEQY1,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FBZHTSFMEQY\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null and [FBIAOZHUNHETONGCODE] <> \"undefined\")),",
          "    已添加索引 = Table.AddIndexColumn(筛选的行, \"索引\", 0, 1, Int64.Type),",
          "    替换的值 = Table.ReplaceValue(已添加索引,null,\"否\",Replacer.ReplaceValue,{\"FBZHTSFMEQY\"}),",
          "    替换的值1 = Table.ReplaceValue(替换的值,\"undefined\",\"否\",Replacer.ReplaceText,{\"FBZHTSFMEQY\"}),",
          "    排序的行 = Table.Sort(替换的值1,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"FSHANGWUKEMUID\", Order.Ascending}, {\"FBIAOZHUNHETONGCODE\", Order.Ascending}, {\"FBZHTSFMEQY\", Order.Descending}}),",
          "    已添加索引1 = Table.AddIndexColumn(排序的行, \"索引.1\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引1, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"})",
          "in",
          "    删除的副本"
        ]
      },
      {
        "name": "项目标准合同维度的废旧物资处置",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_V_XM_XYBZHTFJWZ1 = GSPM{[Name=\"FXV_XM_XYBZHTFJWZ\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_V_XM_XYBZHTFJWZ1,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHSJE\", \"FBHSJE\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    分组的行 = Table.Group(筛选的行, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}, {{\"FYFSFJWZCZ\", each List.Sum([FHSJE]), type nullable number}, {\"FYFSFJWZCZBHS\", each List.Sum([FBHSJE]), type nullable number}})",
          "in",
          "    分组的行"
        ]
      },
      {
        "name": "项目标准合同维度的调拨",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_V_XM_XYBZHTDIAOBO1 = GSPM{[Name=\"FXV_XM_XYBZHTDIAOBO\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_V_XM_XYBZHTDIAOBO1,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHSJE\", \"FBHSJE\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    分组的行 = Table.Group(筛选的行, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}, {{\"HS\", each List.Sum([FHSJE]), type nullable number}, {\"BHS\", each List.Sum([FBHSJE]), type nullable number}}),",
          "    合并的查询 = Table.NestedJoin(分组的行, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"FYFSSYWZCZ\", each if [FJISHUIFANGSHI] = \"一般计税\" then [BHS] else if [FJISHUIFANGSHI] = \"简易计税\" then [HS] else null),",
          "    删除的列 = Table.RemoveColumns(已添加条件列,{\"HS\", \"BHS\", \"FJISHUIFANGSHI\"}),",
          "    更改的类型 = Table.TransformColumnTypes(删除的列,{{\"FYFSSYWZCZ\", type number}})",
          "in",
          "    更改的类型"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}