{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.118.621.0 (23.06)"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"F_商务产值收益\",\"X5\",\"年度\",\"D-项目\",\"应排除的局项目\",\"分公司虚拟项目\",\"项目编码\",\"项目收益率\",\"D-专业\",\"D-分包类型\",\"D-责任体\",\"M_度量值\",\"D-大客户简称\",\"数据连接\",\"Oracle/172 16 8 78/oracledb\",\"Oracle/172 16 8 199/orcl\",\"产值文件路径\",\"已竣已结项目文件路径\",\"已竣未结项目文件路径\",\"特殊项目产值文件路径\",\"已竣未结\",\"已竣已结\",\"项目状态\",\"新接\",\"D-单位\",\"分公司总经\",\"F_业主合同\",\"数据库连接\",\"确认量主表\",\"确认量明细\",\"新业主确认量\",\"确认量历史年度结算表从表\",\"确认量历史年度结算表主表\",\"结转确认量\",\"F_业主确认量\",\"刷新时间\",\"fx_List_生成字段更名列表\",\"项目年度预算主表\",\"项目年度预算表资金情况\",\"F_全面预算\",\"产值与营业收入换算系数\",\"选取预算科目\",\"项管产值\",\"GSPM_CBFKJD_HKPF_ZB（业主收款初始化主表）\",\"GSPM_CBFKJD_HKPF_C1B（业主收款初始化明细）\",\"业主合同回款初始化\",\"GSPM_GONGCHENGKUANHS_ZB（业主收款主表）\",\"GSPM_GONGCHENGKUANHS_ZB（业主收款明细）\",\"业主合同回款登记\",\"F_业主合同回款\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "zh-CN",
    "cultures": [
      {
        "name": "zh-CN",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "table.column": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【目标产值】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "目标产值": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "目标": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年产值无税】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "产值无税": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "完成产值": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "本年产值无税": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column10": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年回收工程款】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "本年回收工程款": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column11": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年确权无税】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "确权无税": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "本年确权无税": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column12": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年结算率】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "本年结算率": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column13": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【开累产值无税】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "开累产值无税": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column14": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【开累确权无税】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "开累确权无税": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column15": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【开累结算率】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "开累结算率": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column16": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【开累回收工程款】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "开累回收工程款": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column17": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年确权目标】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "确权目标": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column18": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年确权进度】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "确权进度": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column19": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年工程款收款目标】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "工程款收款目标": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年产值进度】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "产值进度": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column20": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年回收工程款进度】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "回收工程款进度": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column3": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【目标收益】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "目标收益": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column4": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年核定收益】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "核定收益": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column5": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年总收益】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "总收益": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "本年总收益": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column6": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【平均实现收益率】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "平均实现收益率": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column7": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年收益完成进度】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "收益进度": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "收益完成进度": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column8": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【本年收益完成进度（不含降低）】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "收益进度（无降低）": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "收益进度（不含降低）": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "收益进度（无降低）】": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column9": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "M_度量值",
                    "ConceptualProperty": "【成本降低额】"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "成本降低额": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "fastCombine": true,
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "年度",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": "2023 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "9a12fcfa-8417-4554-87ef-d0d57da36b28",
        "queryGroup": "参数组"
      },
      {
        "name": "分公司虚拟项目",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"lY9LCsIwEIbvknU9UehdBFEU2+qqgnEjGHARxIVi7MbLZJL2FuJj0cRxmuzC/2X+B+fM6B0UG5jPYKpgpUe2PttKdvu7EyeWJWJU+ZywPOMMyopyS8Oo4oe9yhBuCRhVgmUlXT0eo0ovrJUPyi0No0p/2Vtz4tKu5U/vQRZ88q2dUkaPTbM0ettNjqHDAI4MaAoygMCxCxb0gv84LgCEoAIoHBFgrzc41OEhpXqPr1H+BA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [项目名称 = _t, 项目编码 = _t, 直管机构 = _t, 责任体 = _t, 状态 = _t]),",
          "    已添加自定义2 = Table.AddColumn(源, \"业务板块\", each \"房建\",type text),",
          "    已添加自定义3 = Table.AddColumn(已添加自定义2, \"投资非投资项目\", each \"非投资项目\",type text),",
          "    已添加条件列 = Table.AddColumn(已添加自定义3, \"京内外\", each if [直管机构] = \"公司\" then \"京内\" else \"京外\",type text)",
          "in",
          "    已添加条件列"
        ],
        "kind": "m",
        "lineageTag": "dfe0b010-7e0a-4bb3-9f9d-e915eef5ae15",
        "queryGroup": "维度"
      },
      {
        "name": "应排除的局项目",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"dZTrUtpgEIbvhf5tO+GgxZ9CFCZFEUMHiMN4E70AqoOC5ThqBUUpVQ5OORgpJQSBi2n2S/LLW+iGz5GkTGcyk8km37O7776bvT1bwM4wLoZxOp22t7ZP+8Fd3350a9/DrW+7WIxA5kKR21CvQ/bC9QYqD7b4W3qIYRwOB2M+xEX5iBDlFsfw0uozOD+Ck5oidWB2+PyUMiIZ+fkpjXFFutSPi9pNVj1rIRvfKlICxASpyOrZAL8xZ3PZV60lBgRul4+EFumkCelPKJAmxUQb7+zOP4kveHNhBri+eEVi1/Y1S9f+zSjPCiHOIBZS2kFdL/4k5SqWAp0ClFvK+DfkDkhqBmNZ605hWFdbXy081xLPu7XzDw6SaSSqzSI5wUbTerkAyTbkJa3ZIEUJxLx6VlXkpirPzGhm5YMF7fGtx3ybAsbIYx/7hysZumm13V5VxreIJXJBrd7rpcH6VjCwwerXP8j17JWMSkO+COK5WWPM4nI7zFl4YWfdx3G7QtTIMxSh0odRH/PA1UQvJ6nUdLJminPVQglHPX6W+oIytORU6/bIuEUGQ7hrQq6h10bqVZeOXZFO0ReQOoJM0kK1KhDZ/Rhm+c1FYdOuNumhrHrikkL3aItx64TWLA3G0EUvpT2m9FIfSmn9OENbAjGpTPLUpiiYl/oHFaN1Lo+fWbM4NOL3R33svMJOg4hpyOZI6WX8n53/GwHjdpsh3hA3R+jHWZCP5i6vkG8jHLT7/QqOGrIn0HtSJqekNFXvZOrSOc+ymtuC3+c1KhnkcJON/p5KMJpBRbavQn5oWg3r/DkhJsR83o0QvxifMulD0hDFwNx1KUaRM6RSdZHvFkUc1mZ4jg8tfg96owyiiOVow57DjVV4HbQOk7IWKdgIF/IEwtT1qYJ+OCHSPRGruOYYXhLUui9+XmBjxs9Cq9XIwy/SuUWXLH3HBgQ/VQrfarMbbBFNalxSD6q5ZYUCYT7oD2JIkQzngNibP8fjfwE=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [利润中心编码 = _t, 项目编码 = _t, 项目名称 = _t]),",
          "    删除的副本 = Table.Distinct(源, {\"项目编码\"})",
          "in",
          "    删除的副本"
        ],
        "kind": "m",
        "lineageTag": "25415582-53f4-4ba8-87ac-902050312e9a",
        "queryGroup": "维度"
      },
      {
        "name": "数据连接",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"172.16.8.78/oracledb\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c9fa09c2-6c7f-4449-90c8-9d53ac11e231",
        "queryGroup": "参数组"
      },
      {
        "name": "已竣未结",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "expression": [
          "let",
          "    源 = Excel.Workbook(File.Contents(已竣未结项目文件路径), null, true),",
          "    Sheet0 = 源{[Name=\"Sheet0\"]}[Data],",
          "    提升的标题 = Table.PromoteHeaders(Sheet0, [PromoteAllScalars=true]),",
          "    筛选的行 = Table.SelectRows(提升的标题, each ([评审状态] = \"已完成\")),",
          "    // 排除已竣已结项目",
          "    #\"合并的查询（排除已竣已结）\" = Table.NestedJoin(筛选的行, {\"项目编码\"}, 已竣已结, {\"项目编码\"}, \"已竣已结\", JoinKind.LeftAnti),",
          "    删除的其他列 = Table.SelectColumns(#\"合并的查询（排除已竣已结）\",{\"业主结算状态\", \"项目编码\", \"项目名称\"}),",
          "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"业主结算状态\", type text}, {\"项目编码\", type text}, {\"项目名称\", type text}}),",
          "    重命名的列 = Table.RenameColumns(更改的类型,{{\"业主结算状态\", \"状态\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "14e99ab0-5deb-4dc5-b518-e298baaf89a9",
        "queryGroup": "维度\\项目状态(已竣已结、已竣未结每季度需要更换文件)"
      },
      {
        "name": "已竣已结",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "expression": [
          "let",
          "    源 = Excel.Workbook(File.Contents(已竣已结项目文件路径), null, true),",
          "    已竣已结_Sheet = 源{[Item=\"已竣已结\",Kind=\"Sheet\"]}[Data],",
          "    提升的标题 = Table.PromoteHeaders(已竣已结_Sheet, [PromoteAllScalars=true]),",
          "    筛选的行 = Table.SelectRows(提升的标题, each ([业主结算状态] = \"已竣已结\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"业主结算状态\", \"项目编码\", \"项目名称\"}),",
          "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"业主结算状态\", type text}, {\"项目编码\", type text}, {\"项目名称\", type text}}),",
          "    重命名的列 = Table.RenameColumns(更改的类型,{{\"业主结算状态\", \"状态\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "3701e982-32d3-4516-acd2-804208d2dd55",
        "queryGroup": "维度\\项目状态(已竣已结、已竣未结每季度需要更换文件)"
      },
      {
        "name": "新接",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "description": "营销给的新接项目列表",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_XIANGMUZHONGBIAOJINE1 = GSPM{[Name=\"GSPM_XIANGMUZHONGBIAOJINE\"]}[Data],",
          "    重命名的列 = Table.RenameColumns(GSPM_XIANGMUZHONGBIAOJINE1,{{\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FFGFQH_IMPORT\", \"股份期号\"}}),",
          "    已提取首字符 = Table.TransformColumns(重命名的列, {{\"股份期号\", each Text.Start(_, 4),Text.Type}}),",
          "    更改的类型1 = Table.TransformColumnTypes(已提取首字符,{{\"股份期号\", Int64.Type}}),",
          "    #\"筛选的行（股份期号等于本年度）\" = Table.SelectRows(更改的类型1, each [股份期号] = 年度),",
          "    删除的其他列 = Table.SelectColumns(#\"筛选的行（股份期号等于本年度）\",{\"项目编码\", \"项目名称\"}),",
          "    已添加自定义 = Table.AddColumn(删除的其他列, \"状态\", each \"新接\",Text.Type)",
          "in",
          "    已添加自定义"
        ],
        "kind": "m",
        "lineageTag": "41936122-ed01-4018-8a5e-2972fcb99cc7",
        "queryGroup": "维度\\项目状态(已竣已结、已竣未结每季度需要更换文件)"
      },
      {
        "name": "项目状态",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.Combine({新接, 已竣未结, 已竣已结}),",
          "    筛选的行 = Table.SelectRows(源, each ([项目编码] <> null)),",
          "    删除的副本 = Table.Distinct(筛选的行, {\"项目编码\"})",
          "in",
          "    删除的副本"
        ],
        "kind": "m",
        "lineageTag": "3aba0f2c-62f7-4e06-a4ff-51edd2cfed04",
        "queryGroup": "维度\\项目状态(已竣已结、已竣未结每季度需要更换文件)"
      },
      {
        "name": "项目编码",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    MD = 源{[Schema=\"MD\"]}[Data],",
          "    MD_XIANGMUXINXI = MD{[Name=\"MD_XIANGMUXINXI\"]}[Data]",
          "in",
          "    MD_XIANGMUXINXI"
        ],
        "kind": "m",
        "lineageTag": "4ab440c0-f624-4c06-bc0d-f749ba1cbf0c",
        "queryGroup": "维度"
      },
      {
        "name": "产值文件路径",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"\\\\172.16.8.66\\关键指标数据\\经营管控中心\\产值\\2023年产值\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "8686caae-67db-48f0-82c6-8b93fd36096c",
        "queryGroup": "参数组"
      },
      {
        "name": "已竣已结项目文件路径",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"\\\\172.16.8.66\\经营分析\\经营分析会\\2023-1季度\\已竣已结项目情况2023.3.xlsx\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d8aa5cb7-5a41-4660-a977-f08c20243f0d",
        "queryGroup": "参数组"
      },
      {
        "name": "已竣未结项目文件路径",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"\\\\172.16.8.66\\经营分析\\经营分析会\\2023-1季度\\结算进展 23.3.xls\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "20efda99-0e21-4c57-b260-bd113f45f697",
        "queryGroup": "参数组"
      },
      {
        "name": "特殊项目产值文件路径",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"\\\\172.16.8.66\\经营分析\\经营分析会\\2023-1季度\\23.04.25-特殊项目产值报表-海外项目-截止4月底.xlsx\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c358ce2d-29b4-4d94-bc4c-42a0cba4367f",
        "queryGroup": "参数组"
      },
      {
        "name": "数据库连接",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"172.16.8.78/oracledb\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "5eca8801-c5e3-44f8-a72c-f94559df14ae",
        "queryGroup": "业主确认量"
      },
      {
        "name": "确认量主表",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(数据库连接, [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_JLYZQUERENWANCENGLIANG1 = GSPM{[Name=\"GSPM_JLYZQUERENWANCENGLIANG\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_JLYZQUERENWANCENGLIANG1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FNIAN\", \"FYUE\", \"FXIANGMUBIANMA\", \"FXIANGMUMINGCHENG\"}),",
          "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"FNIAN\", Int64.Type}, {\"FYUE\", Int64.Type}})",
          "in",
          "    更改的类型"
        ],
        "kind": "m",
        "lineageTag": "280dcd81-8ed9-48b2-ab8d-32c1c9822f43",
        "queryGroup": "业主确认量"
      },
      {
        "name": "确认量明细",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(数据库连接, [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WANCHENGLIANGMX1 = GSPM{[Name=\"GSPM_WANCHENGLIANGMX\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WANCHENGLIANGMX1,{\"FFENBAOHETONGCODE\", \"FZBID\", \"FSHIGONGZHUANYE\", \"FBYQRCZWS\", \"FBYQRCZSE\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FSHIGONGZHUANYE\", \"专业\"}, {\"FBYQRCZWS\", \"确认产值无税\"}, {\"FBYQRCZSE\", \"税额\"}, {\"FFENBAOHETONGCODE\", \"分包类型\"}}),",
          "    // 内容是合同号的，全是指定分包",
          "    替换的值 = Table.ReplaceValue(重命名的列,each [分包类型] ,each if [分包类型]<>\"自施\" then \"指定\" else \"自施\",Replacer.ReplaceText,{\"分包类型\"}),",
          "    已添加自定义 = Table.AddColumn(替换的值, \"确认产值含税\", each List.Sum({[确认产值无税],[税额]}),type number)",
          "in",
          "    已添加自定义"
        ],
        "kind": "m",
        "lineageTag": "1d5d71d2-b09a-43e8-b979-ae2c91d0b039",
        "queryGroup": "业主确认量"
      },
      {
        "name": "新业主确认量",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.NestedJoin(确认量主表, {\"FID\"}, 确认量明细, {\"FZBID\"}, \"确认量明细\", JoinKind.Inner),",
          "    #\"展开的“确认量明细”\" = Table.ExpandTableColumn(源, \"确认量明细\", {\"分包类型\", \"专业\", \"确认产值无税\", \"确认产值含税\"}, {\"分包类型\", \"专业\", \"确认产值无税\", \"确认产值含税\"}),",
          "    已添加自定义 = Table.AddColumn(#\"展开的“确认量明细”\", \"日期\", each #date([FNIAN],[FYUE],1),type date),",
          "    重命名的列 = Table.RenameColumns(已添加自定义,{{\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}}),",
          "    删除的其他列 = Table.SelectColumns(重命名的列,{\"项目编码\", \"项目名称\", \"分包类型\", \"专业\", \"确认产值无税\", \"确认产值含税\", \"日期\"})",
          "in",
          "    删除的其他列"
        ],
        "kind": "m",
        "lineageTag": "c09c3bdc-c5a5-415a-a65b-b787e6b3be8f",
        "queryGroup": "业主确认量"
      },
      {
        "name": "确认量历史年度结算表从表",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(数据库连接, [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WANCHENGLIANGJIEZHUANCB1 = GSPM{[Name=\"GSPM_WANCHENGLIANGJIEZHUANCB\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WANCHENGLIANGJIEZHUANCB1,{\"FKLTUJIANZISHIHS\", \"FKLTUJIANZISHIWS\", \"FKLTUJIANZHIDINGHS\", \"FKLTUJIANZHIDINGWS\", \"FKLJIANDIANZISHIHS\", \"FKLJIDIANZISHIWS\", \"FKLJIDIANZHIDINGHS\", \"FKLJIDIANZHIDINGWS\", \"FNLTJZSCZHS\", \"FNLTJZSCZWS\", \"FNLTJZDCZHS\", \"FNLTJZDCZWS\", \"FNLJDZSCZHS\", \"FNLJDZSCZWS\", \"FNLJDZDCZHS\", \"FNLJDZDCZWS\", \"FZBID\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FKLTUJIANZISHIHS\", \"2019-12/土建-自施-含税\"}, {\"FKLTUJIANZISHIWS\", \"2019-12/土建-自施-无税\"}, {\"FKLTUJIANZHIDINGHS\", \"2019-12/土建-指定-含税\"}, {\"FKLTUJIANZHIDINGWS\", \"2019-12/土建-指定-无税\"}, {\"FKLJIANDIANZISHIHS\", \"2019-12/机电-自施-含税\"}, {\"FKLJIDIANZISHIWS\", \"2019-12/机电-自施-无税\"}, {\"FKLJIDIANZHIDINGHS\", \"2019-12/机电-指定-含税\"}, {\"FKLJIDIANZHIDINGWS\", \"2019-12/机电-指定-无税\"}, {\"FNLTJZSCZHS\", \"2020-5/土建-自施-含税\"}, {\"FNLTJZSCZWS\", \"2020-5/土建-自施-无税\"}, {\"FNLTJZDCZHS\", \"2020-5/土建-指定-含税\"}, {\"FNLTJZDCZWS\", \"2020-5/土建-指定-无税\"}, {\"FNLJDZSCZHS\", \"2020-5/机电-自施-含税\"}, {\"FNLJDZSCZWS\", \"2020-5/机电-自施-无税\"}, {\"FNLJDZDCZHS\", \"2020-5/机电-指定-含税\"}, {\"FNLJDZDCZWS\", \"2020-5/机电-指定-无税\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "807f5a1d-4c5f-46d3-9a73-76d0e0ef042d",
        "queryGroup": "业主确认量"
      },
      {
        "name": "确认量历史年度结算表主表",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(数据库连接, [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WANCHENGLIANGJIEZHUANZB1 = GSPM{[Name=\"GSPM_WANCHENGLIANGJIEZHUANZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WANCHENGLIANGJIEZHUANZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FXIANGMUMINGCHENG\", \"FID\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "66b53a0c-0643-4cae-a6a2-188ff96eedc8",
        "queryGroup": "业主确认量"
      },
      {
        "name": "结转确认量",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.NestedJoin(确认量历史年度结算表从表, {\"FZBID\"}, 确认量历史年度结算表主表, {\"FID\"}, \"确认量历史年度结算表主表\", JoinKind.Inner),",
          "    #\"展开的“确认量历史年度结算表主表”\" = Table.ExpandTableColumn(源, \"确认量历史年度结算表主表\", {\"项目编码\", \"项目名称\"}, {\"项目编码\", \"项目名称\"}),",
          "    删除的列 = Table.RemoveColumns(#\"展开的“确认量历史年度结算表主表”\",{\"FZBID\"}),",
          "    逆透视的其他列 = Table.UnpivotOtherColumns(删除的列, {\"项目编码\", \"项目名称\"}, \"属性\", \"值\"),",
          "    按分隔符拆分列 = Table.SplitColumn(逆透视的其他列, \"属性\", Splitter.SplitTextByDelimiter(\"/\", QuoteStyle.Csv), {\"日期\", \"属性.2\"}),",
          "    已分析的日期 = Table.TransformColumns(按分隔符拆分列,{{\"日期\", each Date.From(DateTimeZone.From(_)), type date}}),",
          "    按分隔符拆分列1 = Table.SplitColumn(已分析的日期, \"属性.2\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"专业\", \"分包类型\", \"属性.2.3\"}),",
          "    已透视列 = Table.Pivot(按分隔符拆分列1, List.Distinct(按分隔符拆分列1[属性.2.3]), \"属性.2.3\", \"值\", List.Sum),",
          "    重命名的列 = Table.RenameColumns(已透视列,{{\"含税\", \"确认产值含税\"}, {\"无税\", \"确认产值无税\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "ffba8d49-5e73-4dc5-9ab0-894af7580511",
        "queryGroup": "业主确认量"
      },
      {
        "name": "Oracle/172 16 8 78/oracledb",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true])",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "ac08942a-f6b5-46d9-86fb-e2cd96060c6a",
        "queryGroup": "参数组"
      },
      {
        "name": "Oracle/172 16 8 199/orcl",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.199/orcl\", [HierarchicalNavigation=true])",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "d718c0be-11bb-40fa-8fa2-384b2088a82d",
        "queryGroup": "参数组"
      },
      {
        "name": "fx_List_生成字段更名列表",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    源 = (OWNER as text,TABLE_NAME as text) as list => let",
          "        源 =  #\"Oracle/172 16 8 78/oracledb\",",
          "        源1=Value.NativeQuery(源,\"select COLUMN_NAME,COMMENTS from all_col_comments where OWNER = '\" & OWNER &\"' and TABLE_NAME = '\" & TABLE_NAME & \"'\"),",
          "        替换的值 = Table.ReplaceValue(源1,null, each [COLUMN_NAME],Replacer.ReplaceValue,{\"COMMENTS\"}),",
          "        更改的类型 = Table.TransformColumnTypes(替换的值,{{\"COMMENTS\", type text}}),",
          "        删除的副本 = Table.Distinct(更改的类型, {\"COMMENTS\"}),",
          "        缩短说明字段长度=Table.TransformColumns(删除的副本, {{\"COMMENTS\", each Text.Start(_,15), type text}}),",
          "        自定义1 = List.Zip({缩短说明字段长度[COLUMN_NAME],缩短说明字段长度[COMMENTS]})",
          "    in",
          "        自定义1",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "be9b9ad4-48f0-4615-b917-7e66385a2c24",
        "queryGroup": "参数组"
      },
      {
        "name": "项目年度预算主表",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(#\"数据连接\", [HierarchicalNavigation=true]),",
          "    YSXT = 源{[Schema=\"YSXT\"]}[Data],",
          "    YSXT_XMNDYSB1 = YSXT{[Name=\"YSXT_XMNDYSB\"]}[Data],",
          "    // 按照年度参数取值",
          "    筛选的行 = Table.SelectRows(YSXT_XMNDYSB1, each [FPSZT] = \"已完成\" and [FYEAR] = #\"年度\"),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FXIANGMUMINGCHENG\", \"FXIANGMUBIANMA\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FXIANGMUBIANMA\", \"项目编码\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "b8bf2d9d-5f04-4832-b6b7-b797182332b9",
        "queryGroup": "预算\\全面预算"
      },
      {
        "name": "项目年度预算表资金情况",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(#\"数据连接\", [HierarchicalNavigation=true]),",
          "    YSXT = 源{[Schema=\"YSXT\"]}[Data],",
          "    YSXT_XMNDYSB_ZJCB1 = YSXT{[Name=\"YSXT_XMNDYSB_ZJCB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(YSXT_XMNDYSB_ZJCB1, each (List.Contains(选取预算科目[科目],[FKM]))),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FZBID\", \"FKM\", \"FYF1\", \"FYF2\", \"FYF3\", \"FYF4\", \"FYF5\", \"FYF6\", \"FYF7\", \"FYF8\", \"FYF9\", \"FYF10\", \"FYF11\", \"FYF12\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FKM\", \"科目\"}, {\"FYF1\", \"01\"}, {\"FYF2\", \"02\"}, {\"FYF3\", \"03\"}, {\"FYF4\", \"04\"}, {\"FYF5\", \"05\"}, {\"FYF6\", \"06\"}, {\"FYF7\", \"07\"}, {\"FYF8\", \"08\"}, {\"FYF9\", \"09\"}, {\"FYF10\", \"10\"}, {\"FYF11\", \"11\"}, {\"FYF12\", \"12\"}})",
          "in",
          "    重命名的列"
        ],
        "kind": "m",
        "lineageTag": "b92f8e7e-2073-41af-9158-25f8540fb5cf",
        "queryGroup": "预算\\全面预算"
      },
      {
        "name": "产值与营业收入换算系数",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Number"
          }
        ],
        "expression": "0.7763 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "c70df3b4-e07f-4811-b371-9914c33f9bd5",
        "queryGroup": "预算"
      },
      {
        "name": "选取预算科目",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WerKj6/meLU9b1zzt3/FyUcuzKduez+5SitUBycx6smP384XrXqxb8rK9Hyz2dGrb066FT3Ytf9qwR+PphNXPV/RpQiS2L32+ovvZmn3PtjY+bV2q8bxvw8v2iU/7Fz/d14JdxdPWFcjSz6btBaqAmAwWgJgAUYwm0L4L0zFPdvQiuweHt2IB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [科目 = _t])",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "92aec9f2-dbba-4b25-9b98-3d8da083d5a0",
        "queryGroup": "预算"
      },
      {
        "name": "X5",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(数据连接, [HierarchicalNavigation=true])",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "4744932c-645b-4d5b-9e9d-4ac4e32e98b0",
        "queryGroup": "参数组"
      },
      {
        "name": "GSPM_CBFKJD_HKPF_ZB（业主收款初始化主表）",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = #\"X5\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CBFKJD_HKPF_ZB1 = GSPM{[Name=\"GSPM_CBFKJD_HKPF_ZB\"]}[Data],",
          "    重命名的列 = Table.RenameColumns(GSPM_CBFKJD_HKPF_ZB1,#\"fx_List_生成字段更名列表\"(\"GSPM\",\"GSPM_CBFKJD_HKPF_ZB\")),",
          "    筛选的行 = Table.SelectRows(重命名的列, each ([评审状态] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"项目编码\", \"项目名称\", \"FID\", \"创建时间\"}),",
          "    排序的行 = Table.Sort(删除的其他列,{{\"项目编码\", Order.Ascending}, {\"创建时间\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"项目编码\"}),",
          "    提取的日期 = Table.TransformColumns(删除的副本,{{\"创建时间\", DateTime.Date, type date}}),",
          "    删除的列 = Table.RemoveColumns(提取的日期,{\"索引\"}),",
          "    重命名的列1 = Table.RenameColumns(删除的列,{{\"创建时间\", \"实际回款日期\"}})",
          "in",
          "    重命名的列1"
        ],
        "kind": "m",
        "lineageTag": "31eb184f-d269-4358-b331-6eb7f25cbba3",
        "queryGroup": "业主合同回款"
      },
      {
        "name": "GSPM_CBFKJD_HKPF_C1B（业主收款初始化明细）",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = #\"X5\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CBFKJD_HKPF_ZB1 = GSPM{[Name=\"GSPM_CBFKJD_HKPF_C1B\"]}[Data],",
          "    重命名的列 = Table.RenameColumns(GSPM_CBFKJD_HKPF_ZB1,#\"fx_List_生成字段更名列表\"(\"GSPM\",\"GSPM_CBFKJD_HKPF_C1B\")),",
          "    删除的其他列 = Table.SelectColumns(重命名的列,{\"合同编号\", \"主表ID\", \"累计回款金额\", \"其中土建自施劈分总额\", \"其中机电自施劈分总额\", \"其中土建指定劈分总额\", \"其中机电指定劈分总额\"}),",
          "    重命名的列1 = Table.RenameColumns(删除的其他列,{{\"其中土建自施劈分总额\", \"土建-自施\"}, {\"其中机电自施劈分总额\", \"机电-自施\"}, {\"其中土建指定劈分总额\", \"土建-指定\"}, {\"其中机电指定劈分总额\", \"机电-指定\"}})",
          "in",
          "    重命名的列1"
        ],
        "kind": "m",
        "lineageTag": "a292381a-44cc-4c6b-859e-444964bd6086",
        "queryGroup": "业主合同回款"
      },
      {
        "name": "业主合同回款初始化",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.NestedJoin(#\"GSPM_CBFKJD_HKPF_ZB（业主收款初始化主表）\", {\"FID\"}, #\"GSPM_CBFKJD_HKPF_C1B（业主收款初始化明细）\", {\"主表ID\"}, \"GSPM_CBFKJD_HKPF_ZB（业主收款初始化明细）\", JoinKind.Inner),",
          "    #\"展开的“GSPM_CBFKJD_HKPF_ZB（业主收款初始化明细）”\" = Table.ExpandTableColumn(源, \"GSPM_CBFKJD_HKPF_ZB（业主收款初始化明细）\", {\"合同编号\", \"土建-自施\", \"机电-自施\", \"土建-指定\", \"机电-指定\"}, {\"合同编号\", \"土建-自施\", \"机电-自施\", \"土建-指定\", \"机电-指定\"}),",
          "    删除的列 = Table.RemoveColumns(#\"展开的“GSPM_CBFKJD_HKPF_ZB（业主收款初始化明细）”\",{\"FID\"}),",
          "    已添加自定义 = Table.AddColumn(删除的列, \"回款类型\", each \"初始化\",Text.Type),",
          "    逆透视的列 = Table.UnpivotOtherColumns(已添加自定义, {\"项目编码\", \"项目名称\", \"实际回款日期\", \"合同编号\", \"回款类型\"}, \"属性\", \"金额\"),",
          "    按分隔符拆分列 = Table.SplitColumn(逆透视的列, \"属性\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"施工专业\", \"分包类型\"})",
          "in",
          "    按分隔符拆分列"
        ],
        "kind": "m",
        "lineageTag": "7f8891ac-6b85-469b-b5bb-b59a020d7c1c",
        "queryGroup": "业主合同回款"
      },
      {
        "name": "GSPM_GONGCHENGKUANHS_ZB（业主收款主表）",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = #\"X5\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CBFKJD_HKPF_ZB1 = GSPM{[Name=\"GSPM_GONGCHENGKUANHS_ZB\"]}[Data],",
          "    重命名的列 = Table.RenameColumns(GSPM_CBFKJD_HKPF_ZB1,#\"fx_List_生成字段更名列表\"(\"GSPM\",\"GSPM_GONGCHENGKUANHS_ZB\")),",
          "    筛选的行 = Table.SelectRows(重命名的列, each ([评审状态] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"项目编码\", \"项目名称\"})",
          "in",
          "    删除的其他列"
        ],
        "kind": "m",
        "lineageTag": "2d6fc133-75f7-4219-bae3-c2e99187ee1d",
        "queryGroup": "业主合同回款"
      },
      {
        "name": "GSPM_GONGCHENGKUANHS_ZB（业主收款明细）",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = #\"X5\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_CBFKJD_HKPF_ZB1 = GSPM{[Name=\"GSPM_GONGCHENGKUANHS_CB\"]}[Data],",
          "    重命名的列 = Table.RenameColumns(GSPM_CBFKJD_HKPF_ZB1,#\"fx_List_生成字段更名列表\"(\"GSPM\",\"GSPM_GONGCHENGKUANHS_CB\"),MissingField.Ignore),",
          "    #\"筛选的行（去掉收款为null）\" = Table.SelectRows(重命名的列, each ([本次回款金额] <> null)),",
          "    删除的其他列1 = Table.SelectColumns(#\"筛选的行（去掉收款为null）\",{\"合同编号\", \"实际回款日期\", \"其中土建自施\", \"其中土建指定\", \"其中机电自施\", \"其中机电指定\", \"回款类型\", \"主表ID\"}),",
          "    重命名的列1 = Table.RenameColumns(删除的其他列1,{{\"其中土建自施\", \"土建-自施\"}, {\"其中土建指定\", \"土建-指定\"}, {\"其中机电自施\", \"机电-自施\"}, {\"其中机电指定\", \"机电-指定\"}}),",
          "    提取的日期 = Table.TransformColumns(重命名的列1,{{\"实际回款日期\", DateTime.Date, type date}})",
          "in",
          "    提取的日期"
        ],
        "kind": "m",
        "lineageTag": "5214bd04-7075-484d-a5f8-8ba4925d70ef",
        "queryGroup": "业主合同回款"
      },
      {
        "name": "业主合同回款登记",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Table.NestedJoin(#\"GSPM_GONGCHENGKUANHS_ZB（业主收款主表）\", {\"FID\"}, #\"GSPM_GONGCHENGKUANHS_ZB（业主收款明细）\", {\"主表ID\"}, \"GSPM_GONGCHENGKUANHS_ZB（业主收款明细）\", JoinKind.Inner),",
          "    #\"展开的“GSPM_GONGCHENGKUANHS_ZB（业主收款明细）”\" = Table.ExpandTableColumn(源, \"GSPM_GONGCHENGKUANHS_ZB（业主收款明细）\", {\"合同编号\", \"实际回款日期\", \"土建-自施\", \"土建-指定\", \"机电-自施\", \"机电-指定\", \"回款类型\"}, {\"合同编号\", \"实际回款日期\", \"土建-自施\", \"土建-指定\", \"机电-自施\", \"机电-指定\", \"回款类型\"}),",
          "    删除的列 = Table.RemoveColumns(#\"展开的“GSPM_GONGCHENGKUANHS_ZB（业主收款明细）”\",{\"FID\"}),",
          "    逆透视的列 = Table.UnpivotOtherColumns(删除的列, {\"项目编码\", \"项目名称\", \"合同编号\", \"实际回款日期\", \"回款类型\"}, \"属性\", \"金额\"),",
          "    按分隔符拆分列 = Table.SplitColumn(逆透视的列, \"属性\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"施工专业\", \"分包类型\"})",
          "in",
          "    按分隔符拆分列"
        ],
        "kind": "m",
        "lineageTag": "a3b9f362-c497-4bff-94d7-31fa684b3456",
        "queryGroup": "业主合同回款"
      },
      {
        "name": "项管产值",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_XMSC_WCQK_YUEBAO = GSPM{[Name=\"GSPM_XMSC_WCQK_YUEBAO\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_XMSC_WCQK_YUEBAO, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUMINGCHENG\", \"FXIANGMUBIANMA\", \"FNIAN\", \"FYUE\", \"FHJNLSGCZ\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FHJNLSGCZ\", \"本年累计产值\"}}),",
          "    被乘的列 = Table.TransformColumns(重命名的列, {{\"本年累计产值\", each _ * 10000, type number}}),",
          "    已添加自定义 = Table.AddColumn(被乘的列, \"日期\", each #date([年],[月],1),Date.Type),",
          "    删除的其他列1 = Table.SelectColumns(已添加自定义,{\"项目名称\", \"项目编码\", \"日期\", \"本年累计产值\"})",
          "in",
          "    删除的其他列1"
        ],
        "kind": "m",
        "lineageTag": "1cb34bbc-8b98-4245-9435-d7ef3a008214",
        "queryGroup": "项管口径产值"
      },
      {
        "name": "项目收益率",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = 项目编码,",
          "    删除的其他列 = Table.SelectColumns(源,{\"FXMBIANMA\", \"FXMQUANCHENG\", \"FTUJIANHEDINGSYL\", \"FJIDIANHEDINGSYL\", \"FTUJIANHEDINGSYLJZ\", \"FJIDIANHEDINGSYLJZ\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FTUJIANHEDINGSYL\", \"土建-自施\"}, {\"FJIDIANHEDINGSYL\", \"机电-自施\"}, {\"FTUJIANHEDINGSYLJZ\", \"土建-甲指\"}, {\"FJIDIANHEDINGSYLJZ\", \"机电-甲指\"}, {\"FXMBIANMA\", \"项目编码\"}, {\"FXMQUANCHENG\", \"项目名称\"}}),",
          "    逆透视的其他列 = Table.UnpivotOtherColumns(重命名的列, {\"项目编码\",\"项目名称\"}, \"属性\", \"值\"),",
          "    按分隔符拆分列 = Table.SplitColumn(逆透视的其他列, \"属性\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"属性.1\", \"属性.2\"}),",
          "    更改的类型 = Table.TransformColumnTypes(按分隔符拆分列,{{\"属性.1\", type text}, {\"属性.2\", type text}}),",
          "    重命名的列1 = Table.RenameColumns(更改的类型,{{\"属性.1\", \"专业\"}, {\"属性.2\", \"分包类型\"}, {\"值\", \"收益率\"}}),",
          "    已添加条件列 = Table.AddColumn(重命名的列1, \"收益率-调整\", each if [项目编码] = \"U_ORG_XM_BJDCBGLGKJ\" then 0.0606 else if [项目编码] = \"U_ORG_XM_HJDYH\" then 0.0558 else [收益率],type number),",
          "    删除的列 = Table.RemoveColumns(已添加条件列,{\"收益率\"}),",
          "    复制的列 = Table.DuplicateColumn(删除的列, \"专业\", \"专业 - 复制\"),",
          "    复制的列1 = Table.DuplicateColumn(复制的列, \"分包类型\", \"分包类型 - 复制\"),",
          "    合并的列 = Table.CombineColumns(复制的列1,{\"项目编码\", \"分包类型 - 复制\", \"专业 - 复制\"},Combiner.CombineTextByDelimiter(\"-\", QuoteStyle.None),\"已合并\")",
          "in",
          "    合并的列"
        ],
        "kind": "m",
        "lineageTag": "31ff98b8-8e1b-40c0-a362-1b36a0beed2f",
        "queryGroup": "维度"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "参数组"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "产值收益"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "维度"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "维度\\项目状态(已竣已结、已竣未结每季度需要更换文件)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "5"
          }
        ],
        "folder": "业主合同"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "6"
          }
        ],
        "folder": "业主确认量"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "7"
          }
        ],
        "description": "已加载到 2022/6/22 星期三 15:51:27 上的查询中的错误。",
        "folder": "查询错误 - 2022/6/22 星期三 15:51:27"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "9"
          }
        ],
        "folder": "预算"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "预算\\全面预算"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "12"
          }
        ],
        "folder": "项管口径产值"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "10"
          }
        ],
        "folder": "业主合同回款"
      }
    ],
    "relationships": [
      {
        "name": "90db5d0f-8d6e-49b3-88ef-380e4b2f7570",
        "fromColumn": "责任体",
        "fromTable": "D-项目",
        "toColumn": "责任体",
        "toTable": "D-责任体"
      },
      {
        "name": "e2bb0bc9-f1f5-420c-8f31-73347770f0cf",
        "fromColumn": "项目所属大客户",
        "fromTable": "D-项目",
        "toColumn": "大客户",
        "toTable": "D-大客户简称"
      },
      {
        "name": "f4699931-5765-4142-ac2c-5f4185c00d80",
        "fromColumn": "专业",
        "fromTable": "F_商务产值收益",
        "toColumn": "专业",
        "toTable": "D-专业"
      },
      {
        "name": "699c3e13-b71a-490b-8a51-d4c0afd33e76",
        "fromColumn": "分包类型",
        "fromTable": "F_商务产值收益",
        "toColumn": "分包类型",
        "toTable": "D-分包类型"
      },
      {
        "name": "1a00bfd1-8d1d-4459-a43a-ae5e795b936a",
        "fromColumn": "项目编码",
        "fromTable": "F_商务产值收益",
        "toColumn": "项目编码",
        "toTable": "D-项目"
      },
      {
        "name": "7ccb4bfe-b944-47b2-92f3-989df9559fc0",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "责任体",
        "fromTable": "分公司总经",
        "securityFilteringBehavior": "bothDirections",
        "toColumn": "责任体",
        "toTable": "D-责任体"
      },
      {
        "name": "91ea0819-ef72-42e7-ab62-e39cd4c4edd6",
        "fromColumn": "项目编码",
        "fromTable": "F_业主合同",
        "toColumn": "项目编码",
        "toTable": "D-项目"
      },
      {
        "name": "20174346-3940-440f-a756-f35c93c16e47",
        "fromColumn": "项目编码",
        "fromTable": "F_业主确认量",
        "toColumn": "项目编码",
        "toTable": "D-项目"
      },
      {
        "name": "d9c95e8c-2499-4f42-ab8f-11f155152877",
        "fromColumn": "专业",
        "fromTable": "F_业主确认量",
        "toColumn": "专业",
        "toTable": "D-专业"
      },
      {
        "name": "0b16d142-3731-41a6-8a10-7dcf345409f7",
        "fromColumn": "分包类型",
        "fromTable": "F_业主确认量",
        "toColumn": "分包类型",
        "toTable": "D-分包类型"
      },
      {
        "name": "28a00270-e4e4-4e93-9100-d56357ab7072",
        "fromColumn": "日期",
        "fromTable": "F_商务产值收益",
        "toColumn": "日期",
        "toTable": "D-日历"
      },
      {
        "name": "d05c00c8-4977-425f-a54c-c22125d84365",
        "fromColumn": "签订日期",
        "fromTable": "F_业主合同",
        "toColumn": "日期",
        "toTable": "D-日历"
      },
      {
        "name": "a5b3301c-18cc-492e-ac3a-eaffb6298a02",
        "fromColumn": "日期",
        "fromTable": "F_业主确认量",
        "toColumn": "日期",
        "toTable": "D-日历"
      },
      {
        "name": "124fb988-0c61-483a-a416-a2a0a9bb0ff1",
        "fromColumn": "项目编码",
        "fromTable": "F_全面预算",
        "toColumn": "项目编码",
        "toTable": "D-项目"
      },
      {
        "name": "6fd72720-9932-4c26-95a8-d038a72e4517",
        "fromColumn": "日期",
        "fromTable": "F_全面预算",
        "toColumn": "日期",
        "toTable": "D-日历"
      },
      {
        "name": "a39cd21b-2901-4673-bfdf-1b3d18973216",
        "fromColumn": "实际回款日期",
        "fromTable": "F_业主合同回款",
        "toColumn": "日期",
        "toTable": "D-日历"
      },
      {
        "name": "ac457d5a-ba17-4196-9f97-ec8bc3a3281e",
        "fromColumn": "项目编码",
        "fromTable": "F_业主合同回款",
        "toColumn": "项目编码",
        "toTable": "D-项目"
      }
    ],
    "roles": [
      {
        "name": "总部",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "45583a147f5e4e31aa2c0fecaa63fb51"
          }
        ],
        "modelPermission": "read"
      },
      {
        "name": "分公司",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b09080acb7494bdb91687ab2d01c3c38"
          }
        ],
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "分公司总经",
            "filterExpression": "[帐号] = USERNAME()"
          }
        ]
      }
    ],
    "sourceQueryCulture": "zh-CN",
    "tables": [
      {
        "name": "D-专业",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "专业",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "faf8ea31-4d23-4124-85af-dc14d9866d2a",
            "sourceColumn": "专业",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "5e935412-f003-4434-823d-d7c015cbda3c",
        "partitions": [
          {
            "name": "D-专业-b167fa2a-7d05-401b-be85-2569fa8d6a65",
            "mode": "import",
            "queryGroup": "维度",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wejpn/tPdu5RidaKVns3Z9XzKVqXYWAA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [专业 = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"专业\", type text}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "D-分包类型",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "分包类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c7c7f1a-66d7-4eda-b0cd-612a33563ddb",
            "sourceColumn": "分包类型",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "b4f95c6f-84d8-4d7e-8df4-f5b102ee38f6",
        "partitions": [
          {
            "name": "D-分包类型-bd84e0b1-948c-44f8-b859-2e41ee88471c",
            "mode": "import",
            "queryGroup": "维度",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WetG+6tm0vUqxOtFKz3ran66bpRQbCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [分包类型 = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"分包类型\", type text}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "D-单位",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "单位",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c96c0b5b-f92e-459d-bb59-a53b4282089a",
            "sourceColumn": "单位",
            "summarizeBy": "none"
          },
          {
            "name": "序号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25f1de2d-c70b-4d47-87a9-257ed1844c09",
            "sourceColumn": "序号",
            "summarizeBy": "sum"
          },
          {
            "name": "系数",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9b0e8b8e-63da-40d3-b8d2-08563946c768",
            "sourceColumn": "系数",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "b317074f-412f-4ada-8346-e79486f07e21",
        "partitions": [
          {
            "name": "D-单位-49c6db8e-3e86-4e78-ba3a-aefe6d9e3f78",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WetrarKSjZAjGsTrRSk92tEOFDIAASBtBhHftRxKGShkrxcYCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [单位 = _t, 系数 = _t, 序号 = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"系数\", Int64.Type}, {\"序号\", Int64.Type}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "D-大客户简称",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "大客户",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4d5b385-5927-4b97-b716-5bee43a3e008",
            "sourceColumn": "大客户",
            "summarizeBy": "none"
          },
          {
            "name": "大客户简称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8aaacd0-c742-4184-9bbf-56f6e49713a5",
            "sourceColumn": "大客户简称",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "8a1350c7-7771-4f4d-b80d-ddb62cea8b86",
        "partitions": [
          {
            "name": "D-大客户简称-c66d63cf-591d-4504-b269-d63789f2e7f1",
            "mode": "import",
            "queryGroup": "维度",
            "source": {
              "expression": [
                "let",
                "    源 = Excel.Workbook(File.Contents(\"\\\\172.16.8.66\\经营分析\\经营分析会\\大客户简称.xlsx\"), null, true),",
                "    商务偏差汇总表1 = 源{[Name=\"商务偏差汇总表\"]}[Data],",
                "    更改的类型 = Table.TransformColumnTypes(商务偏差汇总表1,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    提升的标题 = Table.PromoteHeaders(更改的类型, [PromoteAllScalars=true]),",
                "    更改的类型1 = Table.TransformColumnTypes(提升的标题,{{\"Column1\", type text}, {\"Column2\", type text}}),",
                "    提升的标题1 = Table.PromoteHeaders(更改的类型1, [PromoteAllScalars=true]),",
                "    更改的类型2 = Table.TransformColumnTypes(提升的标题1,{{\"大客户\", type text}, {\"大客户简称\", type text}}),",
                "    筛选的行 = Table.SelectRows(更改的类型2, each ([大客户简称] <> null))",
                "in",
                "    筛选的行"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "D-日历",
        "columns": [
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('D-日历'[日期],\"yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "36837cb2-574e-48b7-8cc8-fc3cb55b4845",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "年月",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('D-日历'[日期],\"yyyy-MM\")",
            "isDataTypeInferred": true,
            "lineageTag": "e78a0710-a913-47a5-8fb2-1a867951fc63",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "年月名",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "VAR MY=MONTH(MAX('F_商务产值收益'[日期])) RETURN IF(MY=MONTH('D-日历'[日期]),\"\", FORMAT('D-日历'[日期],\"yyyy-MM\"))",
            "isDataTypeInferred": true,
            "lineageTag": "cc9bf8f0-4a73-4529-ade4-fe883115b3ac",
            "sortByColumn": "年月",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": false,
            "lineageTag": "0b69c925-0fd0-402c-994b-dcc36c3e2009",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "26355ddd-0535-4fe8-ac05-97277aef3943",
        "partitions": [
          {
            "name": "D-日历-1c98b3ce-c44f-4582-aa9f-5d19f92f4c7e",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(\"2017-1-1\",TODAY())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "D-责任体",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "排序",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ecc221e-b8db-4738-a217-d7ce6cadbb4c",
            "sourceColumn": "排序",
            "summarizeBy": "sum"
          },
          {
            "name": "责任体",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ca45f28-b0b6-42d5-b52b-a155b6bb3270",
            "sortByColumn": "排序",
            "sourceColumn": "责任体",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "a8ec786b-6d16-4d0d-934c-295275337fb8",
        "partitions": [
          {
            "name": "D-责任体-8c65f55e-fed8-4133-af65-8483dd5ccc9f",
            "mode": "import",
            "queryGroup": "维度",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wetq65mn/juezt7yYsFRJR8lQKVYnWunJjjlPe6Y/7WiDyALFjcDiT3v70MSNYeIgLUjiJnD1vSjqTcHiL5buRxM3A4s/X7PmyY6GJ7u6n+yY9bJ5BVDcHC6+qwdZ3AKhvhNZ3BIm/nT2bGRxQwOwxLOt258umQbiQz20c/+TvbOfzu97uqMJ7hZDYCDEAgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [责任体 = _t, 排序 = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"责任体\", type text}, {\"排序\", Int64.Type}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "D-项目",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "专业分类",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39be80ed-bd5a-47db-98d6-5281ce92a7a1",
            "sourceColumn": "专业分类",
            "summarizeBy": "none"
          },
          {
            "name": "业务板块",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26de1a7d-eee2-460c-9bfe-208a6dfc7f25",
            "sourceColumn": "业务板块",
            "summarizeBy": "none"
          },
          {
            "name": "京内外",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da69ca76-54b1-481c-b82a-51acea57ffd6",
            "sourceColumn": "京内外",
            "summarizeBy": "none"
          },
          {
            "name": "利润中心编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9ac92d7-fdc7-4756-8342-aef30979f280",
            "sourceColumn": "利润中心编码",
            "summarizeBy": "none"
          },
          {
            "name": "区县",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47e1d4e4-1936-42c0-b526-cc2e35a89cc1",
            "sourceColumn": "区县",
            "summarizeBy": "none"
          },
          {
            "name": "厂房事业部",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "546cfba2-5816-45a6-a73a-105e8157718e",
            "sourceColumn": "厂房事业部",
            "summarizeBy": "none"
          },
          {
            "name": "合同开工日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1d595e68-3c5e-46d0-b9be-44d7ca382c5b",
            "sourceColumn": "合同开工日期",
            "summarizeBy": "none"
          },
          {
            "name": "合同竣工日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f5492942-14bc-4b46-a3c4-a9edbf4a98d0",
            "sourceColumn": "合同竣工日期",
            "summarizeBy": "none"
          },
          {
            "name": "土建核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0c56b8c2-971c-48d0-832e-07a271466a25",
            "sourceColumn": "土建核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "土建甲指核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b4f43e2b-6b90-4e37-9e2c-a7480151843a",
            "sourceColumn": "土建甲指核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "城市",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38e16ea1-cd4c-42dc-9954-c1edb15e2967",
            "sourceColumn": "城市",
            "summarizeBy": "none"
          },
          {
            "name": "城市公司",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0352bafc-b23f-4d44-9156-a7fd431a8166",
            "sourceColumn": "城市公司",
            "summarizeBy": "none"
          },
          {
            "name": "实际开工日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "81ea8856-9517-441b-8065-633f225d60a7",
            "sourceColumn": "实际开工日期",
            "summarizeBy": "none"
          },
          {
            "name": "实际竣工日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e1372c22-8f4f-474f-b527-14bb7eb4fff4",
            "sourceColumn": "实际竣工日期",
            "summarizeBy": "none"
          },
          {
            "name": "工程类别一级",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eca8d4aa-404a-423a-a319-a5feb9aef78a",
            "sourceColumn": "工程类别一级",
            "summarizeBy": "none"
          },
          {
            "name": "工程类别二级",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d9850e69-c83a-4137-a7ee-e7d7388a0886",
            "sourceColumn": "工程类别二级",
            "summarizeBy": "none"
          },
          {
            "name": "所属总监团队",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c3dc4b79-950e-430f-8881-d5042197f8c4",
            "sourceColumn": "所属总监团队",
            "summarizeBy": "none"
          },
          {
            "name": "投资非投资项目",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a28db634-cf90-4ae4-acbe-311f3ccd010a",
            "sourceColumn": "投资非投资项目",
            "summarizeBy": "none"
          },
          {
            "name": "是否投资建造项目",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1e60a99-1fc3-420d-8ac5-39c0afa562d0",
            "sourceColumn": "是否投资建造项目",
            "summarizeBy": "none"
          },
          {
            "name": "机电核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "65c6f6e9-1e2d-40c2-8fa6-fcd792f92961",
            "sourceColumn": "机电核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "机电甲指核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7de788d6-17ab-46e6-ac73-9d6addc359a3",
            "sourceColumn": "机电甲指核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9dd4cdc-7656-4dc1-a816-b04477482309",
            "sourceColumn": "状态",
            "summarizeBy": "none"
          },
          {
            "name": "直管机构",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bacdcf1-f594-4b36-ac70-fc4b88b25d1e",
            "sourceColumn": "直管机构",
            "summarizeBy": "none"
          },
          {
            "name": "省",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "303e6e79-413c-4292-8010-c46110370930",
            "sourceColumn": "省",
            "summarizeBy": "none"
          },
          {
            "name": "综合核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bafd21f1-d5e6-4adb-91e2-69a6d672145a",
            "sourceColumn": "综合核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "行政区域",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a395f9a-d27d-49bc-b55f-85d5cc68ffef",
            "sourceColumn": "行政区域",
            "summarizeBy": "none"
          },
          {
            "name": "责任体",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19eaf80e-f2c5-4f5a-befc-b19cbbaceb69",
            "sourceColumn": "责任体",
            "summarizeBy": "none"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1fcace7e-eedd-479b-bd32-ea2c8002bd17",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目实施状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99a18b1b-538c-46d7-b7c5-664b68dd1f43",
            "sourceColumn": "项目实施状态",
            "summarizeBy": "none"
          },
          {
            "name": "项目性质",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "643b6899-21c1-4956-bfd5-9c96ba4b52ee",
            "sourceColumn": "项目性质",
            "summarizeBy": "none"
          },
          {
            "name": "项目总监",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f07b8307-341e-4b84-ab55-cd198e080dea",
            "sourceColumn": "项目总监",
            "summarizeBy": "none"
          },
          {
            "name": "项目所属大客户",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97361f91-c5d7-49b5-bf7e-88a19f162fd7",
            "sourceColumn": "项目所属大客户",
            "summarizeBy": "none"
          },
          {
            "name": "项目类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63631f24-5fff-4352-991b-e111ff1ae796",
            "sourceColumn": "项目类型",
            "summarizeBy": "none"
          },
          {
            "name": "项目结算状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cff074e6-13be-43aa-821a-2ea5ec7fe1c4",
            "sourceColumn": "项目结算状态",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "280e052d-ac03-475b-8b0b-cc625ea20ed9",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          },
          {
            "name": "项目财务状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe7b6f49-43f0-44d3-a51a-9597dcc5ef9d",
            "sourceColumn": "项目财务状态",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d834cb8f-2dd7-4323-8768-599629fb8c63",
        "partitions": [
          {
            "name": "D-项目-3f74781e-1000-42f6-abf4-88db7884b971",
            "mode": "import",
            "queryGroup": "维度",
            "source": {
              "expression": [
                "let",
                "    源 = 项目编码,",
                "    重命名的列 = Table.RenameColumns(源,{{\"FXMBIANMA\", \"项目编码\"}, {\"FXMQUANCHENG\", \"项目名称\"}, {\"FXMZONGJIAN\", \"项目总监\"}, {\"FZHUANYEFL\", \"专业分类\"}, {\"FXMXINGZHI\", \"项目性质\"}, {\"FJNWFB\", \"京内外\"}, {\"FQUYU\", \"行政区域\"}, {\"FSHENG\", \"省\"}, {\"FCHENGSHI\", \"城市\"}, {\"FXIAN\", \"区县\"}, {\"FXMSSZT\", \"项目实施状态\"}, {\"FGCLBYJ\", \"工程类别一级\"}, {\"FGCLBEJ\", \"工程类别二级\"}, {\"FXMJSZT\", \"项目结算状态\"}, {\"FXMSZDKH\", \"项目所属大客户\"}, {\"FSFTZJZXM\", \"是否投资建造项目\"}, {\"FPINGSHENZHUANGTAIID\", \"FPINGSHENZHUANGTAIID\"}, {\"FZHIGUANJGXG\", \"直管机构\"}, {\"FXIANGMULEIXING\", \"项目类型\"}, {\"FZONGJIANTUANDUI\", \"所属总监团队\"}, {\"FXMCAIWUZHUANGTAI\", \"项目财务状态\"}, {\"FYWBK\", \"业务板块\"}, {\"FTUJIANHEDINGSYL\", \"土建核定收益率\"}, {\"FJIDIANHEDINGSYL\", \"机电核定收益率\"}, {\"FZONGHEHEDINGSYL\", \"综合核定收益率\"}, {\"FTUJIANHEDINGSYLJZ\", \"土建甲指核定收益率\"}, {\"FJIDIANHEDINGSYLJZ\", \"机电甲指核定收益率\"}, {\"FCHANGFANGSHIYEBU\", \"厂房事业部\"}, {\"FGFYTHLRZXBM\", \"利润中心编码\"}, {\"FHTKGRQ\", \"合同开工日期\"}, {\"FHTJGRQ\", \"合同竣工日期\"}, {\"FSJKGRQ\", \"实际开工日期\"}, {\"FSJJGRQ\", \"实际竣工日期\"}, {\"FGFCWYTHXMBM\", \"利润中心\"}, {\"FCHENGSHIGONGSI\", \"城市公司\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"项目编码\", \"项目名称\", \"项目总监\", \"专业分类\", \"项目性质\", \"京内外\", \"行政区域\", \"省\", \"城市\", \"区县\", \"实际开工日期\", \"实际竣工日期\", \"项目实施状态\", \"工程类别一级\", \"工程类别二级\", \"合同开工日期\", \"合同竣工日期\", \"项目结算状态\", \"项目所属大客户\", \"是否投资建造项目\", \"项目类型\", \"直管机构\", \"土建甲指核定收益率\", \"机电甲指核定收益率\", \"厂房事业部\", \"所属总监团队\", \"项目财务状态\", \"业务板块\", \"利润中心编码\", \"城市公司\", \"土建核定收益率\", \"机电核定收益率\", \"综合核定收益率\"}),",
                "    缓存表 = Table.Buffer(删除的其他列),",
                "    // 计算责任体",
                "    #\"已添加条件列（计算责任体）\" = Table.AddColumn(缓存表, \"责任体\", each if [京内外] = \"国际\" then \"海外\" else if [厂房事业部] <> null then [厂房事业部] else if [直管机构] <> \"公司\" then [直管机构] else if [城市公司] <> null then [城市公司] else \"公司直营\"),",
                "    // 计算投资非投资",
                "    #\"已添加条件列（计算是否投资项目）\" = Table.AddColumn(#\"已添加条件列（计算责任体）\", \"投资非投资项目\", each if [是否投资建造项目] = \"是\" then \"投资项目\" else \"非投资项目\",Text.Type),",
                "    替换的值 = Table.ReplaceValue(#\"已添加条件列（计算是否投资项目）\",\"机电\",\"机电总包\",Replacer.ReplaceValue,{\"业务板块\"}),",
                "    // 获取项目状态",
                "    合并的查询 = Table.NestedJoin(替换的值, {\"项目编码\"}, 项目状态, {\"项目编码\"}, \"项目状态.1\", JoinKind.LeftOuter),",
                "    #\"展开的“项目状态.1”\" = Table.ExpandTableColumn(合并的查询, \"项目状态.1\", {\"状态\"}, {\"状态\"}),",
                "    替换的值1 = Table.ReplaceValue(#\"展开的“项目状态.1”\",null,\"在施结转\",Replacer.ReplaceValue,{\"状态\"}),",
                "    // 追加分公司虚拟项目",
                "    追加的查询 = Table.Combine({替换的值1, 分公司虚拟项目})",
                "in",
                "    追加的查询"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F_业主合同",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "专业",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e50dda30-91ca-4b94-b931-f3c89b2e44e2",
            "sourceColumn": "专业",
            "summarizeBy": "none"
          },
          {
            "name": "分包类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "67b9adbb-e536-4cd4-ad3c-0b0fb2705e29",
            "sourceColumn": "分包类型",
            "summarizeBy": "none"
          },
          {
            "name": "含税合同额",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2a518a5-d45b-49fa-91bb-ca03ddb13d28",
            "sourceColumn": "含税合同额",
            "summarizeBy": "sum"
          },
          {
            "name": "无税合同额",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "4b08013d-13c3-49f3-8104-5286225e0ea4",
            "sourceColumn": "无税合同额",
            "summarizeBy": "sum"
          },
          {
            "name": "签订日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6ff8df46-a1e6-4897-be73-fec530cdfc41",
            "sourceColumn": "签订日期",
            "summarizeBy": "none"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "106a3e69-f860-41c4-b668-a6882e7ee71c",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "540310a7-0776-4213-9354-8270bee0a1ad",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0384c6f2-8947-4743-aa0b-f52790a0cd50",
        "partitions": [
          {
            "name": "F_业主合同-332a1e9b-12bd-41fb-b6a8-ba9ee8d2cf35",
            "mode": "import",
            "queryGroup": "业主合同",
            "source": {
              "expression": [
                "let",
                "    源 = Oracle.Database(数据连接, [HierarchicalNavigation=true]),",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_CHENGBAOHETONGXINXI1 = GSPM{[Name=\"GSPM_CHENGBAOHETONGXINXI\"]}[Data],",
                "    筛选的行 = Table.SelectRows(GSPM_CHENGBAOHETONGXINXI1, each ([FHETONGFENLEI1] <> \"框架协议\") and ([FHETONGFENLEI2] <> \"备案\")),",
                "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FDUIYINGGONGCHENGBIANMA\", \"FDUIYINGGONGCHENGMINGCHENG\", \"FHETONGQIANDINGRIQI\", \"FTUJIANZHIDINGFENBAOHANSHUI\", \"FJIDIANZHIDINGFENBAOHANSHUI\", \"FTUJIANZISHIJINEHANSHUI\", \"FJIDIANZISHIJINEHANSHUI\", \"FTUJIANZHIDINGFENBAOWUSHUI\", \"FJIDIANZHIDINGFENBAOWUSHUI\", \"FTUJIANZISHIJINEWUSHUI\", \"FJIDIANZISHIJINEWUSHUI\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FDUIYINGGONGCHENGBIANMA\", \"项目编码\"}, {\"FDUIYINGGONGCHENGMINGCHENG\", \"项目名称\"}, {\"FHETONGQIANDINGRIQI\", \"签订日期\"}, {\"FTUJIANZHIDINGFENBAOHANSHUI\", \"土建-指定-含税合同额\"}, {\"FJIDIANZHIDINGFENBAOHANSHUI\", \"机电-指定-含税合同额\"}, {\"FTUJIANZISHIJINEHANSHUI\", \"土建-自施-含税合同额\"}, {\"FJIDIANZISHIJINEHANSHUI\", \"机电-自施-含税合同额\"}, {\"FTUJIANZHIDINGFENBAOWUSHUI\", \"土建-指定-无税合同额\"}, {\"FJIDIANZHIDINGFENBAOWUSHUI\", \"机电-指定-无税合同额\"}, {\"FTUJIANZISHIJINEWUSHUI\", \"土建-自施-无税合同额\"}, {\"FJIDIANZISHIJINEWUSHUI\", \"机电-自施-无税合同额\"}}),",
                "    逆透视的列 = Table.UnpivotOtherColumns(重命名的列, {\"项目编码\", \"项目名称\", \"签订日期\"}, \"属性\", \"值\"),",
                "    按分隔符拆分列 = Table.SplitColumn(逆透视的列, \"属性\", Splitter.SplitTextByDelimiter(\"-\", QuoteStyle.Csv), {\"专业\", \"分包类型\", \"属性.3\"}),",
                "    已透视列 = Table.Pivot(按分隔符拆分列, List.Distinct(按分隔符拆分列[属性.3]), \"属性.3\", \"值\", List.Sum),",
                "    提取的日期 = Table.TransformColumns(已透视列,{{\"签订日期\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F_业主合同回款",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "分包类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca905f2d-fe36-416a-a34e-21b1fbdb4ca8",
            "sourceColumn": "分包类型",
            "summarizeBy": "none"
          },
          {
            "name": "合同编号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "313c211f-5e5c-4bc1-9599-e788efcadb48",
            "sourceColumn": "合同编号",
            "summarizeBy": "none"
          },
          {
            "name": "回款类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "018863c2-edfa-49e7-b213-9e8ef40a1ef2",
            "sourceColumn": "回款类型",
            "summarizeBy": "none"
          },
          {
            "name": "实际回款日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "67074147-34cf-48c7-8c48-189f738e2ca3",
            "sourceColumn": "实际回款日期",
            "summarizeBy": "none"
          },
          {
            "name": "施工专业",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea50db50-bc8d-47ef-b0a7-4726b529869a",
            "sourceColumn": "施工专业",
            "summarizeBy": "none"
          },
          {
            "name": "金额",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ac099c98-9d47-47ef-8a06-e4af64185f3d",
            "sourceColumn": "金额",
            "summarizeBy": "sum"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c040f3c-bb0a-4464-85c5-d0a7cb78fd05",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27ff9aa0-343d-4397-a55f-a6e8ff4af3d3",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5e3a949c-4254-4194-8dfb-c4bd00c37071",
        "partitions": [
          {
            "name": "F_业主合同回款-e8e2f0f8-e3ea-4545-878d-0ce1bf3f690c",
            "mode": "import",
            "queryGroup": "业主合同回款",
            "source": {
              "expression": [
                "let",
                "    源 = Table.Combine({业主合同回款初始化, 业主合同回款登记})",
                "in",
                "    源"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F_业主确认量",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "专业",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d42601c1-7c71-41d3-879b-f00dbd7d12c5",
            "sourceColumn": "专业",
            "summarizeBy": "none"
          },
          {
            "name": "分包类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "cebc022d-cfc9-4dd3-aed5-f3812f738a9c",
            "sourceColumn": "分包类型",
            "summarizeBy": "none"
          },
          {
            "name": "日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3f9e0a5f-da86-403d-85c7-176db310fa4d",
            "sourceColumn": "日期",
            "summarizeBy": "none"
          },
          {
            "name": "确认产值含税",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "550b207e-af9a-40a6-b406-5ce8e55ed291",
            "sourceColumn": "确认产值含税",
            "summarizeBy": "sum"
          },
          {
            "name": "确认产值无税",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "f0371492-4c2c-40c0-b989-cf9b93b1f8bb",
            "sourceColumn": "确认产值无税",
            "summarizeBy": "sum"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "08433801-7582-48b8-9bba-841620607a6f",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b179a66a-19d0-4430-912d-5fde2f820fe8",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "231dc6ac-a92d-4516-af8f-ee9b813b45cf",
        "partitions": [
          {
            "name": "F_业主确认量-4367c645-485e-43bd-b699-d3de05fd0446",
            "mode": "import",
            "queryGroup": "业主确认量",
            "source": {
              "expression": [
                "let",
                "    源 = Table.Combine({新业主确认量, 结转确认量})",
                "in",
                "    源"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F_全面预算",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "上缴公司预收益",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "831777f1-8514-47a1-abd4-2b36fa083552",
            "sourceColumn": "上缴公司预收益",
            "summarizeBy": "sum"
          },
          {
            "name": "业主确认量",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "eeff5bb8-2e93-4d9a-8dee-d924ca33aac9",
            "sourceColumn": "业主确认量",
            "summarizeBy": "sum"
          },
          {
            "name": "商务产值(不含税)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8e583e11-bcaf-4416-8a81-e0e9a66d1f89",
            "sourceColumn": "商务产值(不含税)",
            "summarizeBy": "sum"
          },
          {
            "name": "商务产值(含税)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "12641224-7841-4ed7-98de-26cb348f28a2",
            "sourceColumn": "商务产值(含税)",
            "summarizeBy": "sum"
          },
          {
            "name": "工程款流入(全口径)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed4711ea-6c72-40a8-b97b-c4d386ce1919",
            "sourceColumn": "工程款流入(全口径)",
            "summarizeBy": "sum"
          },
          {
            "name": "工程款流入(现金口径)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "27cfd44e-e610-48b3-8673-347951ab4d82",
            "sourceColumn": "工程款流入(现金口径)",
            "summarizeBy": "sum"
          },
          {
            "name": "年初是否填报预算",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4275fae8-1350-40e5-808d-d554dd7f8aad",
            "sourceColumn": "年初是否填报预算",
            "summarizeBy": "none"
          },
          {
            "name": "施工产值",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "81a2eb83-6060-4011-ad17-b977069c5cdf",
            "sourceColumn": "施工产值",
            "summarizeBy": "sum"
          },
          {
            "name": "日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "511418f3-91bc-4e4e-98dc-681ad0accda6",
            "sourceColumn": "日期",
            "summarizeBy": "none"
          },
          {
            "name": "现金流入",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "212cc694-a12d-4f2f-8526-a8f82f1e3d49",
            "sourceColumn": "现金流入",
            "summarizeBy": "sum"
          },
          {
            "name": "现金流出",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dca1e153-b8cc-42a4-841b-f40117a74494",
            "sourceColumn": "现金流出",
            "summarizeBy": "sum"
          },
          {
            "name": "营业收入",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cdc8b480-7cb2-46b6-a9bc-7bdf97565970",
            "sourceColumn": "营业收入",
            "summarizeBy": "none"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2520c0a9-ab5a-4c6b-a0ef-8123f42e60a1",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b9ea4bb-0891-43a4-929d-75e4f7de9e98",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "393bd77c-8614-46ca-b8be-c456743d9bbc",
        "partitions": [
          {
            "name": "F_全面预算-1b773be4-a93b-4c73-9b0a-99fb3c52346d",
            "mode": "import",
            "queryGroup": "预算\\全面预算",
            "source": {
              "expression": [
                "let",
                "    源 = Table.NestedJoin(项目年度预算表资金情况, {\"FZBID\"}, 项目年度预算主表, {\"FID\"}, \"项目年度预算主表\", JoinKind.Inner),",
                "    #\"展开的“项目年度预算主表”\" = Table.ExpandTableColumn(源, \"项目年度预算主表\", {\"项目名称\", \"项目编码\"}, {\"项目名称\", \"项目编码\"}),",
                "    删除的列 = Table.RemoveColumns(#\"展开的“项目年度预算主表”\",{\"FZBID\"}),",
                "    逆透视的其他列 = Table.UnpivotOtherColumns(删除的列, {\"项目名称\", \"项目编码\", \"科目\"}, \"月份\", \"值\"),",
                "    已透视列 = Table.Pivot(逆透视的其他列, List.Distinct(逆透视的其他列[科目]), \"科目\", \"值\", List.Sum),",
                "    替换的值1 = Table.ReplaceValue(已透视列,null,0,Replacer.ReplaceValue,{\"项目名称\", \"商务产值(含税)\", \"工程款流入(现金口径)\", \"工程款流入(全口径)\", \"上缴公司预收益\", \"施工产值\", \"业主确认量\"}),",
                "    计算营业收入 = Table.AddColumn(替换的值1, \"营业收入\", each [#\"商务产值(含税)\"] * 产值与营业收入换算系数),",
                "    计算日期 = Table.AddColumn(计算营业收入, \"日期\", each #date(#\"年度\",Number.From([月份]),1),type date),",
                "    删除的列1 = Table.RemoveColumns(计算日期,{\"月份\"}),",
                "    已添加自定义 = Table.AddColumn(删除的列1, \"年初是否填报预算\", each \"是\",type text)",
                "in",
                "    已添加自定义"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "F_商务产值收益",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7cdd436-372d-4792-a0e5-f08969050e9d",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "专业",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "8571681b-efa5-4d67-ba80-681b54ec002a",
            "sourceColumn": "专业",
            "summarizeBy": "none"
          },
          {
            "name": "分包类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c41943b4-dafb-44f9-841d-832842fe34e2",
            "sourceColumn": "分包类型",
            "summarizeBy": "none"
          },
          {
            "name": "含税合同额",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed8212db-a8ff-4ee8-b390-db0f97a27be6",
            "sourceColumn": "含税合同额",
            "summarizeBy": "sum"
          },
          {
            "name": "无税合同额",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "c61617fe-bcf4-49f9-aa36-fcd44ac6613d",
            "sourceColumn": "无税合同额",
            "summarizeBy": "sum"
          },
          {
            "name": "日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e6942de1-e50c-4f18-9e7e-347ebdc5c031",
            "sourceColumn": "日期",
            "summarizeBy": "none"
          },
          {
            "name": "本年产值含税",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "ff78dd35-2da6-4ebc-bca9-8805d050cb30",
            "sourceColumn": "本年产值含税",
            "summarizeBy": "sum"
          },
          {
            "name": "本年产值无税",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "472d0518-f021-4a2c-a272-e98d02548689",
            "sourceColumn": "本年产值无税",
            "summarizeBy": "sum"
          },
          {
            "name": "本年完工进度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "2828f073-300b-412e-a9be-d262fe2aae4b",
            "sourceColumn": "本年完工进度",
            "summarizeBy": "sum"
          },
          {
            "name": "本年成本",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "2dd755cd-7dfd-47e2-9394-9417b717d2c5",
            "sourceColumn": "本年成本",
            "summarizeBy": "sum"
          },
          {
            "name": "本年成本降低",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "a33621f8-42b1-4333-965d-d048e286444f",
            "sourceColumn": "本年成本降低",
            "summarizeBy": "sum"
          },
          {
            "name": "本年收益",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "a313fbb7-537f-400c-9355-5f51747f0a7f",
            "sourceColumn": "本年收益",
            "summarizeBy": "sum"
          },
          {
            "name": "核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0f29fde8-b260-40cc-9976-e0682179d3a6",
            "sourceColumn": "核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "累计产值含税",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "224c113b-5ca5-4e9f-b807-8bd874dc03ab",
            "sourceColumn": "累计产值含税",
            "summarizeBy": "sum"
          },
          {
            "name": "累计产值无税",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "55de94c1-df2e-416d-a320-85db7c776378",
            "sourceColumn": "累计产值无税",
            "summarizeBy": "sum"
          },
          {
            "name": "累计完工进度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "1fb5bee6-086a-4d3a-815c-605ea58bf593",
            "sourceColumn": "累计完工进度",
            "summarizeBy": "sum"
          },
          {
            "name": "累计成本",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "70a57bc5-70cf-433f-b8f6-8ea455881604",
            "sourceColumn": "累计成本",
            "summarizeBy": "sum"
          },
          {
            "name": "累计成本降低",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "a02e35c0-98a1-4f14-9efd-f731ab73fd07",
            "sourceColumn": "累计成本降低",
            "summarizeBy": "sum"
          },
          {
            "name": "累计收益",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "3ae341b9-147e-4670-b0a6-beb378adfe9b",
            "sourceColumn": "累计收益",
            "summarizeBy": "sum"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b5ffdc2-e713-4fcf-bbcc-40b6bd721302",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9c4b71e-81d0-4379-8ceb-ad3896b4317b",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          },
          {
            "name": "预计总成本",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "lineageTag": "bc139022-2a78-46fc-bb5a-f8470f3226bc",
            "sourceColumn": "预计总成本",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4037ebbb-33fc-46e5-a47f-1979d25f5945",
        "partitions": [
          {
            "name": "F_商务产值收益-2b9c570a-d3ed-467e-beb6-c767b16f5874",
            "mode": "import",
            "queryGroup": "产值收益",
            "source": {
              "expression": [
                "let",
                "    源 = Folder.Files(产值文件路径),",
                "    筛选的行 = Table.SelectRows(源, each ([Extension] = \".xlsx\")),",
                "    筛选的隐藏文件1 = Table.SelectRows(筛选的行, each [Attributes]?[Hidden]? <> true),",
                "    删除的其他列 = Table.SelectColumns(筛选的隐藏文件1,{\"Name\", \"Content\"}),",
                "    已添加自定义 = Table.AddColumn(删除的其他列, \"自定义\", each Excel.Workbook([Content]){[Item=\"商务产值\",Kind=\"Table\"]}[Data]),",
                "    删除的列 = Table.RemoveColumns(已添加自定义,{\"Content\"}),",
                "    #\"展开的“自定义”\" = Table.ExpandTableColumn(删除的列, \"自定义\", {\"项目名称\", \"项目编码\", \"分包类型\", \"专业\", \"无税合同额\", \"含税合同额\", \"核定收益率\", \"预计总成本\", \"本年成本\", \"累计成本\", \"本年完工进度\", \"累计完工进度\", \"本年产值无税\", \"本年产值含税\", \"累计产值无税\", \"累计产值含税\", \"本年收益\", \"累计收益\", \"日期\", \"累计成本降低\", \"本年成本降低\"}, {\"项目名称\", \"项目编码\", \"分包类型\", \"专业\", \"无税合同额\", \"含税合同额\", \"核定收益率\", \"预计总成本\", \"本年成本\", \"累计成本\", \"本年完工进度\", \"累计完工进度\", \"本年产值无税\", \"本年产值含税\", \"累计产值无税\", \"累计产值含税\", \"本年收益\", \"累计收益\", \"日期\", \"累计成本降低\", \"本年成本降低\"}),",
                "    更改的类型 = Table.TransformColumnTypes(#\"展开的“自定义”\",{{\"项目名称\", type text}, {\"项目编码\", type text}, {\"分包类型\", type text}, {\"专业\", type text}, {\"无税合同额\", type number}, {\"含税合同额\", type number}, {\"核定收益率\", Int64.Type}, {\"预计总成本\", type number}, {\"本年成本\", type number}, {\"累计成本\", type number}, {\"本年完工进度\", type number}, {\"累计完工进度\", type number}, {\"本年产值无税\", type number}, {\"本年产值含税\", type number}, {\"累计产值无税\", type number}, {\"累计产值含税\", type number}, {\"本年收益\", type number}, {\"累计收益\", type number}, {\"日期\", type date}, {\"累计成本降低\", type number}, {\"本年成本降低\", type number}}),",
                "    去除的文本 = Table.TransformColumns(更改的类型,{{\"项目编码\", Text.Trim, type text}}),",
                "    清除的文本 = Table.TransformColumns(去除的文本,{{\"项目编码\", Text.Clean, type text}})",
                "in",
                "    清除的文本"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "M_度量值",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "列 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "586ece71-c985-41d4-a82e-ebfa61fc47ad",
            "sourceColumn": "列 1",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "e8b06568-42b2-425d-9451-778b12eda1fc",
        "measures": [
          {
            "name": "【开累产值无税】",
            "displayFolder": "实现\\产值",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期],SUM('F_商务产值收益'[累计产值无税])/SELECTEDVALUE('D-单位'[系数],1))",
            "formatString": "#,0.00",
            "lineageTag": "66c17e85-4649-474e-81ae-bba8c588f79a"
          },
          {
            "name": "【本年产值无税】",
            "displayFolder": "实现\\产值",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期], SUM('F_商务产值收益'[本年产值无税])/SELECTEDVALUE('D-单位'[系数],1))",
            "formatString": "#,0.00",
            "lineageTag": "a068e69b-8705-4e53-bc63-78e232a332e0"
          },
          {
            "name": "【开累核定收益】",
            "displayFolder": "实现\\收益",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期],SUM('F_商务产值收益'[累计收益])/SELECTEDVALUE('D-单位'[系数],1))",
            "formatString": "#,0.00",
            "lineageTag": "b751411c-c7c7-4a6f-81b4-419b6973d8c8"
          },
          {
            "name": "【本年核定收益】",
            "displayFolder": "实现\\收益",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期],SUM('F_商务产值收益'[本年收益])/SELECTEDVALUE('D-单位'[系数],1))",
            "formatString": "#,0.00",
            "lineageTag": "ab71919b-8b14-4dfb-a680-6e500d77d180"
          },
          {
            "name": "【目标收益】",
            "displayFolder": "目标\\产值",
            "expression": "CALCULATE(SUM('F_全面预算'[上缴公司预收益])/SELECTEDVALUE('D-单位'[系数],1),DATESYTD('D-日历'[日期]))",
            "formatString": "#,0.00",
            "lineageTag": "f25b9762-6e35-42ab-a552-ea9abbb5b0e8"
          },
          {
            "name": "【目标产值】",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "目标\\产值",
            "expression": "CALCULATE(SUM('F_全面预算'[商务产值(不含税)])/SELECTEDVALUE('D-单位'[系数],1),DATESYTD('D-日历'[日期]))",
            "formatString": "#,0.00",
            "lineageTag": "b6d144fd-a39d-4d93-a145-8902926c20b1"
          },
          {
            "name": "【成本降低额】",
            "displayFolder": "实现\\收益",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期],SUM('F_商务产值收益'[本年成本降低])/SELECTEDVALUE('D-单位'[系数],1))",
            "formatString": "#,0.00",
            "lineageTag": "b0faa60d-66f6-4905-9c32-f44ca050fa63"
          },
          {
            "name": "【本年产值进度】",
            "displayFolder": "实现\\产值",
            "expression": "DIVIDE([【本年产值无税】],[【年度目标产值】])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a4550bdd-7e05-4eac-815d-53456647ab98"
          },
          {
            "name": "【本年总收益】",
            "displayFolder": "实现\\收益",
            "expression": "[【本年核定收益】]+[【成本降低额】]",
            "formatString": "#,0.00",
            "lineageTag": "87d11da1-6039-4e8b-adf4-4e361beced15"
          },
          {
            "name": "【本年收益完成进度】",
            "displayFolder": "实现\\收益",
            "expression": "DIVIDE([【本年总收益】],[【目标收益】])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "890c459c-61ad-41e6-8863-ef10ea6bb0cc"
          },
          {
            "name": "【平均实现收益率】",
            "displayFolder": "实现\\产值",
            "expression": "DIVIDE([【本年总收益】],CALCULATE([【本年产值含税】],'D-分包类型'[分包类型]=\"自施\"))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "86615e7e-7ff4-465d-af45-e92170ce7bf9"
          },
          {
            "name": "【本年收益完成进度（不含降低）】",
            "displayFolder": "实现\\收益",
            "expression": "DIVIDE([【本年核定收益】],[【目标收益】])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c5543abc-b9c7-4abd-905c-bb9ed3cd06be"
          },
          {
            "name": "【本年产值含税】",
            "displayFolder": "实现\\产值",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期],SUM('F_商务产值收益'[本年产值含税])/SELECTEDVALUE('D-单位'[系数],1))",
            "formatString": "#,0.00",
            "lineageTag": "e3711217-1de4-4675-a003-b8d1933dca58"
          },
          {
            "name": "【累计成本降低额】",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "实现\\收益",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期],SUM('F_商务产值收益'[累计成本降低])/SELECTEDVALUE('D-单位'[系数],1))",
            "lineageTag": "876d02c4-aed2-4655-a50e-eabb36eab6f2"
          },
          {
            "name": "【本年确权含税】",
            "displayFolder": "实现\\确权",
            "expression": "CALCULATE(SUM('F_业主确认量'[确认产值含税]),DATESYTD('D-日历'[日期]))/SELECTEDVALUE('D-单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "eb6ff7e0-7aa3-4a30-b867-4b481a6fd787"
          },
          {
            "name": "【本年确权无税】",
            "displayFolder": "实现\\确权",
            "expression": "CALCULATE(SUM('F_业主确认量'[确认产值无税]),DATESYTD('D-日历'[日期]))/SELECTEDVALUE('D-单位'[系数],1)",
            "formatString": "0.00",
            "lineageTag": "5ef616af-226b-43c1-a061-f5ae08e0ae2d"
          },
          {
            "name": "【本年结算率】",
            "displayFolder": "实现\\确权",
            "expression": "DIVIDE([【本年确权无税】],[【本年产值无税】])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "086b3386-3cdb-432f-82d6-ece19f5915c8"
          },
          {
            "name": "【开累确权含税】",
            "displayFolder": "实现\\确权",
            "expression": "var MD=MAX('D-日历'[日期]) return CALCULATE(SUM('F_业主确认量'[确认产值含税]),'D-日历'[日期]<=md)/SELECTEDVALUE('D-单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "39f284b0-1bac-499b-8393-4d61aa5dac73"
          },
          {
            "name": "【开累确权无税】",
            "displayFolder": "实现\\确权",
            "expression": "var MD=MAX('D-日历'[日期]) return CALCULATE(SUM('F_业主确认量'[确认产值无税]),'D-日历'[日期]<=md)/SELECTEDVALUE('D-单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "f254e9ec-8d72-467b-b33d-7d63aa091184"
          },
          {
            "name": "【开累结算率】",
            "displayFolder": "实现\\确权",
            "expression": "DIVIDE([【开累确权无税】],[【开累产值无税】])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cde2be79-19f7-4410-8a50-a3c061c944c8"
          },
          {
            "name": "【开累产值含税】",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "实现\\产值",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期],SUM('F_商务产值收益'[累计产值含税])/SELECTEDVALUE('D-单位'[系数],1))",
            "lineageTag": "fa0d5379-955a-4625-b5d8-d7b3bc14ada9"
          },
          {
            "name": "度量值",
            "expression": "month(MAX('F_商务产值收益'[日期]))",
            "formatString": "0",
            "lineageTag": "2cc0e348-e687-4043-84f3-0299115c9015"
          },
          {
            "name": "【本年回收工程款】",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "实现\\收款",
            "expression": "CALCULATE(SUM('F_业主合同回款'[金额]),DATESYTD('D-日历'[日期]))/SELECTEDVALUE('D-单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "6c16911f-7b52-41b5-96a3-011c5d2738c8"
          },
          {
            "name": "【开累回收工程款】",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "实现\\收款",
            "expression": "var MD=MAX('D-日历'[日期]) return CALCULATE(SUM('F_业主合同回款'[金额]),'D-日历'[日期]<=MD)/SELECTEDVALUE('D-单位'[系数],1)",
            "lineageTag": "d0b728a8-5f39-42dd-84d9-eecfd4e600fd"
          },
          {
            "name": "【本年确权目标】",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "目标\\确权",
            "expression": "CALCULATE(SUM('其它预算'[业主确认量]),DATESYTD('维度-日历'[日期]))/SELECTEDVALUE('单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "38b366a8-750b-4ec2-80d9-02f122c5ad7d"
          },
          {
            "name": "【本年工程款收款目标】",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "目标\\收款",
            "expression": "CALCULATE(SUM('其它预算'[工程款流入(现金口径)]),DATESYTD('维度-日历'[日期]))/SELECTEDVALUE('单位'[系数],1)",
            "lineageTag": "d1eaa53a-f2ef-40d0-89b0-e65dc678a4de"
          },
          {
            "name": "【本年确权进度】",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "实现\\确权",
            "expression": "DIVIDE([【本年确权无税】],[【本年确权目标】])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a072a91d-45df-4bb0-b384-eb405988d755"
          },
          {
            "name": "【本年回收工程款进度】",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "实现\\收款",
            "expression": "DIVIDE([【本年回收工程款】],[【本年工程款收款目标】])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f3dc1459-052f-4f40-ab16-3467e94e2880"
          },
          {
            "name": "M_业主合同额_含税",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "实现\\产值",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期], SUM('F_商务产值收益'[含税合同额])/SELECTEDVALUE('D-单位'[系数],1))",
            "formatString": "#,0.00",
            "lineageTag": "29ca8a25-b12d-4c0d-bdd6-05cc635dbb88"
          },
          {
            "name": "M_业主合同额_无税",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "实现\\产值",
            "expression": "LASTNONBLANKVALUE('D-日历'[日期], SUM('F_商务产值收益'[无税合同额])/SELECTEDVALUE('D-单位'[系数],1))",
            "formatString": "#,0.00",
            "lineageTag": "6dbeb4e1-9d19-41ef-81ed-eda59daa0778"
          },
          {
            "name": "【年度目标产值】",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "目标\\产值",
            "expression": "CALCULATE(SUM('F_全面预算'[商务产值(不含税)]),REMOVEFILTERS('D-日历'))/SELECTEDVALUE('D-单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "9f40e4ba-03b2-49ee-be58-bc799dc52864"
          },
          {
            "name": "【年度目标收益】",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "目标\\产值",
            "expression": "CALCULATE(SUM('F_全面预算'[上缴公司预收益])/SELECTEDVALUE('D-单位'[系数],1),REMOVEFILTERS('D-日历'))",
            "formatString": "#,0.00",
            "lineageTag": "b9424077-7ee9-4cad-bc09-324300dcb221"
          },
          {
            "name": "【刷新时间】",
            "expression": "\"刷新时间：\" & MAX('刷新时间'[刷新时间])",
            "lineageTag": "f516f56a-eafb-4eae-8b4c-82727dced8cc"
          }
        ],
        "partitions": [
          {
            "name": "M_度量值-76844576-8c53-4f04-be2e-dcb8f5762857",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"列 1\" = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"列 1\", type text}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "分公司总经",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "姓名",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "de7f90a8-34d8-47c6-9a71-88fba88136df",
            "sourceColumn": "姓名",
            "summarizeBy": "none"
          },
          {
            "name": "帐号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "0672ae23-3ee9-4f9a-a9bd-a69c6d6cbcf6",
            "sourceColumn": "帐号",
            "summarizeBy": "none"
          },
          {
            "name": "责任体",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "079eefa4-a188-4098-908f-d50c41eff03f",
            "sourceColumn": "责任体",
            "summarizeBy": "none"
          }
        ],
        "description": "用于数据行权限",
        "isHidden": true,
        "lineageTag": "f7acc130-4721-4be7-b7eb-02712d940e77",
        "partitions": [
          {
            "name": "分公司总经-6cab2441-914f-48e2-b5fe-476337570dc6",
            "mode": "import",
            "queryGroup": "维度",
            "source": {
              "expression": [
                "let",
                "    源 = Excel.Workbook(File.Contents(\"\\\\172.16.8.66\\经营分析\\经营分析会\\分公司总经.xlsx\"), null, true),",
                "    分公司总经_Table = 源{[Item=\"分公司总经\",Kind=\"Table\"]}[Data],",
                "    更改的类型 = Table.TransformColumnTypes(分公司总经_Table,{{\"帐号\", type text}, {\"姓名\", type text}, {\"责任体\", type text}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "刷新时间",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "刷新时间",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd h:nn:ss",
            "isHidden": true,
            "lineageTag": "2b4a7d60-a866-419f-b5eb-81b53363820a",
            "sourceColumn": "刷新时间",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "d6454d45-a6ed-4cef-b4a4-bb361ed7e44f",
        "partitions": [
          {
            "name": "刷新时间-cc6862ca-b83d-49e9-98e4-583edf65f8eb",
            "mode": "import",
            "queryGroup": "参数组",
            "source": {
              "expression": [
                "let",
                "    源 = DateTime.LocalNow()",
                "in",
                "    源"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}