{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "name": "模型",
    "culture": "zh-CN",
    "dataSources": [
      {
        "type": "structured",
        "name": "Oracle/172 16 8 78/oracledb",
        "connectionDetails": {
          "protocol": "oracle",
          "address": {
            "server": "172.16.8.78/oracledb"
          },
          "authentication": null,
          "query": null
        },
        "options": {
          "hierarchicalNavigation": true
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "gspm"
        }
      }
    ],
    "tables": [
      {
        "name": "累计签约额列",
        "columns": [
          {
            "name": "FXIANGMUBIANMA",
            "dataType": "string",
            "sourceColumn": "FXIANGMUBIANMA"
          },
          {
            "name": "FBIAOZHUNHETONGCODE",
            "dataType": "string",
            "sourceColumn": "FBIAOZHUNHETONGCODE"
          },
          {
            "name": "FSHANGWUKEMUID",
            "dataType": "string",
            "sourceColumn": "FSHANGWUKEMUID"
          },
          {
            "name": "FLJQYEHZT",
            "dataType": "double",
            "sourceColumn": "FLJQYEHZT"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Table.Combine({#\"生成BZKB-105累计签约额\", #\"集采进场出库-项目BZKB-101\", #\"分包合同-单项和指定已结\", #\"分包合同-单项和指定未结1\", #\"分包合同-单项和指定未结2\", #\"分包合同-单项和指定未结3\", #\"分包合同-单项和指定未结4\", #\"分包集采合同-项目已结\", #\"分包集采合同-项目未结1\", #\"分包集采合同-项目未结2\", #\"物资合同-单项和指定已结\", #\"物资合同-单项和指定未结1\", #\"物资合同-单项和指定未结2\", #\"物资合同-单项和指定未结3\", #\"物资合同-单项和指定未结4\", #\"物资集采合同-项目已结\", #\"物资集采合同-项目未结1\", #\"物资集采合同-项目未结2\"}),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"fLJQYEHZT\", type number}}),",
                "    替换的值 = Table.ReplaceValue(更改的类型,null,0,Replacer.ReplaceValue,{\"fLJQYEHZT\"}),",
                "    分组的行 = Table.Group(替换的值, {\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}, {{\"FLJQYEHZT\", each List.Sum([fLJQYEHZT]), type nullable number}})",
                "in",
                "    分组的行"
              ]
            }
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "GSPM_GUDINGZICHANZLCB",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_GUDINGZICHANZLCB1 = GSPM{[Name=\"GSPM_GUDINGZICHANZLCB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_GUDINGZICHANZLCB1, each [FGSGDZCZLF] > 0),",
          "    已添加自定义 = Table.AddColumn(筛选的行, \"FBIAOZHUNHETONGCODE\", each \"BZKB-105\")",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "生成BZKB-105累计签约额",
        "kind": "m",
        "expression": [
          "let",
          "    源 = GSPM_GUDINGZICHANZLCB,",
          "    合并的查询 = Table.NestedJoin(源, {\"FZBID\"}, GSPM_DAIQIANHETONGJIEZHUANZB, {\"FID\"}, \"GSPM_DAIQIANHETONGJIEZHUANZB\", JoinKind.LeftOuter),",
          "    #\"展开的“GSPM_DAIQIANHETONGJIEZHUANZB”\" = Table.ExpandTableColumn(合并的查询, \"GSPM_DAIQIANHETONGJIEZHUANZB\", {\"FXIANGMUBIANMA\"}, {\"FXIANGMUBIANMA\"}),",
          "    删除的其他列 = Table.SelectColumns(#\"展开的“GSPM_DAIQIANHETONGJIEZHUANZB”\",{\"FSHANGWUKEMUID\", \"FGSGDZCZLF\", \"FBIAOZHUNHETONGCODE\", \"FXIANGMUBIANMA\"}),",
          "    已添加自定义 = Table.AddColumn(删除的其他列, \"FSJLY\", each \"已签合同结转\"),",
          "    合并的查询1 = Table.NestedJoin(已添加自定义, {\"FBIAOZHUNHETONGCODE\"}, 标准合同库, {\"FBIAOZHUNHETONGBH\"}, \"标准合同库\", JoinKind.LeftOuter),",
          "    #\"展开的“标准合同库”\" = Table.ExpandTableColumn(合并的查询1, \"标准合同库\", {\"FBIAOZHUNHETONGMC\", \"FHTFLFW\"}, {\"FBIAOZHUNHETONGMC\", \"FHTFLFW\"}),",
          "    重命名的列 = Table.RenameColumns(#\"展开的“标准合同库”\",{{\"FHTFLFW\", \"FHETONGLEIXING\"}, {\"FBIAOZHUNHETONGMC\", \"FBIAOZHUNHETONG\"}, {\"FGSGDZCZLF\", \"fLJQYEHZT\"}}),",
          "    已添加自定义1 = Table.AddColumn(重命名的列, \"自定义\", each 4),",
          "    合并的查询2 = Table.NestedJoin(已添加自定义1, {\"FSHANGWUKEMUID\"}, 商务科目表, {\"FID\"}, \"商务科目表\", JoinKind.LeftOuter),",
          "    #\"展开的“商务科目表”\" = Table.ExpandTableColumn(合并的查询2, \"商务科目表\", {\"FFULLNAME\"}, {\"FFULLNAME\"}),",
          "    重命名的列1 = Table.RenameColumns(#\"展开的“商务科目表”\",{{\"FFULLNAME\", \"FSHANGWUKEMUFNAME\"}}),",
          "    删除的其他列1 = Table.SelectColumns(重命名的列1,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "GSPM_DAIQIANHETONGJIEZHUANZB",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_DAIQIANHETONGJIEZHUANZB1 = GSPM{[Name=\"GSPM_DAIQIANHETONGJIEZHUANZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_DAIQIANHETONGJIEZHUANZB1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    排序的行 = Table.Sort(筛选的行,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\"})",
          "in",
          "    删除的副本"
        ]
      },
      {
        "name": "标准合同库",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_BIAOZHUNHETONG1 = GSPM{[Name=\"GSPM_BIAOZHUNHETONG2020\"]}[Data]",
          "in",
          "    GSPM_BIAOZHUNHETONG1"
        ]
      },
      {
        "name": "商务科目表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    MD = 源{[Schema=\"MD\"]}[Data],",
          "    MD_SHANGWUKEMU1 = MD{[Name=\"MD_SHANGWUKEMU2020\"]}[Data]",
          "in",
          "    MD_SHANGWUKEMU1"
        ]
      },
      {
        "name": "集采进场出库-项目BZKB-101",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIJINCHANG_ZB1 = GSPM{[Name=\"GSPM_WUZIJINCHANG_ZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIJINCHANG_ZB1, each [FBIAOZHUNHETONGCODE] = \"BZKB-101\"),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each ([FDANJUZHUANGTAI] = \"已完成\") and ([FYEWUXIAOLEI] = \"统一进场\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行1,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FHANSHUIJINCHANGJINE\", \"FBUHANSHUIJINCHANGJINE\", \"FZENGZHISHUISHUILV\", \"FLJTCHS\", \"FBIAOZHUNHETONGCODE\"}),",
          "    合并的查询 = Table.NestedJoin(删除的其他列, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    替换的值 = Table.ReplaceValue(#\"展开的“MD_XIANGMUXINXI”\",null,0,Replacer.ReplaceValue,{\"FLJTCHS\"}),",
          "    已添加条件列 = Table.AddColumn(替换的值, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then ([FHANSHUIJINCHANGJINE]-[FLJTCHS])/(1+[FZENGZHISHUISHUILV]) else if [FJISHUIFANGSHI] = \"简易计税\" then [FHANSHUIJINCHANGJINE]-[FLJTCHS] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "MD_XIANGMUXINXI",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    MD = 源{[Schema=\"MD\"]}[Data],",
          "    MD_XIANGMUXINXI1 = MD{[Name=\"MD_XIANGMUXINXI\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(MD_XIANGMUXINXI1,{\"FXMBIANMA\", \"FXMQUANCHENG\", \"FXMXINGZHI\", \"FJISHUIFANGSHI\", \"FJNWFB\", \"FJIANZHUMJ\", \"FTUJIANHEDINGSYLJZ\", \"FJIDIANHEDINGSYLJZ\", \"FTBGLBM\", \"FGFYTHLRZXBM\", \"FLC\", \"FSFSXWZEQ\", \"FTUJIANHEDINGSYL\", \"FJIDIANHEDINGSYL\", \"FZONGHEHEDINGSYL\", \"FJDHLXTJ\"})",
          "in",
          "    删除的其他列"
        ]
      },
      {
        "name": "分包合同-单项和指定已结",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOHETONGJIESUAN1 = GSPM{[Name=\"GSPM_FENBAOHETONGJIESUAN\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FENBAOHETONGJIESUAN1, each ([FBIAOZHUNHETONGCODE] <> null) and ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHETONGJIAKUANHANSHUI\", \"FHETONGJIAKUANBUHANSHUI\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FPINGSHENZHUANGTAI\", \"SCREATETIME\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FJIESUANLEIXING\"}),",
          "    排序的行 = Table.Sort(删除的其他列,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"FHETONGBIANHAO\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\"}),",
          "    合并的查询 = Table.NestedJoin(删除的副本, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    合并的查询1 = Table.NestedJoin(#\"展开的“MD_XIANGMUXINXI”\", {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}, #\"分包合同-单项和指定\", {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\"}, \"分包合同-单项和指定\", JoinKind.LeftOuter),",
          "    #\"展开的“分包合同-单项和指定”\" = Table.ExpandTableColumn(合并的查询1, \"分包合同-单项和指定\", {\"FJIESUANZHUANGTAI\"}, {\"FJIESUANZHUANGTAI\"}),",
          "    合并的列 = Table.CombineColumns(#\"展开的“分包合同-单项和指定”\",{\"FJIESUANZHUANGTAI\", \"FJISHUIFANGSHI\"},Combiner.CombineTextByDelimiter(\"**\", QuoteStyle.None),\"已合并\"),",
          "    已添加条件列 = Table.AddColumn(合并的列, \"fLJQYEHZT\", each if [已合并] = \"已结算**一般计税\" then [FJIESUANJIABHS] else if [已合并] = \"已结算**简易计税\" then [FJIESUANJIAHS] else null),",
          "    筛选的行1 = Table.SelectRows(已添加条件列, each ([fLJQYEHZT] <> null)),",
          "    删除的其他列1 = Table.SelectColumns(筛选的行1,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "分包合同-单项和指定",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_HETONGXINXI1 = GSPM{[Name=\"GSPM_HETONGXINXI\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_HETONGXINXI1,{\"FHETONGBIANHAO\", \"FHETONGXIEYIHAO\", \"FXIANGMUBIANMA\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\", \"FZENGZHISHUISHUILV\", \"FSHIFOUZANGUHETONG\", \"FBUHANSHUIHETONGZONGJIA\", \"FHANSHUIHETONGZONGJIA\", \"FJIESUANZHUANGTAI\", \"FHSJIESUANJINE\", \"FYEWULEIBIE\", \"FSFTCTF\", \"FSFJRXM\", \"FJCQY\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSFJRXM] = \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each [FYEWULEIBIE] = \"项目组织分包合同评审\" or [FYEWULEIBIE] = \"指定分包合同评审\")",
          "in",
          "    筛选的行2"
        ]
      },
      {
        "name": "分包合同-单项和指定未结1",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOHETONGJIESUAN1 = GSPM{[Name=\"GSPM_FENBAOHETONGJIESUAN\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_FENBAOHETONGJIESUAN1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHETONGJIAKUANHANSHUI\", \"FHETONGJIAKUANBUHANSHUI\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FPINGSHENZHUANGTAI\", \"SCREATETIME\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FJIESUANLEIXING\"}),",
          "    排序的行 = Table.Sort(删除的其他列,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"FHETONGBIANHAO\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\"}),",
          "    筛选的行 = Table.SelectRows(删除的副本, each ([FBIAOZHUNHETONGCODE] <> null) and ([FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\")),",
          "    合并的查询1 = Table.NestedJoin(筛选的行, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}, #\"分包合同-单项和指定\", {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\"}, \"分包合同-单项和指定\", JoinKind.RightOuter),",
          "    筛选的行1 = Table.SelectRows(合并的查询1, each ([SCREATETIME] = null)),",
          "    删除的列 = Table.RemoveColumns(筛选的行1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHETONGJIAKUANHANSHUI\", \"FHETONGJIAKUANBUHANSHUI\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FPINGSHENZHUANGTAI\", \"SCREATETIME\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FJIESUANLEIXING\", \"索引\"}),",
          "    #\"展开的“分包合同-单项和指定”\" = Table.ExpandTableColumn(删除的列, \"分包合同-单项和指定\", {\"FHETONGBIANHAO\", \"FHETONGXIEYIHAO\", \"FXIANGMUBIANMA\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\", \"FZENGZHISHUISHUILV\", \"FSHIFOUZANGUHETONG\", \"FBUHANSHUIHETONGZONGJIA\", \"FHANSHUIHETONGZONGJIA\", \"FJIESUANZHUANGTAI\", \"FHSJIESUANJINE\", \"FYEWULEIBIE\", \"FSFTCTF\", \"FSFJRXM\", \"FJCQY\"}, {\"FHETONGBIANHAO\", \"FHETONGXIEYIHAO\", \"FXIANGMUBIANMA\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\", \"FZENGZHISHUISHUILV\", \"FSHIFOUZANGUHETONG\", \"FBUHANSHUIHETONGZONGJIA\", \"FHANSHUIHETONGZONGJIA\", \"FJIESUANZHUANGTAI\", \"FHSJIESUANJINE\", \"FYEWULEIBIE\", \"FSFTCTF\", \"FSFJRXM\", \"FJCQY\"}),",
          "    合并的查询 = Table.NestedJoin(#\"展开的“分包合同-单项和指定”\", {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    筛选的行2 = Table.SelectRows(#\"展开的“MD_XIANGMUXINXI”\", each ([FDAIQIANHETONGBIANMA] <> null)),",
          "    已添加条件列 = Table.AddColumn(筛选的行2, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [FBUHANSHUIHETONGZONGJIA] else if [FJISHUIFANGSHI] = \"简易计税\" then [FHANSHUIHETONGZONGJIA] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列1,{{\"FDAIQIANHETONGBIANMA\", \"FBIAOZHUNHETONGCODE\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "分包初始合同评审",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_HETONGPINGSHEN1 = GSPM{[Name=\"GSPM_HETONGPINGSHEN\"]}[Data]",
          "in",
          "    GSPM_HETONGPINGSHEN1"
        ]
      },
      {
        "name": "分包合同-单项和指定未结2",
        "kind": "m",
        "expression": [
          "let",
          "    源 = 分包初始合同评审,",
          "    筛选的行 = Table.SelectRows(源, each ([FSFJRXM] = \"是\") and ([FSHIFOUZANGUHETONG] <> \"是\") and ([FDAIQIANHETONGBIANMA] <> null)),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\", \"FBUHANSHUIHETONGZONGJIA\", \"FHANSHUIHETONGZONGJIA\", \"FPINGSHENZHUANGTAI\"}),",
          "    筛选的行1 = Table.SelectRows(删除的其他列, each ([FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\")),",
          "    合并的查询 = Table.NestedJoin(筛选的行1, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    筛选的行2 = Table.SelectRows(#\"展开的“MD_XIANGMUXINXI”\", each ([FJISHUIFANGSHI] <> null)),",
          "    已添加条件列 = Table.AddColumn(筛选的行2, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [FBUHANSHUIHETONGZONGJIA] else if [FJISHUIFANGSHI] = \"简易计税\" then [FHANSHUIHETONGZONGJIA] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列1,{{\"FDAIQIANHETONGBIANMA\", \"FBIAOZHUNHETONGCODE\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "分包合同-单项和指定未结3",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOBUCHONGPINGSHEN1 = GSPM{[Name=\"GSPM_FENBAOBUCHONGPINGSHEN\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FENBAOBUCHONGPINGSHEN1, each ([FYEWULEIBIE] <> \"集采分包补充合同评审\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FBUCHONGXIEYIHAO\", \"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHIFOUZANGUHETONG\", \"FHANSHUIHETONGZONGJIA\", \"FBUHANSHUIHETONGZONGJIA\", \"FPINGSHENZHUANGTAI\", \"FYEWULEIBIE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FSFJZDXM\", \"FSFJRXM\", \"FJCQY\"}),",
          "    筛选的行1 = Table.SelectRows(删除的其他列, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行3 = Table.SelectRows(筛选的行1, each ([FSFJRXM] = \"是\") and ([FPINGSHENZHUANGTAI] <> \"已完成\")),",
          "    合并的查询 = Table.NestedJoin(筛选的行3, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    筛选的行2 = Table.SelectRows(#\"展开的“MD_XIANGMUXINXI”\", each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    已添加条件列 = Table.AddColumn(筛选的行2, \"自定义\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and[FHANSHUIHETONGZONGJIA]<0 ",
          "then 0 else [FHANSHUIHETONGZONGJIA]),",
          "    已添加条件列1 = Table.AddColumn(已添加条件列, \"自定义.1\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and [FHANSHUIHETONGZONGJIA] < 0  then 0 else [FBUHANSHUIHETONGZONGJIA]),",
          "    已添加条件列2 = Table.AddColumn(已添加条件列1, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [自定义.1] else if [FJISHUIFANGSHI] = \"简易计税\" then [自定义] else null),",
          "    删除的列 = Table.RemoveColumns(已添加条件列2,{\"自定义\", \"自定义.1\"}),",
          "    删除的其他列1 = Table.SelectColumns(删除的列,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "分包合同-单项和指定未结4",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOHETONGJIESUAN1 = GSPM{[Name=\"GSPM_FENBAOHETONGJIESUAN\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_FENBAOHETONGJIESUAN1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHETONGJIAKUANHANSHUI\", \"FHETONGJIAKUANBUHANSHUI\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FPINGSHENZHUANGTAI\", \"SCREATETIME\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FJIESUANLEIXING\"}),",
          "    排序的行 = Table.Sort(删除的其他列,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"FHETONGBIANHAO\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\"}),",
          "    筛选的行 = Table.SelectRows(删除的副本, each ([FBIAOZHUNHETONGCODE] <> null) and ([FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\")),",
          "    合并的查询1 = Table.NestedJoin(筛选的行, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}, #\"分包合同-单项和指定\", {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\"}, \"分包合同-单项和指定\", JoinKind.RightOuter),",
          "    筛选的行1 = Table.SelectRows(合并的查询1, each [SCREATETIME] <> null),",
          "    #\"展开的“分包合同-单项和指定”\" = Table.ExpandTableColumn(筛选的行1, \"分包合同-单项和指定\", {\"FJIESUANZHUANGTAI\"}, {\"FJIESUANZHUANGTAI\"}),",
          "    合并的查询 = Table.NestedJoin(#\"展开的“分包合同-单项和指定”\", {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"自定义\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and [FJIESUANJIAHS] < [FHETONGJIAKUANHANSHUI] then [FHETONGJIAKUANHANSHUI] else  [FJIESUANJIAHS]),",
          "    已添加条件列1 = Table.AddColumn(已添加条件列, \"自定义.1\", each if [FPINGSHENZHUANGTAI] = \"未提交\"  and [FJIESUANJIAHS] < [FHETONGJIAKUANHANSHUI] then [FHETONGJIAKUANBUHANSHUI] else [FJIESUANJIABHS]),",
          "    已添加条件列2 = Table.AddColumn(已添加条件列1, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [自定义.1] else if [FJISHUIFANGSHI] = \"简易计税\" then [自定义] else null),",
          "    删除的列 = Table.RemoveColumns(已添加条件列2,{\"自定义\", \"自定义.1\"}),",
          "    删除的其他列1 = Table.SelectColumns(删除的列,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "分包集采合同-项目已结",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOHETONGXUNIJIESUAN1 = GSPM{[Name=\"GSPM_FENBAOHETONGXUNIJIESUAN\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FENBAOHETONGXUNIJIESUAN1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FPINGSHENZHUANGTAI\", \"FSFJRXM\"}),",
          "    筛选的行1 = Table.SelectRows(删除的其他列, each [FSFJRXM] = \"是\"),",
          "    合并的查询 = Table.NestedJoin(筛选的行1, {\"FHETONGBIANHAO\"}, #\"分包合同-合同信息\", {\"FHETONGBIANHAO\"}, \"分包合同-合同信息\", JoinKind.LeftOuter),",
          "    #\"展开的“分包合同-合同信息”\" = Table.ExpandTableColumn(合并的查询, \"分包合同-合同信息\", {\"FHETONGBIANHAO\"}, {\"FHETONGBIANHAO.1\"}),",
          "    筛选的行2 = Table.SelectRows(#\"展开的“分包合同-合同信息”\", each [FHETONGBIANHAO.1] <> null ),",
          "    合并的查询1 = Table.NestedJoin(筛选的行2, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询1, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [FJIESUANJIABHS] else if [FJISHUIFANGSHI] = \"简易计税\" then [FJIESUANJIAHS] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "分包合同-合同信息",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_HETONGXINXI1 = GSPM{[Name=\"GSPM_HETONGXINXI\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_HETONGXINXI1,{\"FHETONGBIANHAO\", \"FHETONGXIEYIHAO\", \"FXIANGMUBIANMA\", \"FDAIQIANHETONGBIANMA\", \"FSHANGWUKEMUID\", \"FZENGZHISHUISHUILV\", \"FSHIFOUZANGUHETONG\", \"FBUHANSHUIHETONGZONGJIA\", \"FHANSHUIHETONGZONGJIA\", \"FJIESUANZHUANGTAI\", \"FHSJIESUANJINE\", \"FYEWULEIBIE\", \"FSFTCTF\", \"FSFJRXM\", \"FJCQY\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSFJRXM] = \"是\")",
          "in",
          "    筛选的行1"
        ]
      },
      {
        "name": "分包集采合同-项目未结1",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOHETONGXUNIJIESUAN1 = GSPM{[Name=\"GSPM_FENBAOHETONGXUNIJIESUAN\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FENBAOHETONGXUNIJIESUAN1, each [FPINGSHENZHUANGTAI] = \"已完成\" or [FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\"),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FPINGSHENZHUANGTAI\", \"FSFJRXM\"}),",
          "    筛选的行1 = Table.SelectRows(删除的其他列, each [FSFJRXM] = \"是\"),",
          "    合并的查询 = Table.NestedJoin(筛选的行1, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}, #\"分包合同-集采补充\", {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}, \"分包合同-集采补充\", JoinKind.RightOuter),",
          "    筛选的行2 = Table.SelectRows(合并的查询, each ([FXIANGMUBIANMA] = null)),",
          "    删除的列 = Table.RemoveColumns(筛选的行2,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FPINGSHENZHUANGTAI\", \"FSFJRXM\"}),",
          "    #\"展开的“分包合同-合同信息”\" = Table.ExpandTableColumn(删除的列, \"分包合同-集采补充\", {\"FBUCHONGXIEYIHAO\", \"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHIFOUZANGUHETONG\", \"FHANSHUIHETONGZONGJIA\", \"FBUHANSHUIHETONGZONGJIA\", \"FPINGSHENZHUANGTAI\", \"FYEWULEIBIE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FSFJZDXM\", \"FSFJRXM\", \"FJCQY\"}, {\"FBUCHONGXIEYIHAO\", \"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHIFOUZANGUHETONG\", \"FHANSHUIHETONGZONGJIA\", \"FBUHANSHUIHETONGZONGJIA\", \"FPINGSHENZHUANGTAI\", \"FYEWULEIBIE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FSFJZDXM\", \"FSFJRXM\", \"FJCQY\"}),",
          "    筛选的行3 = Table.SelectRows(#\"展开的“分包合同-合同信息”\", each ([FPINGSHENZHUANGTAI] <> \"已作废\")),",
          "    已添加条件列 = Table.AddColumn(筛选的行3, \"自定义\", each if [FPINGSHENZHUANGTAI] = \"未提交\"  and [FHANSHUIHETONGZONGJIA] < 0 then 0 else [FHANSHUIHETONGZONGJIA]),",
          "    已添加条件列1 = Table.AddColumn(已添加条件列, \"自定义.1\", each if [FPINGSHENZHUANGTAI] = \"未提交\"  and [FHANSHUIHETONGZONGJIA] < 0  then 0 else [FBUHANSHUIHETONGZONGJIA]),",
          "    合并的查询1 = Table.NestedJoin(已添加条件列1, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询1, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列2 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [自定义.1] else if [FJISHUIFANGSHI] = \"简易计税\" then [自定义] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列2,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "分包合同-集采补充",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOBUCHONGPINGSHEN1 = GSPM{[Name=\"GSPM_FENBAOBUCHONGPINGSHEN\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_FENBAOBUCHONGPINGSHEN1,{\"FBUCHONGXIEYIHAO\", \"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHIFOUZANGUHETONG\", \"FHANSHUIHETONGZONGJIA\", \"FBUHANSHUIHETONGZONGJIA\", \"FPINGSHENZHUANGTAI\", \"FYEWULEIBIE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FSFJZDXM\", \"FSFJRXM\", \"FJCQY\"}),",
          "    筛选的行1 = Table.SelectRows(删除的其他列, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each [FSFJZDXM] = \"是\"),",
          "    筛选的行3 = Table.SelectRows(筛选的行2, each [FSFJRXM] = \"是\"),",
          "    筛选的行4 = Table.SelectRows(筛选的行3, each [FYEWULEIBIE] = \"集采分包补充合同评审\")",
          "in",
          "    筛选的行4"
        ]
      },
      {
        "name": "分包集采合同-项目未结2",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOHETONGXUNIJIESUAN1 = GSPM{[Name=\"GSPM_FENBAOHETONGXUNIJIESUAN\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FENBAOHETONGXUNIJIESUAN1, each  [FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\"),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FLJQYHTJHS\", \"FLJQYHTJBHS\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FPINGSHENZHUANGTAI\", \"FSFJRXM\"}),",
          "    筛选的行1 = Table.SelectRows(删除的其他列, each [FSFJRXM] = \"是\"),",
          "    合并的查询 = Table.NestedJoin(筛选的行1, {\"FHETONGBIANHAO\"}, #\"分包合同-合同信息\", {\"FHETONGBIANHAO\"}, \"分包合同-合同信息\", JoinKind.LeftOuter),",
          "    #\"展开的“分包合同-合同信息”\" = Table.ExpandTableColumn(合并的查询, \"分包合同-合同信息\", {\"FSHIFOUZANGUHETONG\"}, {\"FSHIFOUZANGUHETONG\"}),",
          "    筛选的行2 = Table.SelectRows(#\"展开的“分包合同-合同信息”\", each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    已添加条件列 = Table.AddColumn(筛选的行2, \"自定义\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and [FJIESUANJIAHS] < [FLJQYHTJHS] then [FLJQYHTJHS] else [FJIESUANJIAHS]),",
          "    已添加条件列1 = Table.AddColumn(已添加条件列, \"自定义.1\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and  [FJIESUANJIAHS] < [FLJQYHTJHS]  then [FLJQYHTJBHS] else [FJIESUANJIABHS]),",
          "    合并的查询1 = Table.NestedJoin(已添加条件列1, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询1, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列2 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [自定义.1] else if [FJISHUIFANGSHI] = \"简易计税\" then [自定义] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列2,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "物资合同-单项和指定已结",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGJIESUANPS1 = GSPM{[Name=\"GSPM_WUZIHETONGJIESUANPS\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGJIESUANPS1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHANGWUKEMUID\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FPINGSHENZHUANGTAI\", \"SCREATETIME\", \"FBIAOZHUNHETONGCODE\"}),",
          "    筛选的行2 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    筛选的行1 = Table.SelectRows(筛选的行2, each ([FSHANGWUKEMUID] <> null)),",
          "    排序的行 = Table.Sort(筛选的行1,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"FSHANGWUKEMUID\", Order.Ascending}, {\"FBIAOZHUNHETONGCODE\", Order.Ascending}, {\"FHETONGBIANHAO\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}),",
          "    合并的查询 = Table.NestedJoin(删除的副本, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    筛选的行3 = Table.SelectRows(#\"展开的“MD_XIANGMUXINXI”\", each ([FJISHUIFANGSHI] <> null)),",
          "    合并的查询1 = Table.NestedJoin(筛选的行3, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHETONGBIANHAO\"}, #\"物资合同-单项和指定\", {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHETONGBIANHAO\"}, \"物资合同-单项和指定\", JoinKind.LeftOuter),",
          "    #\"展开的“物资合同-单项和指定”\" = Table.ExpandTableColumn(合并的查询1, \"物资合同-单项和指定\", {\"FSHIFOUJIESUAN\", \"FSHIFOUZANGUHETONG\", \"FSFJRXM\"}, {\"FSHIFOUJIESUAN\", \"FSHIFOUZANGUHETONG\", \"FSFJRXM\"}),",
          "    筛选的行5 = Table.SelectRows(#\"展开的“物资合同-单项和指定”\", each ([FSHIFOUJIESUAN] = \"是\")),",
          "    筛选的行4 = Table.SelectRows(筛选的行5, each ([FSHIFOUZANGUHETONG] <> \"是\") and ([FSFJRXM] = \"是\")),",
          "    已添加条件列 = Table.AddColumn(筛选的行4, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [FJIESUANJIABHS] else if [FJISHUIFANGSHI] = \"简易计税\" then [FJIESUANJIAHS] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "物资合同-单项和指定",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGXINXI1 = GSPM{[Name=\"GSPM_WUZIHETONGXINXI\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZIHETONGXINXI1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHETONGXIEYIHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FZENGZHISHUILV\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FSHIFOUJIESUAN\", \"FHSJIESUANJINE\", \"FHETONGPINGSHENTYPE\", \"FSFTCTF\", \"FSHIFOUZANGUHETONG\", \"FJIESUANJIABHS\", \"FSFJRXM\", \"FJCQY\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each [FSFJRXM] = \"是\"),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each [FHETONGPINGSHENTYPE] = \"消耗材料专项采购合同\" or [FHETONGPINGSHENTYPE] = \"周转材料租赁合同\" or [FHETONGPINGSHENTYPE] = \"指定物资采购合同\" or [FHETONGPINGSHENTYPE] = \"指定物资租赁合同\")",
          "in",
          "    筛选的行2"
        ]
      },
      {
        "name": "物资合同-单项和指定未结1",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGJIESUANPS1 = GSPM{[Name=\"GSPM_WUZIHETONGJIESUANPS\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGJIESUANPS1, each [FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\"),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHANGWUKEMUID\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FPINGSHENZHUANGTAI\", \"SCREATETIME\", \"FBIAOZHUNHETONGCODE\"}),",
          "    筛选的行2 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    筛选的行1 = Table.SelectRows(筛选的行2, each ([FSHANGWUKEMUID] <> null)),",
          "    排序的行 = Table.Sort(筛选的行1,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"FSHANGWUKEMUID\", Order.Ascending}, {\"FBIAOZHUNHETONGCODE\", Order.Ascending}, {\"FHETONGBIANHAO\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}),",
          "    合并的查询1 = Table.NestedJoin(删除的副本, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHETONGBIANHAO\"}, #\"物资合同-单项和指定\", {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHETONGBIANHAO\"}, \"物资合同-单项和指定\", JoinKind.RightOuter),",
          "    筛选的行3 = Table.SelectRows(合并的查询1, each ([FXIANGMUBIANMA] = null)),",
          "    删除的其他列1 = Table.SelectColumns(筛选的行3,{\"物资合同-单项和指定\"}),",
          "    #\"展开的“物资合同-单项和指定”\" = Table.ExpandTableColumn(删除的其他列1, \"物资合同-单项和指定\", {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHETONGXIEYIHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FZENGZHISHUILV\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FSHIFOUJIESUAN\", \"FHSJIESUANJINE\", \"FHETONGPINGSHENTYPE\", \"FSFTCTF\", \"FSHIFOUZANGUHETONG\", \"FJIESUANJIABHS\", \"FSFJRXM\", \"FJCQY\"}, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHETONGXIEYIHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FZENGZHISHUILV\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FSHIFOUJIESUAN\", \"FHSJIESUANJINE\", \"FHETONGPINGSHENTYPE\", \"FSFTCTF\", \"FSHIFOUZANGUHETONG\", \"FJIESUANJIABHS\", \"FSFJRXM\", \"FJCQY\"}),",
          "    筛选的行5 = Table.SelectRows(#\"展开的“物资合同-单项和指定”\", each ([FSHIFOUJIESUAN] <> \"是\")),",
          "    筛选的行4 = Table.SelectRows(筛选的行5, each ([FSHIFOUZANGUHETONG] <> \"是\") and ([FSFJRXM] = \"是\")),",
          "    合并的查询 = Table.NestedJoin(筛选的行4, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    筛选的行6 = Table.SelectRows(#\"展开的“MD_XIANGMUXINXI”\", each ([FJISHUIFANGSHI] <> null) and ([FBIAOZHUNHETONGCODE] <> null)),",
          "    已添加条件列 = Table.AddColumn(筛选的行6, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [FBUHANSHUIHETONGJIAKUAN] else if [FJISHUIFANGSHI] = \"简易计税\" then [FHANSHUIHETONGJIAKUAN] else null),",
          "    删除的其他列2 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列2"
        ]
      },
      {
        "name": "物资合同-单项和指定未结2",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGPS1 = GSPM{[Name=\"GSPM_WUZIHETONGPS\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZIHETONGPS1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FPINGSHENZHUANGTAI\", \"FSHIFOUZANGUHETONG\", \"FSFJRXM\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null) and ([FSHANGWUKEMUID] <> null) and ([FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\") and ([FSHIFOUZANGUHETONG] <> \"是\")),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSFJRXM] = \"是\"),",
          "    合并的查询 = Table.NestedJoin(筛选的行1, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [FBUHANSHUIHETONGJIAKUAN] else if [FJISHUIFANGSHI] = \"简易计税\" then [FHANSHUIHETONGJIAKUAN] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "物资合同-单项和指定未结3",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGBUCHONG1 = GSPM{[Name=\"GSPM_WUZIHETONGBUCHONG\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZIHETONGBUCHONG1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBUCHONGXIEYIHAO\", \"FHANSHUIHETONGZONGJIA\", \"FBUHANSHUIHETONGJIAKUAN\", \"FPINGSHENZHUANGTAI\", \"FHETONGPINGSHENTYPE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FSFJZDXM\", \"FSHIFOUZANGUHETONG\", \"FZENGZHISHUISHUILV\", \"FSFJRXM\"}),",
          "    筛选的行3 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    筛选的行 = Table.SelectRows(筛选的行3, each ([FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\")),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSFJRXM] = \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each ([FSHIFOUZANGUHETONG] <> \"是\") and ([FHETONGPINGSHENTYPE] = \"周转材料租赁补充合同\" or [FHETONGPINGSHENTYPE] = \"指定物资采购补充合同\" or [FHETONGPINGSHENTYPE] = \"指定物资租赁补充合同\" or [FHETONGPINGSHENTYPE] = \"消耗材料专项采购补充合同\")),",
          "    合并的查询 = Table.NestedJoin(筛选的行2, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"自定义\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and [FHANSHUIHETONGZONGJIA] < 0 then 0 else [FHANSHUIHETONGZONGJIA]),",
          "    已添加条件列1 = Table.AddColumn(已添加条件列, \"自定义.1\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and [FHANSHUIHETONGZONGJIA] < 0 then 0 else [FBUHANSHUIHETONGJIAKUAN]),",
          "    已添加条件列2 = Table.AddColumn(已添加条件列1, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [自定义.1] else if [FJISHUIFANGSHI] = \"简易计税\" then [自定义] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列2,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "物资合同-单项和指定未结4",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGJIESUANPS1 = GSPM{[Name=\"GSPM_WUZIHETONGJIESUANPS\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGJIESUANPS1, each [FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\"),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHANGWUKEMUID\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FPINGSHENZHUANGTAI\", \"SCREATETIME\", \"FBIAOZHUNHETONGCODE\"}),",
          "    筛选的行2 = Table.SelectRows(删除的其他列, each ([FBIAOZHUNHETONGCODE] <> null)),",
          "    筛选的行1 = Table.SelectRows(筛选的行2, each ([FSHANGWUKEMUID] <> null)),",
          "    排序的行 = Table.Sort(筛选的行1,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"FSHANGWUKEMUID\", Order.Ascending}, {\"FBIAOZHUNHETONGCODE\", Order.Ascending}, {\"FHETONGBIANHAO\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
          "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\"}),",
          "    合并的查询1 = Table.NestedJoin(删除的副本, {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHETONGBIANHAO\"}, #\"物资合同-单项和指定\", {\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"FHETONGBIANHAO\"}, \"物资合同-单项和指定\", JoinKind.RightOuter),",
          "    筛选的行3 = Table.SelectRows(合并的查询1, each [FXIANGMUBIANMA] <> null),",
          "    #\"展开的“物资合同-单项和指定”\" = Table.ExpandTableColumn(筛选的行3, \"物资合同-单项和指定\", {\"FSHIFOUJIESUAN\", \"FSHIFOUZANGUHETONG\", \"FSFJRXM\"}, {\"FSHIFOUJIESUAN\", \"FSHIFOUZANGUHETONG\", \"FSFJRXM\"}),",
          "    筛选的行5 = Table.SelectRows(#\"展开的“物资合同-单项和指定”\", each ([FSHIFOUJIESUAN] <> \"是\")),",
          "    筛选的行4 = Table.SelectRows(筛选的行5, each ([FSHIFOUZANGUHETONG] <> \"是\") and ([FSFJRXM] = \"是\")),",
          "    合并的查询 = Table.NestedJoin(筛选的行4, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    筛选的行6 = Table.SelectRows(#\"展开的“MD_XIANGMUXINXI”\", each ([FJISHUIFANGSHI] <> null) and ([FBIAOZHUNHETONGCODE] <> null)),",
          "    已添加条件列1 = Table.AddColumn(筛选的行6, \"自定义\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and [FJIESUANJIAHS] < [FHANSHUIHETONGJIAKUAN]  then [FHANSHUIHETONGJIAKUAN] else [FJIESUANJIAHS]),",
          "    已添加条件列2 = Table.AddColumn(已添加条件列1, \"自定义.1\", each if [FPINGSHENZHUANGTAI] = \"未提交\"  and [FJIESUANJIAHS] < [FHANSHUIHETONGJIAKUAN]  then [FBUHANSHUIHETONGJIAKUAN] else [FJIESUANJIABHS]),",
          "    已添加条件列 = Table.AddColumn(已添加条件列2, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [自定义.1] else if [FJISHUIFANGSHI] = \"简易计税\" then [自定义] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FSHANGWUKEMUID\", \"FBIAOZHUNHETONGCODE\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "物资集采合同-项目已结",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGXUNIJIESUANPS1 = GSPM{[Name=\"GSPM_WUZIHETONGXUNIJIESUANPS\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZIHETONGXUNIJIESUANPS1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FPINGSHENZHUANGTAI\", \"FSFJRXM\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FSHANGWUKEMUID] <> null) and ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSFJRXM] = \"是\"),",
          "    合并的查询 = Table.NestedJoin(筛选的行1, {\"FHETONGBIANHAO\"}, #\"物资合同-合同信息\", {\"FHETONGBIANHAO\"}, \"物资合同-合同信息\", JoinKind.LeftOuter),",
          "    #\"展开的“物资合同-合同信息”\" = Table.ExpandTableColumn(合并的查询, \"物资合同-合同信息\", {\"FHETONGBIANHAO\"}, {\"FHETONGBIANHAO.1\"}),",
          "    筛选的行2 = Table.SelectRows(#\"展开的“物资合同-合同信息”\", each [FHETONGBIANHAO.1] <> null),",
          "    合并的查询1 = Table.NestedJoin(筛选的行2, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询1, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [FJIESUANJIABHS] else if [FJISHUIFANGSHI] = \"简易计税\" then [FJIESUANJIAHS] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      },
      {
        "name": "物资合同-合同信息",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGXINXI1 = GSPM{[Name=\"GSPM_WUZIHETONGXINXI\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZIHETONGXINXI1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHETONGXIEYIHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FZENGZHISHUILV\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FSHIFOUJIESUAN\", \"FHSJIESUANJINE\", \"FHETONGPINGSHENTYPE\", \"FSFTCTF\", \"FSHIFOUZANGUHETONG\", \"FJIESUANJIABHS\", \"FSFJRXM\", \"FJCQY\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each [FSFJRXM] = \"是\"),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each [FSHIFOUZANGUHETONG] <> \"是\")",
          "in",
          "    筛选的行1"
        ]
      },
      {
        "name": "物资集采合同-项目未结1",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGXUNIJIESUANPS1 = GSPM{[Name=\"GSPM_WUZIHETONGXUNIJIESUANPS\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZIHETONGXUNIJIESUANPS1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FHANSHUIHETONGJIAKUAN\", \"FBUHANSHUIHETONGJIAKUAN\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FPINGSHENZHUANGTAI\", \"FSFJRXM\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FSHANGWUKEMUID] <> null)),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each ([FSFJRXM] = \"是\") and ([FPINGSHENZHUANGTAI] = \"已完成\" or [FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\")),",
          "    合并的查询 = Table.NestedJoin(筛选的行1, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}, #\"物资合同-集采补充\", {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\"}, \"物资合同-集采补充\", JoinKind.RightOuter),",
          "    筛选的行3 = Table.SelectRows(合并的查询, each [FXIANGMUBIANMA] = null),",
          "    删除的其他列1 = Table.SelectColumns(筛选的行3,{\"物资合同-集采补充\"}),",
          "    #\"展开的“物资合同-集采补充”\" = Table.ExpandTableColumn(删除的其他列1, \"物资合同-集采补充\", {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBUCHONGXIEYIHAO\", \"FHANSHUIHETONGZONGJIA\", \"FBUHANSHUIHETONGJIAKUAN\", \"FPINGSHENZHUANGTAI\", \"FHETONGPINGSHENTYPE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FSFJZDXM\", \"FSHIFOUZANGUHETONG\", \"FZENGZHISHUISHUILV\", \"FSFJRXM\"}, {\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBUCHONGXIEYIHAO\", \"FHANSHUIHETONGZONGJIA\", \"FBUHANSHUIHETONGJIAKUAN\", \"FPINGSHENZHUANGTAI\", \"FHETONGPINGSHENTYPE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FSFJZDXM\", \"FSHIFOUZANGUHETONG\", \"FZENGZHISHUISHUILV\", \"FSFJRXM\"}),",
          "    筛选的行2 = Table.SelectRows(#\"展开的“物资合同-集采补充”\", each ([FPINGSHENZHUANGTAI] <> \"已作废\")),",
          "    已添加条件列 = Table.AddColumn(筛选的行2, \"自定义\", each if [FPINGSHENZHUANGTAI] = \"未提交\"  and [FHANSHUIHETONGZONGJIA] < 0 then 0 else [FHANSHUIHETONGZONGJIA]),",
          "    已添加条件列1 = Table.AddColumn(已添加条件列, \"自定义.1\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and [FHANSHUIHETONGZONGJIA] < 0 then 0 else [FBUHANSHUIHETONGJIAKUAN]),",
          "    合并的查询1 = Table.NestedJoin(已添加条件列1, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询1, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列2 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [自定义.1] else if [FJISHUIFANGSHI] = \"简易计税\" then [自定义] else null),",
          "    删除的其他列2 = Table.SelectColumns(已添加条件列2,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列2"
        ]
      },
      {
        "name": "物资合同-集采补充",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGBUCHONG1 = GSPM{[Name=\"GSPM_WUZIHETONGBUCHONG\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZIHETONGBUCHONG1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FBUCHONGXIEYIHAO\", \"FHANSHUIHETONGZONGJIA\", \"FBUHANSHUIHETONGJIAKUAN\", \"FPINGSHENZHUANGTAI\", \"FHETONGPINGSHENTYPE\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FSFJZDXM\", \"FSHIFOUZANGUHETONG\", \"FZENGZHISHUISHUILV\", \"FSFJRXM\"}),",
          "    筛选的行1 = Table.SelectRows(删除的其他列, each [FSFJRXM] = \"是\"),",
          "    筛选的行2 = Table.SelectRows(筛选的行1, each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    筛选的行3 = Table.SelectRows(筛选的行2, each [FSFJZDXM] = \"是\"),",
          "    筛选的行4 = Table.SelectRows(筛选的行3, each [FHETONGPINGSHENTYPE] = \"统一转账补充合同\" or [FHETONGPINGSHENTYPE] = \"集采租赁补充合同\")",
          "in",
          "    筛选的行4"
        ]
      },
      {
        "name": "物资集采合同-项目未结2",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGXUNIJIESUANPS1 = GSPM{[Name=\"GSPM_WUZIHETONGXUNIJIESUANPS\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZIHETONGXUNIJIESUANPS1,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FJIESUANJIAHS\", \"FJIESUANJIABHS\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"FPINGSHENZHUANGTAI\", \"FLJQYHTJHS\", \"FLJQYHTJBHS\", \"FSFJRXM\"}),",
          "    筛选的行 = Table.SelectRows(删除的其他列, each ([FSHANGWUKEMUID] <> null)),",
          "    筛选的行1 = Table.SelectRows(筛选的行, each ([FSFJRXM] = \"是\") and ([FPINGSHENZHUANGTAI] = \"处理中\" or [FPINGSHENZHUANGTAI] = \"未提交\")),",
          "    合并的查询 = Table.NestedJoin(筛选的行1, {\"FHETONGBIANHAO\"}, #\"物资合同-合同信息\", {\"FHETONGBIANHAO\"}, \"物资合同-合同信息\", JoinKind.LeftOuter),",
          "    #\"展开的“物资合同-合同信息”\" = Table.ExpandTableColumn(合并的查询, \"物资合同-合同信息\", {\"FSHIFOUZANGUHETONG\"}, {\"FSHIFOUZANGUHETONG\"}),",
          "    筛选的行2 = Table.SelectRows(#\"展开的“物资合同-合同信息”\", each [FSHIFOUZANGUHETONG] <> \"是\"),",
          "    合并的查询1 = Table.NestedJoin(筛选的行2, {\"FXIANGMUBIANMA\"}, MD_XIANGMUXINXI, {\"FXMBIANMA\"}, \"MD_XIANGMUXINXI\", JoinKind.LeftOuter),",
          "    #\"展开的“MD_XIANGMUXINXI”\" = Table.ExpandTableColumn(合并的查询1, \"MD_XIANGMUXINXI\", {\"FJISHUIFANGSHI\"}, {\"FJISHUIFANGSHI\"}),",
          "    已添加条件列 = Table.AddColumn(#\"展开的“MD_XIANGMUXINXI”\", \"自定义\", each if [FPINGSHENZHUANGTAI] = \"未提交\"  and [FJIESUANJIAHS] < [FLJQYHTJHS] then [FLJQYHTJHS] else [FJIESUANJIAHS]),",
          "    已添加条件列1 = Table.AddColumn(已添加条件列, \"自定义.1\", each if [FPINGSHENZHUANGTAI] = \"未提交\" and [FJIESUANJIAHS] < [FLJQYHTJHS]  then [FLJQYHTJBHS] else [FJIESUANJIABHS]),",
          "    已添加条件列2 = Table.AddColumn(已添加条件列1, \"fLJQYEHZT\", each if [FJISHUIFANGSHI] = \"一般计税\" then [自定义.1] else if [FJISHUIFANGSHI] = \"简易计税\" then [自定义] else null),",
          "    删除的其他列1 = Table.SelectColumns(已添加条件列2,{\"FXIANGMUBIANMA\", \"FBIAOZHUNHETONGCODE\", \"FSHANGWUKEMUID\", \"fLJQYEHZT\"})",
          "in",
          "    删除的其他列1"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      }
    ]
  },
  "id": "SemanticModel"
}