{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "name": "模型",
    "culture": "zh-CN",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "Oracle/172 16 8 78/oracledb",
        "connectionDetails": {
          "protocol": "oracle",
          "address": {
            "server": "172.16.8.78/oracledb"
          },
          "authentication": null,
          "query": null
        },
        "options": {
          "hierarchicalNavigation": true
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "Oracle",
          "path": "172.16.8.78/oracledb",
          "Username": "gspm",
          "PrivacySetting": "Public"
        }
      },
      {
        "type": "structured",
        "name": "Oracle/172 16 8 127/racdb com",
        "connectionDetails": {
          "protocol": "oracle",
          "address": {
            "server": "172.16.8.127/racdb.com"
          },
          "authentication": null,
          "query": null
        },
        "options": {
          "hierarchicalNavigation": true
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "Oracle",
          "path": "172.16.8.127/racdb.com",
          "Username": "picc",
          "PrivacySetting": "Public"
        }
      }
    ],
    "tables": [
      {
        "name": "分包合同表",
        "columns": [
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "合同协议号",
            "dataType": "string",
            "sourceColumn": "合同协议号"
          },
          {
            "name": "合同名称",
            "dataType": "string",
            "sourceColumn": "合同名称"
          },
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "待签合同编号",
            "dataType": "string",
            "sourceColumn": "待签合同编号"
          },
          {
            "name": "待签合同名称",
            "dataType": "string",
            "sourceColumn": "待签合同名称"
          },
          {
            "name": "商务科目全路径",
            "dataType": "string",
            "sourceColumn": "商务科目全路径"
          },
          {
            "name": "财务科目全路径",
            "dataType": "string",
            "sourceColumn": "财务科目全路径"
          },
          {
            "name": "是否临建分包合同",
            "dataType": "string",
            "sourceColumn": "是否临建分包合同"
          },
          {
            "name": "施工专业",
            "dataType": "string",
            "sourceColumn": "施工专业"
          },
          {
            "name": "合同类型",
            "dataType": "string",
            "sourceColumn": "合同类型"
          },
          {
            "name": "招标方式",
            "dataType": "string",
            "sourceColumn": "招标方式"
          },
          {
            "name": "分包编码",
            "dataType": "string",
            "sourceColumn": "分包编码"
          },
          {
            "name": "分包名称",
            "dataType": "string",
            "sourceColumn": "分包名称"
          },
          {
            "name": "是否在一局协同平台准入",
            "dataType": "string",
            "sourceColumn": "是否在一局协同平台准入"
          },
          {
            "name": "纳税人性质",
            "dataType": "string",
            "sourceColumn": "纳税人性质"
          },
          {
            "name": "增值税税率",
            "dataType": "double",
            "sourceColumn": "增值税税率"
          },
          {
            "name": "增值税发票类别",
            "dataType": "string",
            "sourceColumn": "增值税发票类别"
          },
          {
            "name": "合同约定的收票时点",
            "dataType": "string",
            "sourceColumn": "合同约定的收票时点"
          },
          {
            "name": "是否非常规分包合同",
            "dataType": "string",
            "sourceColumn": "是否非常规分包合同"
          },
          {
            "name": "是否暂估合同",
            "dataType": "string",
            "sourceColumn": "是否暂估合同"
          },
          {
            "name": "分包类别",
            "dataType": "string",
            "sourceColumn": "分包类别"
          },
          {
            "name": "局分包类别",
            "dataType": "string",
            "sourceColumn": "局分包类别"
          },
          {
            "name": "承包范围",
            "dataType": "string",
            "sourceColumn": "承包范围"
          },
          {
            "name": "合同内容描述",
            "dataType": "string",
            "sourceColumn": "合同内容描述"
          },
          {
            "name": "质量目标",
            "dataType": "string",
            "sourceColumn": "质量目标"
          },
          {
            "name": "分包开工日期",
            "dataType": "dateTime",
            "sourceColumn": "分包开工日期"
          },
          {
            "name": "分包完工日期",
            "dataType": "dateTime",
            "sourceColumn": "分包完工日期"
          },
          {
            "name": "定价原则",
            "dataType": "string",
            "sourceColumn": "定价原则"
          },
          {
            "name": "结算准则",
            "dataType": "string",
            "sourceColumn": "结算准则"
          },
          {
            "name": "签订时间",
            "dataType": "dateTime",
            "sourceColumn": "签订时间"
          },
          {
            "name": "不含税合同总价",
            "dataType": "double",
            "sourceColumn": "不含税合同总价"
          },
          {
            "name": "含税合同总价",
            "dataType": "double",
            "sourceColumn": "含税合同总价"
          },
          {
            "name": "税金",
            "dataType": "double",
            "sourceColumn": "税金"
          },
          {
            "name": "超过合约规划金额说明",
            "dataType": "string",
            "sourceColumn": "超过合约规划金额说明"
          },
          {
            "name": "附件",
            "dataType": "string",
            "sourceColumn": "附件"
          },
          {
            "name": "是否已结算",
            "dataType": "string",
            "sourceColumn": "是否已结算"
          },
          {
            "name": "含税结算金额",
            "dataType": "double",
            "sourceColumn": "含税结算金额"
          },
          {
            "name": "结算考核状态",
            "dataType": "string",
            "sourceColumn": "结算考核状态"
          },
          {
            "name": "结算考核完成时间",
            "dataType": "dateTime",
            "sourceColumn": "结算考核完成时间"
          },
          {
            "name": "业务类别",
            "dataType": "string",
            "sourceColumn": "业务类别"
          },
          {
            "name": "提交者",
            "dataType": "string",
            "sourceColumn": "提交者"
          },
          {
            "name": "提交者岗位",
            "dataType": "string",
            "sourceColumn": "提交者岗位"
          },
          {
            "name": "提交者部门",
            "dataType": "string",
            "sourceColumn": "提交者部门"
          },
          {
            "name": "提交者机构",
            "dataType": "string",
            "sourceColumn": "提交者机构"
          },
          {
            "name": "创建时间",
            "dataType": "dateTime",
            "sourceColumn": "创建时间"
          },
          {
            "name": "最后修改人",
            "dataType": "string",
            "sourceColumn": "最后修改人"
          },
          {
            "name": "最后修改时间",
            "dataType": "dateTime",
            "sourceColumn": "最后修改时间"
          },
          {
            "name": "预付款金额",
            "dataType": "double",
            "sourceColumn": "预付款金额"
          },
          {
            "name": "预付款担保形式",
            "dataType": "string",
            "sourceColumn": "预付款担保形式"
          },
          {
            "name": "预付款担保形式编码",
            "dataType": "string",
            "sourceColumn": "预付款担保形式编码"
          },
          {
            "name": "股份财务一体化项目名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目名称"
          },
          {
            "name": "对方负责人",
            "dataType": "string",
            "sourceColumn": "对方负责人"
          },
          {
            "name": "司法保全金额(元)",
            "dataType": "double",
            "sourceColumn": "司法保全金额(元)"
          },
          {
            "name": "收款单位开户行名称",
            "dataType": "string",
            "sourceColumn": "收款单位开户行名称"
          },
          {
            "name": "收款单位银行账号",
            "dataType": "string",
            "sourceColumn": "收款单位银行账号"
          },
          {
            "name": "对方签约单位",
            "dataType": "string",
            "sourceColumn": "对方签约单位"
          },
          {
            "name": "股份财务一体化项目编码",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目编码"
          },
          {
            "name": "人工费金额",
            "dataType": "double",
            "sourceColumn": "人工费金额"
          },
          {
            "name": "人工费比例",
            "dataType": "double",
            "sourceColumn": "人工费比例"
          },
          {
            "name": "股份财务一体化组织机构名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化组织机构名称"
          },
          {
            "name": "是否已做三方抵债",
            "dataType": "string",
            "sourceColumn": "是否已做三方抵债"
          },
          {
            "name": "对应集采分包框架协议编号",
            "dataType": "string",
            "sourceColumn": "对应集采分包框架协议编号"
          },
          {
            "name": "对应集采分包框架协议名称",
            "dataType": "string",
            "sourceColumn": "对应集采分包框架协议名称"
          },
          {
            "name": "填报单位编码",
            "dataType": "string",
            "sourceColumn": "填报单位编码"
          },
          {
            "name": "填报单位名称",
            "dataType": "string",
            "sourceColumn": "填报单位名称"
          },
          {
            "name": "标准合同是否满额签约",
            "dataType": "string",
            "sourceColumn": "标准合同是否满额签约"
          },
          {
            "name": "是否已更新标准合同",
            "dataType": "string",
            "sourceColumn": "是否已更新标准合同"
          },
          {
            "name": "是否合同外签约",
            "dataType": "string",
            "sourceColumn": "是否合同外签约"
          },
          {
            "name": "国内/外",
            "dataType": "string",
            "sourceColumn": "国内/外"
          },
          {
            "name": "我司拟用签约主体",
            "dataType": "string",
            "sourceColumn": "我司拟用签约主体"
          },
          {
            "name": "是否EPC设计合同",
            "dataType": "string",
            "sourceColumn": "是否EPC设计合同"
          },
          {
            "name": "分包单位是否国内",
            "dataType": "string",
            "sourceColumn": "分包单位是否国内"
          },
          {
            "name": "分包模式",
            "dataType": "string",
            "sourceColumn": "分包模式"
          },
          {
            "name": "合同计价货币",
            "dataType": "string",
            "sourceColumn": "合同计价货币"
          },
          {
            "name": "计价货币兑人民币汇率",
            "dataType": "double",
            "sourceColumn": "计价货币兑人民币汇率"
          },
          {
            "name": "核定制造成本价款(计价货币)",
            "dataType": "double",
            "sourceColumn": "核定制造成本价款(计价货币)"
          },
          {
            "name": "预付款金额(计价货币)",
            "dataType": "double",
            "sourceColumn": "预付款金额(计价货币)"
          },
          {
            "name": "是否提供等额预付款保函",
            "dataType": "string",
            "sourceColumn": "是否提供等额预付款保函"
          },
          {
            "name": "含税合同总价(计价货币)",
            "dataType": "double",
            "sourceColumn": "含税合同总价(计价货币)"
          },
          {
            "name": "不含税合同总价(计价货币)",
            "dataType": "double",
            "sourceColumn": "不含税合同总价(计价货币)"
          },
          {
            "name": "税金(计价货币)",
            "dataType": "double",
            "sourceColumn": "税金(计价货币)"
          },
          {
            "name": "劳务人工费金额(计价货币)",
            "dataType": "double",
            "sourceColumn": "劳务人工费金额(计价货币)"
          },
          {
            "name": "付款货币",
            "dataType": "string",
            "sourceColumn": "付款货币"
          },
          {
            "name": "付款方式",
            "dataType": "string",
            "sourceColumn": "付款方式"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_HETONGXINXI = GSPM{[Name=\"GSPM_HETONGXINXI\"]}[Data],",
                "    重命名的列 = Table.RenameColumns(GSPM_HETONGXINXI,fx_List_生成字段更名列表(\"GSPM\",\"GSPM_HETONGXINXI\")),",
                "    去除的文本 = Table.TransformColumns(重命名的列,{{\"项目名称\", Text.Trim, type text}}),",
                "    删除的列 = Table.RemoveColumns(去除的文本,{\"FID\", \"版本\", \"项目ID\", \"项目编号\", \"对应承包合同ID\", \"对应承包合同编号\", \"对应承包合同名称\", \"待签合同ID\", \"商务科目ID\", \"商务科目编码\", \"商务科目\", \"商务科目全路径ID\", \"商务科目全路径编码\", \"商务科目级次码\", \"财务科目ID\", \"财务科目编码\", \"财务科目\", \"财务科目全路径ID\", \"财务科目全路径编码\", \"财务科目级次码\", \"分包ID\", \"主表ID\", \"提交者ID\", \"提交者岗位ID\", \"提交者部门ID\", \"提交者机构ID\", \"组织全路径ID\", \"组织全路径名\", \"最后修改人标识\", \"一体化合同账户\", \"密码\"}),",
                "    提取的日期 = Table.TransformColumns(删除的列,{{\"签订时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            }
          }
        ]
      },
      {
        "name": "分包报量表",
        "columns": [
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "分包名称",
            "dataType": "string",
            "sourceColumn": "分包名称"
          },
          {
            "name": "报量金额",
            "dataType": "double",
            "sourceColumn": "报量金额"
          },
          {
            "name": "报量税额",
            "dataType": "double",
            "sourceColumn": "报量税额"
          },
          {
            "name": "报量价税合计",
            "dataType": "double",
            "sourceColumn": "报量价税合计"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "专业",
            "dataType": "string",
            "sourceColumn": "专业"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Table.NestedJoin(分包报量明细, {\"FSHENPIBIAOID\"}, 分包报量主表, {\"FID\"}, \"分包报量主表\", JoinKind.Inner),",
                "    #\"展开的“分包报量主表”\" = Table.ExpandTableColumn(源, \"分包报量主表\", {\"项目名称\", \"年\", \"月\", \"专业\"}, {\"项目名称\", \"年\", \"月\", \"专业\"}),",
                "    删除的列 = Table.RemoveColumns(#\"展开的“分包报量主表”\",{\"FSHENPIBIAOID\"}),",
                "    已添加自定义 = Table.AddColumn(删除的列, \"日期\", each #date([年],[月],1),type date)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ]
      },
      {
        "name": "分包付款主表",
        "columns": [
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "本期实际付款",
            "dataType": "double",
            "sourceColumn": "本期实际付款"
          },
          {
            "name": "单据状态",
            "dataType": "string",
            "sourceColumn": "单据状态"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_FENBAOGONGCHENGFUKUAN = GSPM{[Name=\"GSPM_FENBAOGONGCHENGFUKUAN\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(GSPM_FENBAOGONGCHENGFUKUAN,{\"FNIAN\", \"FYUE\", \"FHETONGBIANHAO\", \"FBENQISHIJIFUKUAN\", \"FPINGSHENZHUANGTAI2\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FBENQISHIJIFUKUAN\", \"本期实际付款\"}, {\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FPINGSHENZHUANGTAI2\", \"单据状态\"}}),",
                "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1),type date)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ]
      },
      {
        "name": "分包结算",
        "columns": [
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "含税结算额",
            "dataType": "double",
            "sourceColumn": "含税结算额"
          },
          {
            "name": "单据状态",
            "dataType": "string",
            "sourceColumn": "单据状态"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_FENBAOHETONGJIESUAN = GSPM{[Name=\"GSPM_FENBAOHETONGJIESUAN\"]}[Data],",
                "    筛选的行1 = Table.SelectRows(GSPM_FENBAOHETONGJIESUAN, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
                "    删除的其他列 = Table.SelectColumns(筛选的行1,{\"FHETONGBIANHAO\", \"FJIESUANJIAHS\", \"FPINGSHENZHUANGTAI\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FJIESUANJIAHS\", \"含税结算额\"}, {\"FPINGSHENZHUANGTAI\", \"单据状态\"}})",
                "in",
                "    重命名的列"
              ]
            }
          }
        ]
      },
      {
        "name": "项目信息",
        "columns": [
          {
            "name": "FID",
            "dataType": "string",
            "sourceColumn": "FID"
          },
          {
            "name": "版本",
            "dataType": "double",
            "sourceColumn": "版本"
          },
          {
            "name": "单据编号",
            "dataType": "string",
            "sourceColumn": "单据编号"
          },
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目编号",
            "dataType": "string",
            "sourceColumn": "项目编号"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "项目总监",
            "dataType": "string",
            "sourceColumn": "项目总监"
          },
          {
            "name": "履约项目经理",
            "dataType": "string",
            "sourceColumn": "履约项目经理"
          },
          {
            "name": "备案项目经理",
            "dataType": "string",
            "sourceColumn": "备案项目经理"
          },
          {
            "name": "执行经理",
            "dataType": "string",
            "sourceColumn": "执行经理"
          },
          {
            "name": "商务经理",
            "dataType": "string",
            "sourceColumn": "商务经理"
          },
          {
            "name": "总部联络人",
            "dataType": "string",
            "sourceColumn": "总部联络人"
          },
          {
            "name": "所属大项目部",
            "dataType": "string",
            "sourceColumn": "所属大项目部"
          },
          {
            "name": "项目管理方式",
            "dataType": "string",
            "sourceColumn": "项目管理方式"
          },
          {
            "name": "FZHIGUANJG",
            "dataType": "string",
            "sourceColumn": "FZHIGUANJG"
          },
          {
            "name": "监管机构",
            "dataType": "string",
            "sourceColumn": "监管机构"
          },
          {
            "name": "照管机构",
            "dataType": "string",
            "sourceColumn": "照管机构"
          },
          {
            "name": "专业分类",
            "dataType": "string",
            "sourceColumn": "专业分类"
          },
          {
            "name": "项目性质",
            "dataType": "string",
            "sourceColumn": "项目性质"
          },
          {
            "name": "附加税率",
            "dataType": "double",
            "sourceColumn": "附加税率"
          },
          {
            "name": "增值税计税方式",
            "dataType": "string",
            "sourceColumn": "增值税计税方式"
          },
          {
            "name": "京内外分布",
            "dataType": "string",
            "sourceColumn": "京内外分布"
          },
          {
            "name": "区域",
            "dataType": "string",
            "sourceColumn": "区域"
          },
          {
            "name": "省",
            "dataType": "string",
            "sourceColumn": "省"
          },
          {
            "name": "城市",
            "dataType": "string",
            "sourceColumn": "城市"
          },
          {
            "name": "县",
            "dataType": "string",
            "sourceColumn": "县"
          },
          {
            "name": "详细地址",
            "dataType": "string",
            "sourceColumn": "详细地址"
          },
          {
            "name": "设计单位",
            "dataType": "string",
            "sourceColumn": "设计单位"
          },
          {
            "name": "监理单位",
            "dataType": "string",
            "sourceColumn": "监理单位"
          },
          {
            "name": "建设单位",
            "dataType": "string",
            "sourceColumn": "建设单位"
          },
          {
            "name": "顾问管理公司",
            "dataType": "string",
            "sourceColumn": "顾问管理公司"
          },
          {
            "name": "施工单位",
            "dataType": "string",
            "sourceColumn": "施工单位"
          },
          {
            "name": "签约单位",
            "dataType": "string",
            "sourceColumn": "签约单位"
          },
          {
            "name": "建筑面积(㎡)",
            "dataType": "double",
            "sourceColumn": "建筑面积(㎡)"
          },
          {
            "name": "其中地下建筑面积(㎡)",
            "dataType": "double",
            "sourceColumn": "其中地下建筑面积(㎡)"
          },
          {
            "name": "地上层数",
            "dataType": "double",
            "sourceColumn": "地上层数"
          },
          {
            "name": "地下层数",
            "dataType": "double",
            "sourceColumn": "地下层数"
          },
          {
            "name": "中标合同价(万元)",
            "dataType": "double",
            "sourceColumn": "中标合同价(万元)"
          },
          {
            "name": "中标合同自施部分(万元)",
            "dataType": "double",
            "sourceColumn": "中标合同自施部分(万元)"
          },
          {
            "name": "中标日期",
            "dataType": "dateTime",
            "sourceColumn": "中标日期"
          },
          {
            "name": "签约日期",
            "dataType": "dateTime",
            "sourceColumn": "签约日期"
          },
          {
            "name": "实际开工日期",
            "dataType": "dateTime",
            "sourceColumn": "实际开工日期"
          },
          {
            "name": "实际竣工日期",
            "dataType": "dateTime",
            "sourceColumn": "实际竣工日期"
          },
          {
            "name": "单体个数(≥5000平米)",
            "dataType": "double",
            "sourceColumn": "单体个数(≥5000平米)"
          },
          {
            "name": "单体工程数量(个)",
            "dataType": "double",
            "sourceColumn": "单体工程数量(个)"
          },
          {
            "name": "长(跨)度(m)",
            "dataType": "double",
            "sourceColumn": "长(跨)度(m)"
          },
          {
            "name": "建筑高度(m)",
            "dataType": "double",
            "sourceColumn": "建筑高度(m)"
          },
          {
            "name": "是否重点项目",
            "dataType": "string",
            "sourceColumn": "是否重点项目"
          },
          {
            "name": "是否地产项目",
            "dataType": "string",
            "sourceColumn": "是否地产项目"
          },
          {
            "name": "规划许可证",
            "dataType": "string",
            "sourceColumn": "规划许可证"
          },
          {
            "name": "施工许可证",
            "dataType": "string",
            "sourceColumn": "施工许可证"
          },
          {
            "name": "项目实施状态",
            "dataType": "string",
            "sourceColumn": "项目实施状态"
          },
          {
            "name": "项目中标方式",
            "dataType": "string",
            "sourceColumn": "项目中标方式"
          },
          {
            "name": "建筑用途",
            "dataType": "string",
            "sourceColumn": "建筑用途"
          },
          {
            "name": "项目经理资质等级",
            "dataType": "string",
            "sourceColumn": "项目经理资质等级"
          },
          {
            "name": "工程所在国家",
            "dataType": "string",
            "sourceColumn": "工程所在国家"
          },
          {
            "name": "工程类别[一级]",
            "dataType": "string",
            "sourceColumn": "工程类别[一级]"
          },
          {
            "name": "工程类别[二级]",
            "dataType": "string",
            "sourceColumn": "工程类别[二级]"
          },
          {
            "name": "合同开工日期",
            "dataType": "dateTime",
            "sourceColumn": "合同开工日期"
          },
          {
            "name": "合同竣工日期",
            "dataType": "dateTime",
            "sourceColumn": "合同竣工日期"
          },
          {
            "name": "合同质量目标",
            "dataType": "string",
            "sourceColumn": "合同质量目标"
          },
          {
            "name": "结构形式",
            "dataType": "string",
            "sourceColumn": "结构形式"
          },
          {
            "name": "基础形式",
            "dataType": "string",
            "sourceColumn": "基础形式"
          },
          {
            "name": "檐高(m)",
            "dataType": "double",
            "sourceColumn": "檐高(m)"
          },
          {
            "name": "地下深度(m)",
            "dataType": "double",
            "sourceColumn": "地下深度(m)"
          },
          {
            "name": "层高(m)",
            "dataType": "double",
            "sourceColumn": "层高(m)"
          },
          {
            "name": "项目结算状态",
            "dataType": "string",
            "sourceColumn": "项目结算状态"
          },
          {
            "name": "经营类型",
            "dataType": "string",
            "sourceColumn": "经营类型"
          },
          {
            "name": "结构劳务分包承包模式",
            "dataType": "string",
            "sourceColumn": "结构劳务分包承包模式"
          },
          {
            "name": "发包人名称",
            "dataType": "string",
            "sourceColumn": "发包人名称"
          },
          {
            "name": "发包人性质",
            "dataType": "string",
            "sourceColumn": "发包人性质"
          },
          {
            "name": "业主联系人",
            "dataType": "string",
            "sourceColumn": "业主联系人"
          },
          {
            "name": "业主联系电话",
            "dataType": "string",
            "sourceColumn": "业主联系电话"
          },
          {
            "name": "投资来源",
            "dataType": "string",
            "sourceColumn": "投资来源"
          },
          {
            "name": "是否属于保障性住房项目",
            "dataType": "string",
            "sourceColumn": "是否属于保障性住房项目"
          },
          {
            "name": "项目所属大客户",
            "dataType": "string",
            "sourceColumn": "项目所属大客户"
          },
          {
            "name": "项目规模",
            "dataType": "string",
            "sourceColumn": "项目规模"
          },
          {
            "name": "是否内部分包",
            "dataType": "string",
            "sourceColumn": "是否内部分包"
          },
          {
            "name": "竣工责任状签订结算完成日期",
            "dataType": "dateTime",
            "sourceColumn": "竣工责任状签订结算完成日期"
          },
          {
            "name": "履约保证金形式",
            "dataType": "string",
            "sourceColumn": "履约保证金形式"
          },
          {
            "name": "履约保证金比例",
            "dataType": "string",
            "sourceColumn": "履约保证金比例"
          },
          {
            "name": "履约保证金返还时间",
            "dataType": "dateTime",
            "sourceColumn": "履约保证金返还时间"
          },
          {
            "name": "业主隶属集团公司全称",
            "dataType": "string",
            "sourceColumn": "业主隶属集团公司全称"
          },
          {
            "name": "FCBFS",
            "dataType": "string",
            "sourceColumn": "FCBFS"
          },
          {
            "name": "业主结算时间",
            "dataType": "dateTime",
            "sourceColumn": "业主结算时间"
          },
          {
            "name": "是否有投资项目公司",
            "dataType": "string",
            "sourceColumn": "是否有投资项目公司"
          },
          {
            "name": "是否投资建造项目",
            "dataType": "string",
            "sourceColumn": "是否投资建造项目"
          },
          {
            "name": "所属成本主办",
            "dataType": "string",
            "sourceColumn": "所属成本主办"
          },
          {
            "name": "单据状态",
            "dataType": "string",
            "sourceColumn": "单据状态"
          },
          {
            "name": "是否先立项",
            "dataType": "string",
            "sourceColumn": "是否先立项"
          },
          {
            "name": "中标交底ID",
            "dataType": "string",
            "sourceColumn": "中标交底ID"
          },
          {
            "name": "投标评审ID",
            "dataType": "string",
            "sourceColumn": "投标评审ID"
          },
          {
            "name": "合同工期日历天",
            "dataType": "double",
            "sourceColumn": "合同工期日历天"
          },
          {
            "name": "工程重点级别",
            "dataType": "string",
            "sourceColumn": "工程重点级别"
          },
          {
            "name": "土建自施核定收益率",
            "dataType": "double",
            "sourceColumn": "土建自施核定收益率"
          },
          {
            "name": "机电自施核定收益率",
            "dataType": "double",
            "sourceColumn": "机电自施核定收益率"
          },
          {
            "name": "综合核定收益率",
            "dataType": "double",
            "sourceColumn": "综合核定收益率"
          },
          {
            "name": "清欠责任人",
            "dataType": "string",
            "sourceColumn": "清欠责任人"
          },
          {
            "name": "责任领导",
            "dataType": "string",
            "sourceColumn": "责任领导"
          },
          {
            "name": "项目账户",
            "dataType": "string",
            "sourceColumn": "项目账户"
          },
          {
            "name": "责任部门",
            "dataType": "string",
            "sourceColumn": "责任部门"
          },
          {
            "name": "NC编码",
            "dataType": "string",
            "sourceColumn": "NC编码"
          },
          {
            "name": "NC所属账套",
            "dataType": "string",
            "sourceColumn": "NC所属账套"
          },
          {
            "name": "NC项目名称",
            "dataType": "string",
            "sourceColumn": "NC项目名称"
          },
          {
            "name": "总部联络人Code",
            "dataType": "string",
            "sourceColumn": "总部联络人Code"
          },
          {
            "name": "流程结束时间",
            "dataType": "dateTime",
            "sourceColumn": "流程结束时间"
          },
          {
            "name": "流程发起时间",
            "dataType": "dateTime",
            "sourceColumn": "流程发起时间"
          },
          {
            "name": "创建时间",
            "dataType": "dateTime",
            "sourceColumn": "创建时间"
          },
          {
            "name": "序号",
            "dataType": "double",
            "sourceColumn": "序号"
          },
          {
            "name": "承包方式",
            "dataType": "string",
            "sourceColumn": "承包方式"
          },
          {
            "name": "评审状态",
            "dataType": "string",
            "sourceColumn": "评审状态"
          },
          {
            "name": "评审状态ID",
            "dataType": "string",
            "sourceColumn": "评审状态ID"
          },
          {
            "name": "招标评审状态",
            "dataType": "string",
            "sourceColumn": "招标评审状态"
          },
          {
            "name": "提交者ID",
            "dataType": "string",
            "sourceColumn": "提交者ID"
          },
          {
            "name": "提交者",
            "dataType": "string",
            "sourceColumn": "提交者"
          },
          {
            "name": "提交者岗位ID",
            "dataType": "string",
            "sourceColumn": "提交者岗位ID"
          },
          {
            "name": "提交者岗位",
            "dataType": "string",
            "sourceColumn": "提交者岗位"
          },
          {
            "name": "提交者部门ID",
            "dataType": "string",
            "sourceColumn": "提交者部门ID"
          },
          {
            "name": "提交者部门",
            "dataType": "string",
            "sourceColumn": "提交者部门"
          },
          {
            "name": "提交者机构ID",
            "dataType": "string",
            "sourceColumn": "提交者机构ID"
          },
          {
            "name": "提交者机构",
            "dataType": "string",
            "sourceColumn": "提交者机构"
          },
          {
            "name": "组织全路径ID",
            "dataType": "string",
            "sourceColumn": "组织全路径ID"
          },
          {
            "name": "组织全路径名",
            "dataType": "string",
            "sourceColumn": "组织全路径名"
          },
          {
            "name": "最后修改人标识",
            "dataType": "string",
            "sourceColumn": "最后修改人标识"
          },
          {
            "name": "最后修改人",
            "dataType": "string",
            "sourceColumn": "最后修改人"
          },
          {
            "name": "最后修改时间",
            "dataType": "dateTime",
            "sourceColumn": "最后修改时间"
          },
          {
            "name": "经管主办人员ID",
            "dataType": "string",
            "sourceColumn": "经管主办人员ID"
          },
          {
            "name": "机电主办人员ID",
            "dataType": "string",
            "sourceColumn": "机电主办人员ID"
          },
          {
            "name": "总部联络人ID",
            "dataType": "string",
            "sourceColumn": "总部联络人ID"
          },
          {
            "name": "印花税计税方式",
            "dataType": "string",
            "sourceColumn": "印花税计税方式"
          },
          {
            "name": "后延期结束日期",
            "dataType": "dateTime",
            "sourceColumn": "后延期结束日期"
          },
          {
            "name": "误餐补助系数",
            "dataType": "double",
            "sourceColumn": "误餐补助系数"
          },
          {
            "name": "公司到项目公里数",
            "dataType": "double",
            "sourceColumn": "公司到项目公里数"
          },
          {
            "name": "投资项目运作模式",
            "dataType": "string",
            "sourceColumn": "投资项目运作模式"
          },
          {
            "name": "项目税率",
            "dataType": "double",
            "sourceColumn": "项目税率"
          },
          {
            "name": "直管机构编码",
            "dataType": "string",
            "sourceColumn": "直管机构编码"
          },
          {
            "name": "项目类型",
            "dataType": "string",
            "sourceColumn": "项目类型"
          },
          {
            "name": "直管机构",
            "dataType": "string",
            "sourceColumn": "直管机构"
          },
          {
            "name": "FZHIGUANJGXGBM",
            "dataType": "string",
            "sourceColumn": "FZHIGUANJGXGBM"
          },
          {
            "name": "项目备案序号",
            "dataType": "string",
            "sourceColumn": "项目备案序号"
          },
          {
            "name": "是否为进度款后延支付项目（工程",
            "dataType": "string",
            "sourceColumn": "是否为进度款后延支付项目（工程"
          },
          {
            "name": "NC项目类别编码",
            "dataType": "string",
            "sourceColumn": "NC项目类别编码"
          },
          {
            "name": "NC项目类别",
            "dataType": "string",
            "sourceColumn": "NC项目类别"
          },
          {
            "name": "土建甲指核定收益率",
            "dataType": "double",
            "sourceColumn": "土建甲指核定收益率"
          },
          {
            "name": "机电甲指核定收益率",
            "dataType": "double",
            "sourceColumn": "机电甲指核定收益率"
          },
          {
            "name": "投资收益率",
            "dataType": "double",
            "sourceColumn": "投资收益率"
          },
          {
            "name": "投资项目公司编码",
            "dataType": "string",
            "sourceColumn": "投资项目公司编码"
          },
          {
            "name": "投资项目公司",
            "dataType": "string",
            "sourceColumn": "投资项目公司"
          },
          {
            "name": "是否无业务项目",
            "dataType": "string",
            "sourceColumn": "是否无业务项目"
          },
          {
            "name": "厂房事业部",
            "dataType": "string",
            "sourceColumn": "厂房事业部"
          },
          {
            "name": "所属总监团队",
            "dataType": "string",
            "sourceColumn": "所属总监团队"
          },
          {
            "name": "项目财务状态",
            "dataType": "string",
            "sourceColumn": "项目财务状态"
          },
          {
            "name": "责任书签订日期",
            "dataType": "dateTime",
            "sourceColumn": "责任书签订日期"
          },
          {
            "name": "fYWBK",
            "dataType": "string",
            "sourceColumn": "fYWBK"
          },
          {
            "name": "投标管理部门",
            "dataType": "string",
            "sourceColumn": "投标管理部门"
          },
          {
            "name": "商务完工时间",
            "dataType": "dateTime",
            "sourceColumn": "商务完工时间"
          },
          {
            "name": "是否已迁移至人力资源",
            "dataType": "string",
            "sourceColumn": "是否已迁移至人力资源"
          },
          {
            "name": "人力资源业务流程ID",
            "dataType": "string",
            "sourceColumn": "人力资源业务流程ID"
          },
          {
            "name": "股份财务一体化组织机构名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化组织机构名称"
          },
          {
            "name": "股份财务一体化项目名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目名称"
          },
          {
            "name": "股份财务一体化项目编码",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目编码"
          },
          {
            "name": "防水保修年限",
            "dataType": "dateTime",
            "sourceColumn": "防水保修年限"
          },
          {
            "name": "机电及其他保修年限",
            "dataType": "dateTime",
            "sourceColumn": "机电及其他保修年限"
          },
          {
            "name": "是否提交保修情况免报申请",
            "dataType": "string",
            "sourceColumn": "是否提交保修情况免报申请"
          },
          {
            "name": "保修金退还的约定",
            "dataType": "string",
            "sourceColumn": "保修金退还的约定"
          },
          {
            "name": "保修金是否回收完成",
            "dataType": "string",
            "sourceColumn": "保修金是否回收完成"
          },
          {
            "name": "项目是否封存（财务）",
            "dataType": "string",
            "sourceColumn": "项目是否封存（财务）"
          },
          {
            "name": "股份一体化利润中心编码",
            "dataType": "string",
            "sourceColumn": "股份一体化利润中心编码"
          },
          {
            "name": "FSFFXXM",
            "dataType": "string",
            "sourceColumn": "FSFFXXM"
          },
          {
            "name": "是否开立监管账户",
            "dataType": "string",
            "sourceColumn": "是否开立监管账户"
          },
          {
            "name": "云筑劳务项目名称",
            "dataType": "string",
            "sourceColumn": "云筑劳务项目名称"
          },
          {
            "name": "云筑劳务项目编号",
            "dataType": "string",
            "sourceColumn": "云筑劳务项目编号"
          },
          {
            "name": "云筑劳务密钥",
            "dataType": "string",
            "sourceColumn": "云筑劳务密钥"
          },
          {
            "name": "初始合同额（元）",
            "dataType": "double",
            "sourceColumn": "初始合同额（元）"
          },
          {
            "name": "劳务实名制状态",
            "dataType": "string",
            "sourceColumn": "劳务实名制状态"
          },
          {
            "name": "基础设施细分",
            "dataType": "string",
            "sourceColumn": "基础设施细分"
          },
          {
            "name": "装配式建筑",
            "dataType": "string",
            "sourceColumn": "装配式建筑"
          },
          {
            "name": "装配率（%）",
            "dataType": "double",
            "sourceColumn": "装配率（%）"
          },
          {
            "name": "里程（KM）",
            "dataType": "double",
            "sourceColumn": "里程（KM）"
          },
          {
            "name": "履约直管机构",
            "dataType": "string",
            "sourceColumn": "履约直管机构"
          },
          {
            "name": "履约直管机构编码",
            "dataType": "string",
            "sourceColumn": "履约直管机构编码"
          },
          {
            "name": "FCHENGSHIGONGSI",
            "dataType": "string",
            "sourceColumn": "FCHENGSHIGONGSI"
          },
          {
            "name": "FJZDBZXGC",
            "dataType": "string",
            "sourceColumn": "FJZDBZXGC"
          },
          {
            "name": "财务评审状态",
            "dataType": "string",
            "sourceColumn": "财务评审状态"
          },
          {
            "name": "FXIANGMUDIQU",
            "dataType": "string",
            "sourceColumn": "FXIANGMUDIQU"
          },
          {
            "name": "FHTJJHB",
            "dataType": "string",
            "sourceColumn": "FHTJJHB"
          },
          {
            "name": "FZBHTJ_JJHB",
            "dataType": "double",
            "sourceColumn": "FZBHTJ_JJHB"
          },
          {
            "name": "FZSBF_JJHB",
            "dataType": "double",
            "sourceColumn": "FZSBF_JJHB"
          },
          {
            "name": "FDDJJHBDRMBHL",
            "dataType": "double",
            "sourceColumn": "FDDJJHBDRMBHL"
          },
          {
            "name": "FMYDRMBHL",
            "dataType": "double",
            "sourceColumn": "FMYDRMBHL"
          },
          {
            "name": "FZBHTJ_WMY",
            "dataType": "double",
            "sourceColumn": "FZBHTJ_WMY"
          },
          {
            "name": "FZBZSBF_WMY",
            "dataType": "double",
            "sourceColumn": "FZBZSBF_WMY"
          },
          {
            "name": "FZHONNGBIAOHETO",
            "dataType": "double",
            "sourceColumn": "FZHONNGBIAOHETO"
          },
          {
            "name": "FZBZSBF",
            "dataType": "double",
            "sourceColumn": "FZBZSBF"
          },
          {
            "name": "FXMZBJD",
            "dataType": "double",
            "sourceColumn": "FXMZBJD"
          },
          {
            "name": "FXMZBWD",
            "dataType": "double",
            "sourceColumn": "FXMZBWD"
          },
          {
            "name": "是否上线目标成本",
            "dataType": "string",
            "sourceColumn": "是否上线目标成本"
          },
          {
            "name": "计价模式",
            "dataType": "string",
            "sourceColumn": "计价模式"
          },
          {
            "name": "清单模式",
            "dataType": "string",
            "sourceColumn": "清单模式"
          },
          {
            "name": "海外项目平台公司",
            "dataType": "string",
            "sourceColumn": "海外项目平台公司"
          },
          {
            "name": "海外项目平台公司编码",
            "dataType": "string",
            "sourceColumn": "海外项目平台公司编码"
          },
          {
            "name": "海外项目平台公司id",
            "dataType": "string",
            "sourceColumn": "海外项目平台公司id"
          },
          {
            "name": "海外项目平台公司fid",
            "dataType": "string",
            "sourceColumn": "海外项目平台公司fid"
          },
          {
            "name": "责任体",
            "dataType": "string",
            "sourceColumn": "责任体"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    MD = 源{[Schema=\"MD\"]}[Data],",
                "    MD_XIANGMUXINXI = MD{[Name=\"MD_XIANGMUXINXI\"]}[Data],",
                "    重命名的列 = Table.Buffer(Table.RenameColumns(MD_XIANGMUXINXI,fx_List_生成字段更名列表(\"MD\",\"MD_XIANGMUXINXI\"))),",
                "    自定义1 = Table.AddColumn(重命名的列, \"责任体\", each if [京内外分布] = \"国际\" then \"海外\" else if [厂房事业部] <> null then [厂房事业部] else if [直管机构] <> \"公司\" then [直管机构] else \"公司直营\",type text)",
                "in",
                "    自定义1"
              ]
            }
          }
        ]
      },
      {
        "name": "日历",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Date]"
          },
          {
            "type": "calculated",
            "name": "年月",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT('日历'[Date],\"yyyy-MM\")"
          },
          {
            "type": "calculated",
            "name": "年",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "YEAR('日历'[Date])"
          },
          {
            "type": "calculated",
            "name": "月",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "MONTH('日历'[Date])"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "CALENDAR(\"2005-1-1\",TODAY())"
            }
          }
        ]
      },
      {
        "name": "专项物资合同表",
        "columns": [
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "合同名称",
            "dataType": "string",
            "sourceColumn": "合同名称"
          },
          {
            "name": "合同协议号",
            "dataType": "string",
            "sourceColumn": "合同协议号"
          },
          {
            "name": "合同类型",
            "dataType": "string",
            "sourceColumn": "合同类型"
          },
          {
            "name": "待签合同编号",
            "dataType": "string",
            "sourceColumn": "待签合同编号"
          },
          {
            "name": "待签合同名称",
            "dataType": "string",
            "sourceColumn": "待签合同名称"
          },
          {
            "name": "商务科目Code",
            "dataType": "string",
            "sourceColumn": "商务科目Code"
          },
          {
            "name": "商务科目",
            "dataType": "string",
            "sourceColumn": "商务科目"
          },
          {
            "name": "商务科目全名称",
            "dataType": "string",
            "sourceColumn": "商务科目全名称"
          },
          {
            "name": "财务科目编码",
            "dataType": "string",
            "sourceColumn": "财务科目编码"
          },
          {
            "name": "财务科目名称",
            "dataType": "string",
            "sourceColumn": "财务科目名称"
          },
          {
            "name": "财务科目全路径名称",
            "dataType": "string",
            "sourceColumn": "财务科目全路径名称"
          },
          {
            "name": "施工专业",
            "dataType": "string",
            "sourceColumn": "施工专业"
          },
          {
            "name": "纳税人性质",
            "dataType": "string",
            "sourceColumn": "纳税人性质"
          },
          {
            "name": "增值税率",
            "dataType": "double",
            "sourceColumn": "增值税率"
          },
          {
            "name": "是否非常规分供合同",
            "dataType": "string",
            "sourceColumn": "是否非常规分供合同"
          },
          {
            "name": "计划单号ID",
            "dataType": "string",
            "sourceColumn": "计划单号ID"
          },
          {
            "name": "计划单号编码",
            "dataType": "string",
            "sourceColumn": "计划单号编码"
          },
          {
            "name": "计划单号",
            "dataType": "string",
            "sourceColumn": "计划单号"
          },
          {
            "name": "合同约定的收票时点",
            "dataType": "string",
            "sourceColumn": "合同约定的收票时点"
          },
          {
            "name": "是否一局协同平台准入",
            "dataType": "string",
            "sourceColumn": "是否一局协同平台准入"
          },
          {
            "name": "供方编码",
            "dataType": "string",
            "sourceColumn": "供方编码"
          },
          {
            "name": "供方名称",
            "dataType": "string",
            "sourceColumn": "供方名称"
          },
          {
            "name": "供方联系人",
            "dataType": "string",
            "sourceColumn": "供方联系人"
          },
          {
            "name": "局分供类别",
            "dataType": "string",
            "sourceColumn": "局分供类别"
          },
          {
            "name": "合作内容",
            "dataType": "string",
            "sourceColumn": "合作内容"
          },
          {
            "name": "合同内容描述",
            "dataType": "string",
            "sourceColumn": "合同内容描述"
          },
          {
            "name": "此物资是否包含在分包合同内",
            "dataType": "string",
            "sourceColumn": "此物资是否包含在分包合同内"
          },
          {
            "name": "签订时间",
            "dataType": "dateTime",
            "sourceColumn": "签订时间"
          },
          {
            "name": "定价原则",
            "dataType": "string",
            "sourceColumn": "定价原则"
          },
          {
            "name": "含税合同价",
            "dataType": "double",
            "sourceColumn": "含税合同价"
          },
          {
            "name": "不含税合同价款",
            "dataType": "double",
            "sourceColumn": "不含税合同价款"
          },
          {
            "name": "税金",
            "dataType": "double",
            "sourceColumn": "税金"
          },
          {
            "name": "超过合约规划金额说明",
            "dataType": "string",
            "sourceColumn": "超过合约规划金额说明"
          },
          {
            "name": "其他说明",
            "dataType": "string",
            "sourceColumn": "其他说明"
          },
          {
            "name": "运输商名称",
            "dataType": "string",
            "sourceColumn": "运输商名称"
          },
          {
            "name": "填报日期",
            "dataType": "dateTime",
            "sourceColumn": "填报日期"
          },
          {
            "name": "是否已结算",
            "dataType": "string",
            "sourceColumn": "是否已结算"
          },
          {
            "name": "含税结算金额",
            "dataType": "double",
            "sourceColumn": "含税结算金额"
          },
          {
            "name": "结算考核状态",
            "dataType": "string",
            "sourceColumn": "结算考核状态"
          },
          {
            "name": "结算考核完成时间",
            "dataType": "dateTime",
            "sourceColumn": "结算考核完成时间"
          },
          {
            "name": "评审状态ID",
            "dataType": "string",
            "sourceColumn": "评审状态ID"
          },
          {
            "name": "评审状态",
            "dataType": "string",
            "sourceColumn": "评审状态"
          },
          {
            "name": "合同评审类型",
            "dataType": "string",
            "sourceColumn": "合同评审类型"
          },
          {
            "name": "业务大类",
            "dataType": "string",
            "sourceColumn": "业务大类"
          },
          {
            "name": "业务小类",
            "dataType": "string",
            "sourceColumn": "业务小类"
          },
          {
            "name": "提交者",
            "dataType": "string",
            "sourceColumn": "提交者"
          },
          {
            "name": "提交者岗位",
            "dataType": "string",
            "sourceColumn": "提交者岗位"
          },
          {
            "name": "提交者部门",
            "dataType": "string",
            "sourceColumn": "提交者部门"
          },
          {
            "name": "提交者机构",
            "dataType": "string",
            "sourceColumn": "提交者机构"
          },
          {
            "name": "组织全路径名",
            "dataType": "string",
            "sourceColumn": "组织全路径名"
          },
          {
            "name": "创建时间",
            "dataType": "dateTime",
            "sourceColumn": "创建时间"
          },
          {
            "name": "最后修改人",
            "dataType": "string",
            "sourceColumn": "最后修改人"
          },
          {
            "name": "最后修改时间",
            "dataType": "dateTime",
            "sourceColumn": "最后修改时间"
          },
          {
            "name": "预付款金额",
            "dataType": "double",
            "sourceColumn": "预付款金额"
          },
          {
            "name": "预付款担保形式",
            "dataType": "string",
            "sourceColumn": "预付款担保形式"
          },
          {
            "name": "预付款担保形式编码",
            "dataType": "string",
            "sourceColumn": "预付款担保形式编码"
          },
          {
            "name": "股份财务一体化项目名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目名称"
          },
          {
            "name": "对方负责人",
            "dataType": "string",
            "sourceColumn": "对方负责人"
          },
          {
            "name": "司法保全金额(元)",
            "dataType": "double",
            "sourceColumn": "司法保全金额(元)"
          },
          {
            "name": "收款单位开户行名称",
            "dataType": "string",
            "sourceColumn": "收款单位开户行名称"
          },
          {
            "name": "收款单位银行账号",
            "dataType": "string",
            "sourceColumn": "收款单位银行账号"
          },
          {
            "name": "对方签约单位",
            "dataType": "string",
            "sourceColumn": "对方签约单位"
          },
          {
            "name": "股份财务一体化项目编码",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目编码"
          },
          {
            "name": "股份财务一体化组织机构名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化组织机构名称"
          },
          {
            "name": "是否云筑MRO框架协议",
            "dataType": "string",
            "sourceColumn": "是否云筑MRO框架协议"
          },
          {
            "name": "对应云筑MRO框架协议编号",
            "dataType": "string",
            "sourceColumn": "对应云筑MRO框架协议编号"
          },
          {
            "name": "对应云筑MRO框架协议名称",
            "dataType": "string",
            "sourceColumn": "对应云筑MRO框架协议名称"
          },
          {
            "name": "是否已做三方抵债",
            "dataType": "string",
            "sourceColumn": "是否已做三方抵债"
          },
          {
            "name": "标准合同是否满额签约",
            "dataType": "string",
            "sourceColumn": "标准合同是否满额签约"
          },
          {
            "name": "是否已更新标准合同",
            "dataType": "string",
            "sourceColumn": "是否已更新标准合同"
          },
          {
            "name": "是否合同外签约",
            "dataType": "string",
            "sourceColumn": "是否合同外签约"
          },
          {
            "name": "国内/外",
            "dataType": "string",
            "sourceColumn": "国内/外"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = 专项物资合同表",
                "in",
                "    源"
              ]
            }
          }
        ]
      },
      {
        "name": "专项物资进场",
        "columns": [
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "价税合计",
            "dataType": "double",
            "sourceColumn": "价税合计"
          },
          {
            "name": "金额",
            "dataType": "double",
            "sourceColumn": "金额"
          },
          {
            "name": "税金",
            "dataType": "double",
            "sourceColumn": "税金"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_WUZIJINCHANG_ZB = GSPM{[Name=\"GSPM_WUZIJINCHANG_ZB\"]}[Data],",
                "    筛选的行 = Table.SelectRows(GSPM_WUZIJINCHANG_ZB, each ([FYEWUXIAOLEI] = \"专项进场\") and ([FDANJUZHUANGTAI] = \"已完成\")),",
                "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FNIAN\", \"FYUE\", \"FXIANGMUMINGCHENG\", \"FHETONGBIANHAO\", \"FHANSHUIJINCHANGJINE\", \"FBUHANSHUIJINCHANGJINE\", \"FSHUIJIN\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FHANSHUIJINCHANGJINE\", \"价税合计\"}, {\"FBUHANSHUIJINCHANGJINE\", \"金额\"}, {\"FSHUIJIN\", \"税金\"}}),",
                "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1),type date)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ]
      },
      {
        "name": "专项物资退场",
        "columns": [
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "金额",
            "dataType": "double",
            "sourceColumn": "金额"
          },
          {
            "name": "税金",
            "dataType": "double",
            "sourceColumn": "税金"
          },
          {
            "name": "价税合计",
            "dataType": "double",
            "sourceColumn": "价税合计"
          },
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "单据状态",
            "dataType": "string",
            "sourceColumn": "单据状态"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_WUZITUICHANG_CB = GSPM{[Name=\"GSPM_WUZITUICHANG_CB\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(GSPM_WUZITUICHANG_CB,{\"FTUICHANGDANID\", \"FHETONGBIANHAO\", \"FJINE\", \"FSHUIE\", \"FJIASHUIHEJI\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FTUICHANGDANID\", \"退场单\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FJINE\", \"金额\"}, {\"FSHUIE\", \"税金\"}, {\"FJIASHUIHEJI\", \"价税合计\"}}),",
                "    合并的查询 = Table.NestedJoin(重命名的列,{\"退场单\"},专项物资退场主表,{\"FID\"},\"专项物资退场主表\",JoinKind.Inner),",
                "    #\"展开的“专项物资退场主表”\" = Table.ExpandTableColumn(合并的查询, \"专项物资退场主表\", {\"年\", \"月\", \"单据状态\"}, {\"年\", \"月\", \"单据状态\"}),",
                "    删除的列 = Table.RemoveColumns(#\"展开的“专项物资退场主表”\",{\"退场单\"}),",
                "    已添加自定义 = Table.AddColumn(删除的列, \"日期\", each #date([年],[月],1),type date)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ]
      },
      {
        "name": "专项物资结算",
        "columns": [
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "含税结算额",
            "dataType": "double",
            "sourceColumn": "含税结算额"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": "专项物资结算"
            }
          }
        ]
      },
      {
        "name": "专项物资付款表",
        "columns": [
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "本期付款",
            "dataType": "double",
            "sourceColumn": "本期付款"
          },
          {
            "name": "单据状态",
            "dataType": "string",
            "sourceColumn": "单据状态"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_DANXIANGWUZIFUKUAN = GSPM{[Name=\"GSPM_DANXIANGWUZIFUKUAN\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(GSPM_DANXIANGWUZIFUKUAN,{\"FNIAN\", \"FYUE\", \"FHETONGBIANHAO\", \"FBENQISHIJIFUKUAN\", \"FPINGSHENZHUANGTAI2\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FBENQISHIJIFUKUAN\", \"本期付款\"}, {\"FPINGSHENZHUANGTAI2\", \"单据状态\"}}),",
                "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1)),",
                "    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{\"日期\", type datetime}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ]
      },
      {
        "name": "租赁合同表",
        "columns": [
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "合同名称",
            "dataType": "string",
            "sourceColumn": "合同名称"
          },
          {
            "name": "合同协议号",
            "dataType": "string",
            "sourceColumn": "合同协议号"
          },
          {
            "name": "合同类型",
            "dataType": "string",
            "sourceColumn": "合同类型"
          },
          {
            "name": "待签合同编号",
            "dataType": "string",
            "sourceColumn": "待签合同编号"
          },
          {
            "name": "待签合同名称",
            "dataType": "string",
            "sourceColumn": "待签合同名称"
          },
          {
            "name": "商务科目Code",
            "dataType": "string",
            "sourceColumn": "商务科目Code"
          },
          {
            "name": "商务科目",
            "dataType": "string",
            "sourceColumn": "商务科目"
          },
          {
            "name": "商务科目全名称",
            "dataType": "string",
            "sourceColumn": "商务科目全名称"
          },
          {
            "name": "财务科目编码",
            "dataType": "string",
            "sourceColumn": "财务科目编码"
          },
          {
            "name": "财务科目名称",
            "dataType": "string",
            "sourceColumn": "财务科目名称"
          },
          {
            "name": "财务科目全路径名称",
            "dataType": "string",
            "sourceColumn": "财务科目全路径名称"
          },
          {
            "name": "施工专业",
            "dataType": "string",
            "sourceColumn": "施工专业"
          },
          {
            "name": "纳税人性质",
            "dataType": "string",
            "sourceColumn": "纳税人性质"
          },
          {
            "name": "增值税率",
            "dataType": "double",
            "sourceColumn": "增值税率"
          },
          {
            "name": "是否非常规分供合同",
            "dataType": "string",
            "sourceColumn": "是否非常规分供合同"
          },
          {
            "name": "计划单号ID",
            "dataType": "string",
            "sourceColumn": "计划单号ID"
          },
          {
            "name": "计划单号编码",
            "dataType": "string",
            "sourceColumn": "计划单号编码"
          },
          {
            "name": "计划单号",
            "dataType": "string",
            "sourceColumn": "计划单号"
          },
          {
            "name": "合同约定的收票时点",
            "dataType": "string",
            "sourceColumn": "合同约定的收票时点"
          },
          {
            "name": "是否一局协同平台准入",
            "dataType": "string",
            "sourceColumn": "是否一局协同平台准入"
          },
          {
            "name": "供方编码",
            "dataType": "string",
            "sourceColumn": "供方编码"
          },
          {
            "name": "供方名称",
            "dataType": "string",
            "sourceColumn": "供方名称"
          },
          {
            "name": "供方联系人",
            "dataType": "string",
            "sourceColumn": "供方联系人"
          },
          {
            "name": "局分供类别",
            "dataType": "string",
            "sourceColumn": "局分供类别"
          },
          {
            "name": "合作内容",
            "dataType": "string",
            "sourceColumn": "合作内容"
          },
          {
            "name": "合同内容描述",
            "dataType": "string",
            "sourceColumn": "合同内容描述"
          },
          {
            "name": "此物资是否包含在分包合同内",
            "dataType": "string",
            "sourceColumn": "此物资是否包含在分包合同内"
          },
          {
            "name": "签订时间",
            "dataType": "dateTime",
            "sourceColumn": "签订时间"
          },
          {
            "name": "定价原则",
            "dataType": "string",
            "sourceColumn": "定价原则"
          },
          {
            "name": "含税合同价",
            "dataType": "double",
            "sourceColumn": "含税合同价"
          },
          {
            "name": "不含税合同价款",
            "dataType": "double",
            "sourceColumn": "不含税合同价款"
          },
          {
            "name": "税金",
            "dataType": "double",
            "sourceColumn": "税金"
          },
          {
            "name": "超过合约规划金额说明",
            "dataType": "string",
            "sourceColumn": "超过合约规划金额说明"
          },
          {
            "name": "其他说明",
            "dataType": "string",
            "sourceColumn": "其他说明"
          },
          {
            "name": "运输商名称",
            "dataType": "string",
            "sourceColumn": "运输商名称"
          },
          {
            "name": "填报日期",
            "dataType": "dateTime",
            "sourceColumn": "填报日期"
          },
          {
            "name": "是否已结算",
            "dataType": "string",
            "sourceColumn": "是否已结算"
          },
          {
            "name": "含税结算金额",
            "dataType": "double",
            "sourceColumn": "含税结算金额"
          },
          {
            "name": "结算考核状态",
            "dataType": "string",
            "sourceColumn": "结算考核状态"
          },
          {
            "name": "结算考核完成时间",
            "dataType": "dateTime",
            "sourceColumn": "结算考核完成时间"
          },
          {
            "name": "评审状态ID",
            "dataType": "string",
            "sourceColumn": "评审状态ID"
          },
          {
            "name": "评审状态",
            "dataType": "string",
            "sourceColumn": "评审状态"
          },
          {
            "name": "合同评审类型",
            "dataType": "string",
            "sourceColumn": "合同评审类型"
          },
          {
            "name": "业务大类",
            "dataType": "string",
            "sourceColumn": "业务大类"
          },
          {
            "name": "业务小类",
            "dataType": "string",
            "sourceColumn": "业务小类"
          },
          {
            "name": "提交者",
            "dataType": "string",
            "sourceColumn": "提交者"
          },
          {
            "name": "提交者岗位",
            "dataType": "string",
            "sourceColumn": "提交者岗位"
          },
          {
            "name": "提交者部门",
            "dataType": "string",
            "sourceColumn": "提交者部门"
          },
          {
            "name": "提交者机构",
            "dataType": "string",
            "sourceColumn": "提交者机构"
          },
          {
            "name": "组织全路径名",
            "dataType": "string",
            "sourceColumn": "组织全路径名"
          },
          {
            "name": "创建时间",
            "dataType": "dateTime",
            "sourceColumn": "创建时间"
          },
          {
            "name": "最后修改人",
            "dataType": "string",
            "sourceColumn": "最后修改人"
          },
          {
            "name": "最后修改时间",
            "dataType": "dateTime",
            "sourceColumn": "最后修改时间"
          },
          {
            "name": "预付款金额",
            "dataType": "double",
            "sourceColumn": "预付款金额"
          },
          {
            "name": "预付款担保形式",
            "dataType": "string",
            "sourceColumn": "预付款担保形式"
          },
          {
            "name": "预付款担保形式编码",
            "dataType": "string",
            "sourceColumn": "预付款担保形式编码"
          },
          {
            "name": "股份财务一体化项目名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目名称"
          },
          {
            "name": "对方负责人",
            "dataType": "string",
            "sourceColumn": "对方负责人"
          },
          {
            "name": "司法保全金额(元)",
            "dataType": "double",
            "sourceColumn": "司法保全金额(元)"
          },
          {
            "name": "收款单位开户行名称",
            "dataType": "string",
            "sourceColumn": "收款单位开户行名称"
          },
          {
            "name": "收款单位银行账号",
            "dataType": "string",
            "sourceColumn": "收款单位银行账号"
          },
          {
            "name": "对方签约单位",
            "dataType": "string",
            "sourceColumn": "对方签约单位"
          },
          {
            "name": "股份财务一体化项目编码",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目编码"
          },
          {
            "name": "股份财务一体化组织机构名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化组织机构名称"
          },
          {
            "name": "是否云筑MRO框架协议",
            "dataType": "string",
            "sourceColumn": "是否云筑MRO框架协议"
          },
          {
            "name": "对应云筑MRO框架协议编号",
            "dataType": "string",
            "sourceColumn": "对应云筑MRO框架协议编号"
          },
          {
            "name": "对应云筑MRO框架协议名称",
            "dataType": "string",
            "sourceColumn": "对应云筑MRO框架协议名称"
          },
          {
            "name": "是否已做三方抵债",
            "dataType": "string",
            "sourceColumn": "是否已做三方抵债"
          },
          {
            "name": "标准合同是否满额签约",
            "dataType": "string",
            "sourceColumn": "标准合同是否满额签约"
          },
          {
            "name": "是否已更新标准合同",
            "dataType": "string",
            "sourceColumn": "是否已更新标准合同"
          },
          {
            "name": "是否合同外签约",
            "dataType": "string",
            "sourceColumn": "是否合同外签约"
          },
          {
            "name": "国内/外",
            "dataType": "string",
            "sourceColumn": "国内/外"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_WUZIHETONGXINXI = GSPM{[Name=\"GSPM_WUZIHETONGXINXI\"]}[Data],",
                "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGXINXI, each ([FHETONGPINGSHENTYPE] = \"周转材料租赁合同\")),",
                "    重命名的列 = Table.RenameColumns(筛选的行,fx_List_生成字段更名列表(\"GSPM\",\"GSPM_WUZIHETONGXINXI\")),",
                "    删除的列 = Table.RemoveColumns(重命名的列,{\"FID\", \"版本\", \"项目ID\", \"项目编号\", \"合同类型ID\", \"合同类型Code\", \"待签合同ID\", \"商务科目ID\", \"商务科目全路径ID\", \"商务科目全路径编码\", \"商务科目级次码\", \"财务科目ID\", \"财务科目全路径ID\", \"财务科目全路径编码\", \"财务科目级次码\", \"施工专业ID\", \"施工专业编码\", \"增值税发票类别ID\", \"增值税发票类别Code\", \"增值税发票类别\", \"供方ID\", \"供方类别\", \"局分供类别ID\", \"局分供类别Code\", \"定价原则ID\", \"定价原则Code\", \"填报人ID\", \"对应评审合同ID\", \"提交者ID\", \"提交者岗位ID\", \"提交者部门ID\", \"提交者机构ID\", \"组织全路径ID\", \"最后修改人标识\", \"一体化合同账户\", \"密码\"}),",
                "    提取的日期 = Table.TransformColumns(删除的列,{{\"签订时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            }
          }
        ]
      },
      {
        "name": "租赁物资报量表",
        "columns": [
          {
            "name": "FID",
            "dataType": "string",
            "sourceColumn": "FID"
          },
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "单据状态",
            "dataType": "string",
            "sourceColumn": "单据状态"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "报量金额",
            "dataType": "double",
            "sourceColumn": "报量金额"
          },
          {
            "name": "供方名称",
            "dataType": "string",
            "sourceColumn": "供方名称"
          },
          {
            "name": "报量税额",
            "dataType": "double",
            "sourceColumn": "报量税额"
          },
          {
            "name": "报量价税合计",
            "dataType": "double",
            "sourceColumn": "报量价税合计"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_ZZCAILIAOZLDQBL_ZB = GSPM{[Name=\"GSPM_ZZCAILIAOZLDQBL_ZB\"]}[Data],",
                "    筛选的行 = Table.SelectRows(GSPM_ZZCAILIAOZLDQBL_ZB, each ([FDANJUZHUANGTAI] = \"已完成\")),",
                "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FNIAN\", \"FYUE\", \"FXIANGMUBIANMA\", \"FXIANGMUMINGCHENG\", \"FDANJUZHUANGTAI\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FDANJUZHUANGTAI\", \"单据状态\"}, {\"FXIANGMUBIANMA\", \"项目编码\"}}),",
                "    合并的查询 = Table.NestedJoin(重命名的列, {\"FID\"}, 租赁物资报量从表, {\"FBAOLIANGID\"}, \"租赁物资报量从表\", JoinKind.Inner),",
                "    #\"展开的“租赁物资报量从表”\" = Table.ExpandTableColumn(合并的查询, \"租赁物资报量从表\", {\"合同编号\", \"报量金额\", \"供方名称\", \"报量税额\", \"报量价税合计\"}, {\"合同编号\", \"报量金额\", \"供方名称\", \"报量税额\", \"报量价税合计\"}),",
                "    已添加自定义 = Table.AddColumn(#\"展开的“租赁物资报量从表”\", \"日期\", each #date([年],[月],1),type date)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ]
      },
      {
        "name": "租赁物资结算",
        "columns": [
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "含税结算额",
            "dataType": "double",
            "sourceColumn": "含税结算额"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = 专项物资结算",
                "in",
                "    源"
              ]
            }
          }
        ]
      },
      {
        "name": "租赁物资付款表",
        "columns": [
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "金额",
            "dataType": "double",
            "sourceColumn": "金额"
          },
          {
            "name": "单据状态",
            "dataType": "string",
            "sourceColumn": "单据状态"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_ZZCAILIAOZULINAFK = GSPM{[Name=\"GSPM_ZZCAILIAOZULINAFK\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(GSPM_ZZCAILIAOZULINAFK,{\"FNIAN\", \"FYUE\", \"FHETONGBIANHAO\", \"FBENQISHIJIFUKUAN\", \"FPINGSHENZHUANGTAI2\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FBENQISHIJIFUKUAN\", \"金额\"}, {\"FPINGSHENZHUANGTAI2\", \"单据状态\"}}),",
                "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1),type date)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ]
      },
      {
        "name": "度量值表",
        "columns": [
          {
            "name": "列 1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "列 1"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#\"列 1\" = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"列 1\", type text}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【分包付款_在途】",
            "expression": "CALCULATE(SUM('分包付款主表'[本期实际付款]),'分包付款主表'[单据状态]=\"总部处理中\")",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【分包付款含在途】",
            "expression": " [【分包付款_在途】]+[【分包实际付款】]",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【分包付款差额】",
            "expression": " SUMX(KEEPFILTERS(values('分包合同表'[合同编号])),var a=[【分包含税结算额】] return IF(a>0,a-[【分包实际付款】],[【报量价税合计】]-[【分包实际付款】]))",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【分包合同价税合计】",
            "expression": "SUM('分包合同额表'[含税合同总价])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【分包合同税额】",
            "expression": "SUM('分包合同额表'[税金])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【分包合同金额】",
            "expression": "SUM('分包合同额表'[不含税合同总价])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【分包含税结算额】",
            "expression": " var a=SUM('分包结算'[含税结算额]) return IF(ISFILTERED('日历'[年月]),BLANK(),a)",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【分包实际付款】",
            "expression": " CALCULATE(SUM('分包付款主表'[本期实际付款]),'分包付款主表'[单据状态]=\"已完成\")",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【报量价税合计】",
            "expression": "SUM('分包报量表'[报量价税合计])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【报量税金】",
            "expression": "SUM('分包报量表'[报量税额])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【报量金额】",
            "expression": " SUM('分包报量表'[报量金额])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【减报量价税合计】",
            "expression": "SUM('分包减报量'[减报量价税合计])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【减报量税金】",
            "expression": " SUM('分包减报量'[减报量税额])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【减报量金额】",
            "expression": "SUM('分包减报量'[减报量金额])",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【有效报量价税合计】",
            "expression": " [【减报量价税合计】]+[【报量价税合计】]",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【有效报量税金】",
            "expression": "[【减报量税金】]+[【报量税金】]",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【有效报量金额】",
            "expression": "[【减报量金额】]+[【报量金额】]",
            "formatString": "#,0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【进场价税合计】",
            "expression": " SUM('专项物资进场'[价税合计])",
            "displayFolder": "物资"
          },
          {
            "name": "【进场税金】",
            "expression": " SUM('专项物资进场'[税金])",
            "displayFolder": "物资"
          },
          {
            "name": "【进场金额】",
            "expression": " SUM('专项物资进场'[金额])",
            "displayFolder": "物资"
          },
          {
            "name": "【退场价税合计】",
            "expression": " SUM('专项物资退场'[价税合计])",
            "displayFolder": "物资"
          },
          {
            "name": "【退场税金】",
            "expression": " SUM('专项物资退场'[税金])",
            "displayFolder": "物资"
          },
          {
            "name": "【退场金额】",
            "expression": " SUM('专项物资退场'[金额])",
            "displayFolder": "物资"
          },
          {
            "name": "【物资合同价税合计】",
            "expression": "SUM('专项物资合同额表'[含税合同价])",
            "displayFolder": "物资"
          },
          {
            "name": "【物资合同税额】",
            "expression": "SUM('专项物资合同额表'[税金])",
            "displayFolder": "物资"
          },
          {
            "name": "【物资合同额】",
            "expression": "SUM('专项物资合同额表'[不含税合同价款])",
            "displayFolder": "物资"
          },
          {
            "name": "【物资实际付款】",
            "expression": " CALCULATE(SUM('专项物资付款表'[本期付款]),'专项物资付款表'[单据状态]=\"已完成\")",
            "displayFolder": "物资"
          },
          {
            "name": "【物资付款差额】",
            "expression": " SUMX(KEEPFILTERS(VALUES('专项物资合同表'[合同编号])),var a=[【专项物资含税结算价】] return IF(a>0,a-[【物资实际付款】],[【有效进场价税合计】]-[【物资实际付款】]))",
            "displayFolder": "物资"
          },
          {
            "name": "【专项物资含税结算价】",
            "expression": " var a=SUM('专项物资结算'[含税结算额]) return IF(ISFILTERED('日历'[年月]),BLANK(),a)",
            "displayFolder": "物资"
          },
          {
            "name": "【有效进场价税合计】",
            "expression": " [【进场价税合计】]-[【退场价税合计】]",
            "displayFolder": "物资"
          },
          {
            "name": "【有效进场税金】",
            "expression": " [【进场税金】]-[【退场税金】]",
            "displayFolder": "物资"
          },
          {
            "name": "【有效进场金额】",
            "expression": " [【进场金额】]-[【退场金额】]",
            "displayFolder": "物资"
          },
          {
            "name": "【物资付款_在途】",
            "expression": " CALCULATE(SUM('专项物资付款表'[本期付款]),'专项物资付款表'[单据状态]=\"总部处理中\")",
            "displayFolder": "物资"
          },
          {
            "name": "【物资付款含在途】",
            "expression": " [【物资付款_在途】]+[【物资实际付款】]",
            "displayFolder": "物资"
          },
          {
            "name": "【租赁合同价税合计】",
            "expression": "SUM('租赁合同额表'[含税合同价])",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁合同税额】",
            "expression": "SUM('租赁合同额表'[税金])",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁合同额】",
            "expression": "SUM('租赁合同额表'[不含税合同价款])",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁含税结算额】",
            "expression": " var a=SUM('租赁物资结算'[含税结算额]) return IF(ISFILTERED('日历'[年月]),BLANK(),a)",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁报量价税合计】",
            "expression": " SUM('租赁物资报量表'[报量价税合计])",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁报量税额】",
            "expression": " SUM('租赁物资报量表'[报量税额])",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁报量金额】",
            "expression": " SUM('租赁物资报量表'[报量金额])",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁付款_在途】",
            "expression": " CALCULATE(SUM('租赁物资付款表'[金额]),'租赁物资付款表'[单据状态]=\"总部处理中\")",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁付款】",
            "expression": " CALCULATE(SUM('租赁物资付款表'[金额]),'租赁物资付款表'[单据状态]=\"已完成\")",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁付款含在途】",
            "expression": " [【租赁付款_在途】]+[【租赁付款】]",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁付款差额】",
            "expression": " SUMX(KEEPFILTERS(VALUES('租赁合同表'[合同编号])), var a=[【租赁含税结算额】] return IF(a>0,a-[【租赁付款】], [【租赁报量价税合计】]-[【租赁付款】]))",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁合同付款比例】",
            "expression": " IF(ISFILTERED('日历'[年月]),BLANK(), IF(ISBLANK([【租赁含税结算额】]),DIVIDE([【租赁付款】],[【租赁报量价税合计】]),DIVIDE([【租赁付款】],[【租赁含税结算额】])))",
            "displayFolder": "租赁"
          },
          {
            "name": "【最后处理时间】",
            "expression": "MAX('最后处理时间'[最后处理时间])"
          },
          {
            "name": "【统一转账付款金额】",
            "expression": " CALCULATE(SUM('统一转账进场'[价税合计]),'统一转账进场'[付款状态]=\"已支付\")",
            "formatString": "#,0.00",
            "displayFolder": "统一转账"
          },
          {
            "name": "【统一进场价税合计】",
            "expression": " SUM('统一转账进场'[价税合计])",
            "formatString": "#,0.00",
            "displayFolder": "统一转账"
          },
          {
            "name": "【统一进场税金】",
            "expression": " SUM('统一转账进场'[税金])",
            "formatString": "#,0.00",
            "displayFolder": "统一转账"
          },
          {
            "name": "【统一进场金额】",
            "expression": " SUM('统一转账进场'[金额])",
            "formatString": "#,0.00",
            "displayFolder": "统一转账"
          },
          {
            "name": "【统一退场价税合计】",
            "expression": " SUM('统一转账退场'[价税合计])",
            "formatString": "#,0.00",
            "displayFolder": "统一转账"
          },
          {
            "name": "【统一退场税金】",
            "expression": " SUM('统一转账退场'[税金])",
            "formatString": "#,0.00",
            "displayFolder": "统一转账"
          },
          {
            "name": "【统一退场金额】",
            "expression": " SUM('统一转账退场'[金额])",
            "formatString": "#,0.00",
            "displayFolder": "统一转账"
          },
          {
            "name": "【统一有效进场】",
            "expression": " [【统一进场价税合计】]-[【统一退场价税合计】]",
            "formatString": "#,0.00",
            "displayFolder": "统一转账"
          },
          {
            "name": "【分包应付】",
            "expression": "SUMX(KEEPFILTERS(values('分包合同表'[合同编号])),IF([【分包含税结算额】]>0,[【分包含税结算额】],[【报量价税合计】]))",
            "formatString": "#,##0.00",
            "displayFolder": "分包"
          },
          {
            "name": "【分包支付比例】",
            "expression": " DIVIDE([【分包实际付款】],[【分包应付】])",
            "formatString": "#,##0.00 %",
            "displayFolder": "分包"
          },
          {
            "name": "【分供应付】",
            "expression": "SUMX(KEEPFILTERS(VALUES('专项物资合同表'[合同编号])),IF([【专项物资含税结算价】]>0,[【专项物资含税结算价】],[【有效进场价税合计】]))",
            "formatString": "#,##0.00",
            "displayFolder": "物资"
          },
          {
            "name": "【分供支付比例】",
            "expression": "DIVIDE([【物资实际付款】],[【分供应付】])",
            "formatString": "#,##0.00 %",
            "displayFolder": "物资"
          },
          {
            "name": "【租赁应付】",
            "expression": "SUMX(KEEPFILTERS(VALUES('租赁合同表'[合同编号])),IF([【租赁含税结算额】]>0,[【租赁含税结算额】], [【租赁报量价税合计】]))",
            "formatString": "#,##0.00",
            "displayFolder": "租赁"
          },
          {
            "name": "【租赁支付比例】",
            "expression": " DIVIDE([【租赁付款】],[【租赁应付】])",
            "formatString": "#,##0.00 %",
            "displayFolder": "租赁"
          }
        ]
      },
      {
        "name": "分包减报量",
        "columns": [
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "分包名称",
            "dataType": "string",
            "sourceColumn": "分包名称"
          },
          {
            "name": "减报量金额",
            "dataType": "double",
            "sourceColumn": "减报量金额"
          },
          {
            "name": "减报量税额",
            "dataType": "double",
            "sourceColumn": "减报量税额"
          },
          {
            "name": "减报量价税合计",
            "dataType": "double",
            "sourceColumn": "减报量价税合计"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "专业",
            "dataType": "string",
            "sourceColumn": "专业"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Table.NestedJoin(分包减报量明细,{\"FSHENPIBIAOID\"},分包减报量主表,{\"FID\"},\"分包减报量主表\",JoinKind.Inner),",
                "    #\"展开的“分包减报量主表”\" = Table.ExpandTableColumn(源, \"分包减报量主表\", {\"项目名称\", \"年\", \"月\", \"专业\"}, {\"项目名称\", \"年\", \"月\", \"专业\"}),",
                "    删除的列 = Table.RemoveColumns(#\"展开的“分包减报量主表”\",{\"FSHENPIBIAOID\"}),",
                "    已添加自定义 = Table.AddColumn(删除的列, \"日期\", each #date([年],[月],1),type date)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ]
      },
      {
        "name": "最后处理时间",
        "columns": [
          {
            "name": "最后处理时间",
            "dataType": "dateTime",
            "sourceColumn": "最后处理时间"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = DateTime.LocalNow(),",
                "    转换为表 = #table(1, {{源}}),",
                "    重命名的列 = Table.RenameColumns(转换为表,{{\"Column1\", \"最后处理时间\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"最后处理时间\", type datetime}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ]
      },
      {
        "name": "账户权限",
        "columns": [
          {
            "name": "身份证",
            "dataType": "string",
            "sourceColumn": "身份证"
          },
          {
            "name": "单位类型",
            "dataType": "string",
            "sourceColumn": "单位类型"
          },
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "账号",
            "dataType": "string",
            "sourceColumn": "账号"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Table.Combine({总部帐号, 分公司帐号, 项目帐号}),",
                "    合并的查询 = Table.NestedJoin(源, {\"身份证\"}, 门户账户, {\"身份证\"}, \"门户账户\", JoinKind.RightOuter),",
                "    #\"展开的“门户账户”\" = Table.ExpandTableColumn(合并的查询, \"门户账户\", {\"账号\"}, {\"账号\"})",
                "in",
                "    #\"展开的“门户账户”\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "账户类型",
            "expression": "CALCULATE(MIN('账户权限'[单位类型]),'账户权限'[账号]=username())"
          }
        ]
      },
      {
        "name": "权限",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "无限制",
              "description": "SELECTEDMEASURE()",
              "expression": "SELECTEDMEASURE()"
            },
            {
              "name": "分级权限",
              "description": "SWITCH(true,[账户类型]=\"001\",SELECTEDMEASURE(),CALCULATE(SELECTEDMEASURE(),'账户权限'[账号]=CUSTOMDATA()))",
              "expression": "SWITCH(true,[账户类型]=\"001\",SELECTEDMEASURE(),CALCULATE(SELECTEDMEASURE(),'账户权限'[账号]=CUSTOMDATA()))"
            }
          ]
        },
        "columns": [
          {
            "name": "权限设置",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "分包合同额表",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "合同编号",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "分包合同表[合同编号]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "签订时间",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "分包合同表[签订时间]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "不含税合同总价",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "分包合同表[不含税合同总价]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "含税合同总价",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "分包合同表[含税合同总价]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "税金",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "分包合同表[税金]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "GROUPBY('分包合同表','分包合同表'[合同编号],'分包合同表'[签订时间],'分包合同表'[不含税合同总价],'分包合同表'[含税合同总价],'分包合同表'[税金])"
            }
          }
        ]
      },
      {
        "name": "专项物资合同额表",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "合同编号",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "专项物资合同表[合同编号]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "签订时间",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "专项物资合同表[签订时间]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "不含税合同价款",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "专项物资合同表[不含税合同价款]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "含税合同价",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "专项物资合同表[含税合同价]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "税金",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "专项物资合同表[税金]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "GROUPBY('专项物资合同表','专项物资合同表'[合同编号],'专项物资合同表'[签订时间],'专项物资合同表'[不含税合同价款],'专项物资合同表'[含税合同价],'专项物资合同表'[税金])"
            }
          }
        ]
      },
      {
        "name": "租赁合同额表",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "合同编号",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "租赁合同表[合同编号]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "签订时间",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "租赁合同表[签订时间]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "不含税合同价款",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "租赁合同表[不含税合同价款]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "含税合同价",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "租赁合同表[含税合同价]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "税金",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "租赁合同表[税金]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "GROUPBY('租赁合同表','租赁合同表'[合同编号],'租赁合同表'[签订时间],'租赁合同表'[不含税合同价款],'租赁合同表'[含税合同价],'租赁合同表'[税金])"
            }
          }
        ]
      },
      {
        "name": "统一转账合同",
        "columns": [
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "合同名称",
            "dataType": "string",
            "sourceColumn": "合同名称"
          },
          {
            "name": "合同协议号",
            "dataType": "string",
            "sourceColumn": "合同协议号"
          },
          {
            "name": "合同类型",
            "dataType": "string",
            "sourceColumn": "合同类型"
          },
          {
            "name": "待签合同编号",
            "dataType": "string",
            "sourceColumn": "待签合同编号"
          },
          {
            "name": "待签合同名称",
            "dataType": "string",
            "sourceColumn": "待签合同名称"
          },
          {
            "name": "商务科目Code",
            "dataType": "string",
            "sourceColumn": "商务科目Code"
          },
          {
            "name": "商务科目",
            "dataType": "string",
            "sourceColumn": "商务科目"
          },
          {
            "name": "商务科目全名称",
            "dataType": "string",
            "sourceColumn": "商务科目全名称"
          },
          {
            "name": "财务科目编码",
            "dataType": "string",
            "sourceColumn": "财务科目编码"
          },
          {
            "name": "财务科目名称",
            "dataType": "string",
            "sourceColumn": "财务科目名称"
          },
          {
            "name": "财务科目全路径名称",
            "dataType": "string",
            "sourceColumn": "财务科目全路径名称"
          },
          {
            "name": "施工专业",
            "dataType": "string",
            "sourceColumn": "施工专业"
          },
          {
            "name": "纳税人性质",
            "dataType": "string",
            "sourceColumn": "纳税人性质"
          },
          {
            "name": "增值税率",
            "dataType": "double",
            "sourceColumn": "增值税率"
          },
          {
            "name": "是否非常规分供合同",
            "dataType": "string",
            "sourceColumn": "是否非常规分供合同"
          },
          {
            "name": "计划单号ID",
            "dataType": "string",
            "sourceColumn": "计划单号ID"
          },
          {
            "name": "计划单号编码",
            "dataType": "string",
            "sourceColumn": "计划单号编码"
          },
          {
            "name": "计划单号",
            "dataType": "string",
            "sourceColumn": "计划单号"
          },
          {
            "name": "合同约定的收票时点",
            "dataType": "string",
            "sourceColumn": "合同约定的收票时点"
          },
          {
            "name": "是否一局协同平台准入",
            "dataType": "string",
            "sourceColumn": "是否一局协同平台准入"
          },
          {
            "name": "供方编码",
            "dataType": "string",
            "sourceColumn": "供方编码"
          },
          {
            "name": "供方名称",
            "dataType": "string",
            "sourceColumn": "供方名称"
          },
          {
            "name": "供方联系人",
            "dataType": "string",
            "sourceColumn": "供方联系人"
          },
          {
            "name": "局分供类别",
            "dataType": "string",
            "sourceColumn": "局分供类别"
          },
          {
            "name": "合作内容",
            "dataType": "string",
            "sourceColumn": "合作内容"
          },
          {
            "name": "合同内容描述",
            "dataType": "string",
            "sourceColumn": "合同内容描述"
          },
          {
            "name": "此物资是否包含在分包合同内",
            "dataType": "string",
            "sourceColumn": "此物资是否包含在分包合同内"
          },
          {
            "name": "签订时间",
            "dataType": "dateTime",
            "sourceColumn": "签订时间"
          },
          {
            "name": "定价原则",
            "dataType": "string",
            "sourceColumn": "定价原则"
          },
          {
            "name": "含税合同价",
            "dataType": "double",
            "sourceColumn": "含税合同价"
          },
          {
            "name": "不含税合同价款",
            "dataType": "double",
            "sourceColumn": "不含税合同价款"
          },
          {
            "name": "税金",
            "dataType": "double",
            "sourceColumn": "税金"
          },
          {
            "name": "超过合约规划金额说明",
            "dataType": "string",
            "sourceColumn": "超过合约规划金额说明"
          },
          {
            "name": "其他说明",
            "dataType": "string",
            "sourceColumn": "其他说明"
          },
          {
            "name": "运输商名称",
            "dataType": "string",
            "sourceColumn": "运输商名称"
          },
          {
            "name": "填报日期",
            "dataType": "dateTime",
            "sourceColumn": "填报日期"
          },
          {
            "name": "是否已结算",
            "dataType": "string",
            "sourceColumn": "是否已结算"
          },
          {
            "name": "含税结算金额",
            "dataType": "double",
            "sourceColumn": "含税结算金额"
          },
          {
            "name": "结算考核状态",
            "dataType": "string",
            "sourceColumn": "结算考核状态"
          },
          {
            "name": "结算考核完成时间",
            "dataType": "dateTime",
            "sourceColumn": "结算考核完成时间"
          },
          {
            "name": "评审状态ID",
            "dataType": "string",
            "sourceColumn": "评审状态ID"
          },
          {
            "name": "评审状态",
            "dataType": "string",
            "sourceColumn": "评审状态"
          },
          {
            "name": "合同评审类型",
            "dataType": "string",
            "sourceColumn": "合同评审类型"
          },
          {
            "name": "业务大类",
            "dataType": "string",
            "sourceColumn": "业务大类"
          },
          {
            "name": "业务小类",
            "dataType": "string",
            "sourceColumn": "业务小类"
          },
          {
            "name": "提交者",
            "dataType": "string",
            "sourceColumn": "提交者"
          },
          {
            "name": "提交者岗位",
            "dataType": "string",
            "sourceColumn": "提交者岗位"
          },
          {
            "name": "提交者部门",
            "dataType": "string",
            "sourceColumn": "提交者部门"
          },
          {
            "name": "提交者机构",
            "dataType": "string",
            "sourceColumn": "提交者机构"
          },
          {
            "name": "组织全路径名",
            "dataType": "string",
            "sourceColumn": "组织全路径名"
          },
          {
            "name": "创建时间",
            "dataType": "dateTime",
            "sourceColumn": "创建时间"
          },
          {
            "name": "最后修改人",
            "dataType": "string",
            "sourceColumn": "最后修改人"
          },
          {
            "name": "最后修改时间",
            "dataType": "dateTime",
            "sourceColumn": "最后修改时间"
          },
          {
            "name": "预付款金额",
            "dataType": "double",
            "sourceColumn": "预付款金额"
          },
          {
            "name": "预付款担保形式",
            "dataType": "string",
            "sourceColumn": "预付款担保形式"
          },
          {
            "name": "预付款担保形式编码",
            "dataType": "string",
            "sourceColumn": "预付款担保形式编码"
          },
          {
            "name": "股份财务一体化项目名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目名称"
          },
          {
            "name": "对方负责人",
            "dataType": "string",
            "sourceColumn": "对方负责人"
          },
          {
            "name": "司法保全金额(元)",
            "dataType": "double",
            "sourceColumn": "司法保全金额(元)"
          },
          {
            "name": "收款单位开户行名称",
            "dataType": "string",
            "sourceColumn": "收款单位开户行名称"
          },
          {
            "name": "收款单位银行账号",
            "dataType": "string",
            "sourceColumn": "收款单位银行账号"
          },
          {
            "name": "对方签约单位",
            "dataType": "string",
            "sourceColumn": "对方签约单位"
          },
          {
            "name": "股份财务一体化项目编码",
            "dataType": "string",
            "sourceColumn": "股份财务一体化项目编码"
          },
          {
            "name": "股份财务一体化组织机构名称",
            "dataType": "string",
            "sourceColumn": "股份财务一体化组织机构名称"
          },
          {
            "name": "是否云筑MRO框架协议",
            "dataType": "string",
            "sourceColumn": "是否云筑MRO框架协议"
          },
          {
            "name": "对应云筑MRO框架协议编号",
            "dataType": "string",
            "sourceColumn": "对应云筑MRO框架协议编号"
          },
          {
            "name": "对应云筑MRO框架协议名称",
            "dataType": "string",
            "sourceColumn": "对应云筑MRO框架协议名称"
          },
          {
            "name": "是否已做三方抵债",
            "dataType": "string",
            "sourceColumn": "是否已做三方抵债"
          },
          {
            "name": "标准合同是否满额签约",
            "dataType": "string",
            "sourceColumn": "标准合同是否满额签约"
          },
          {
            "name": "是否已更新标准合同",
            "dataType": "string",
            "sourceColumn": "是否已更新标准合同"
          },
          {
            "name": "是否合同外签约",
            "dataType": "string",
            "sourceColumn": "是否合同外签约"
          },
          {
            "name": "国内/外",
            "dataType": "string",
            "sourceColumn": "国内/外"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = 专项物资合同表,",
                "    筛选的行 = Table.SelectRows(源, each ([合同评审类型] = \"统一转账合同\"))",
                "in",
                "    筛选的行"
              ]
            }
          }
        ]
      },
      {
        "name": "统一转账进场",
        "columns": [
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "价税合计",
            "dataType": "double",
            "sourceColumn": "价税合计"
          },
          {
            "name": "金额",
            "dataType": "double",
            "sourceColumn": "金额"
          },
          {
            "name": "税金",
            "dataType": "double",
            "sourceColumn": "税金"
          },
          {
            "name": "付款状态",
            "dataType": "string",
            "sourceColumn": "付款状态"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_WUZIJINCHANG_ZB = GSPM{[Name=\"GSPM_WUZIJINCHANG_ZB\"]}[Data],",
                "    筛选的行1 = Table.SelectRows(GSPM_WUZIJINCHANG_ZB, each ([FWUZIJINCHANGLEIBIE] = \"统一转账物资\") and ([FDANJUZHUANGTAI] = \"已完成\")),",
                "    删除的其他列 = Table.SelectColumns(筛选的行1,{\"FNIAN\", \"FYUE\", \"FXIANGMUBIANMA\", \"FXIANGMUMINGCHENG\", \"FHETONGBIANHAO\", \"FHANSHUIJINCHANGJINE\", \"FBUHANSHUIJINCHANGJINE\", \"FSHUIJIN\", \"FFUKUANZHUANGTAI\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FHANSHUIJINCHANGJINE\", \"价税合计\"}, {\"FBUHANSHUIJINCHANGJINE\", \"金额\"}, {\"FSHUIJIN\", \"税金\"}, {\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FFUKUANZHUANGTAI\", \"付款状态\"}}),",
                "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1),type date)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ]
      },
      {
        "name": "统一转账退场",
        "columns": [
          {
            "name": "退场单",
            "dataType": "string",
            "sourceColumn": "退场单"
          },
          {
            "name": "合同编号",
            "dataType": "string",
            "sourceColumn": "合同编号"
          },
          {
            "name": "金额",
            "dataType": "double",
            "sourceColumn": "金额"
          },
          {
            "name": "税金",
            "dataType": "double",
            "sourceColumn": "税金"
          },
          {
            "name": "价税合计",
            "dataType": "double",
            "sourceColumn": "价税合计"
          },
          {
            "name": "年",
            "dataType": "double",
            "sourceColumn": "年"
          },
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "月",
            "dataType": "double",
            "sourceColumn": "月"
          },
          {
            "name": "日期",
            "dataType": "dateTime",
            "sourceColumn": "日期"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = #\"Oracle/172 16 8 78/oracledb\",",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_WUZITUICHANG_CB = GSPM{[Name=\"GSPM_WUZITUICHANG_CB\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(GSPM_WUZITUICHANG_CB,{\"FTUICHANGDANID\", \"FHETONGBIANHAO\", \"FJINE\", \"FSHUIE\", \"FJIASHUIHEJI\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FTUICHANGDANID\", \"退场单\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FJINE\", \"金额\"}, {\"FSHUIE\", \"税金\"}, {\"FJIASHUIHEJI\", \"价税合计\"}}),",
                "    合并的查询 = Table.NestedJoin(重命名的列, {\"退场单\"}, 统一转账物资退场主表, {\"FID\"}, \"专项物资退场主表\", JoinKind.Inner),",
                "    #\"展开的“专项物资退场主表”\" = Table.ExpandTableColumn(合并的查询, \"专项物资退场主表\", {\"年\", \"项目编码\", \"项目名称\", \"月\"}, {\"年\", \"项目编码\", \"项目名称\", \"月\"}),",
                "    已添加自定义 = Table.AddColumn(#\"展开的“专项物资退场主表”\", \"日期\", each #date([年],[月],1)),",
                "    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{\"日期\", type datetime}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "b811fbef-f3e0-4a4a-a21f-11695a2280ed",
        "fromTable": "分包报量表",
        "fromColumn": "合同编号",
        "toTable": "分包合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "20e42ea8-8611-4fef-b2be-68f3bcd96f32",
        "fromTable": "分包付款主表",
        "fromColumn": "合同编号",
        "toTable": "分包合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "3f590088-48e1-4711-9bbd-9bf6bf88e164",
        "fromTable": "分包合同表",
        "fromColumn": "项目编码",
        "toTable": "项目信息",
        "toColumn": "项目编码"
      },
      {
        "name": "27d07ca7-f942-4bcd-abb5-fe80c78fc32f",
        "fromTable": "分包结算",
        "fromColumn": "合同编号",
        "toTable": "分包合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "a4a5f5ac-2772-4246-a679-cade440b2686",
        "fromTable": "分包报量表",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "2b198d2c-87bc-4555-9b1d-1df058b4411d",
        "fromTable": "分包付款主表",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "865b7476-b66d-4281-ad2a-d1779cc7e97f",
        "fromTable": "专项物资合同表",
        "fromColumn": "项目编码",
        "toTable": "项目信息",
        "toColumn": "项目编码"
      },
      {
        "name": "2f6c863f-8311-413c-934f-53206fe5d344",
        "fromTable": "专项物资进场",
        "fromColumn": "合同编号",
        "toTable": "专项物资合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "e2267f8c-69af-4aad-a892-e356b83efb9f",
        "fromTable": "专项物资进场",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "9927d9d8-cfa1-4c77-b47b-3be98da62d0f",
        "fromTable": "专项物资退场",
        "fromColumn": "合同编号",
        "toTable": "专项物资合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "9697e062-ea08-49a8-b8b2-cdc63dff9fd1",
        "fromTable": "专项物资退场",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "de244127-a5c6-41ce-8a52-5ef6b328361d",
        "fromTable": "专项物资结算",
        "fromColumn": "合同编号",
        "toTable": "专项物资合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "157ecdd7-c854-4648-b1e7-7aab5fa3a9d4",
        "fromTable": "专项物资付款表",
        "fromColumn": "合同编号",
        "toTable": "专项物资合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "b1bc0b54-a33e-41d0-8fa5-79702516c397",
        "fromTable": "专项物资付款表",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "902603a1-e2d0-4e69-ac83-18033f3ea778",
        "fromTable": "租赁合同表",
        "fromColumn": "项目编码",
        "toTable": "项目信息",
        "toColumn": "项目编码"
      },
      {
        "name": "88499df2-c643-4549-bac9-c8264eed93f4",
        "fromTable": "租赁物资报量表",
        "fromColumn": "合同编号",
        "toTable": "租赁合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "9435f9e2-dd3b-4225-a98b-fe6ca294273d",
        "fromTable": "租赁物资报量表",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "c5eaed56-08b3-4919-9ffa-3737d8ffefd0",
        "fromTable": "租赁物资结算",
        "fromColumn": "合同编号",
        "toTable": "租赁合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "b290c1e7-6ab6-48aa-a8f8-5af15a4e6b5c",
        "fromTable": "租赁物资付款表",
        "fromColumn": "合同编号",
        "toTable": "租赁合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "940e2c0e-749e-46a4-b005-8e9e733406ab",
        "fromTable": "租赁物资付款表",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "ba6c3a6a-2bf2-4163-a620-4dad5790402f",
        "fromTable": "分包减报量",
        "fromColumn": "合同编号",
        "toTable": "分包合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "fe297e43-b04e-4228-ab19-94fc00618d7e",
        "fromTable": "分包减报量",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "fa1085cd-968b-4e6f-a069-70d5c94d5cbe",
        "toCardinality": "many",
        "fromTable": "项目信息",
        "fromColumn": "项目编码",
        "toTable": "账户权限",
        "toColumn": "项目编码",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "c28fab4a-7238-436f-a75b-8deb12bfe1bd",
        "fromTable": "分包合同额表",
        "fromColumn": "合同编号",
        "toTable": "分包合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "60ee2016-419a-400a-80cb-cba7c46a5769",
        "fromTable": "分包合同额表",
        "fromColumn": "签订时间",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "d318b269-0061-419b-a552-743adfdc79bd",
        "fromTable": "专项物资合同额表",
        "fromColumn": "合同编号",
        "toTable": "专项物资合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "f3da8bf6-4ac3-4894-85f9-2214f4d03cc1",
        "fromTable": "专项物资合同额表",
        "fromColumn": "签订时间",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "2d515db6-a7b8-415e-857e-42c88bcc7d77",
        "fromTable": "租赁合同额表",
        "fromColumn": "合同编号",
        "toTable": "租赁合同表",
        "toColumn": "合同编号"
      },
      {
        "name": "a3843684-ba7c-468e-bb1c-82c977113866",
        "fromTable": "租赁合同额表",
        "fromColumn": "签订时间",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "95dca82a-eda1-42ff-ad4f-571bb8431e6c",
        "fromTable": "统一转账进场",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "2c1f1738-ac0f-4b52-913f-1ed76216106f",
        "fromTable": "统一转账退场",
        "fromColumn": "日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "19a5db26-5e7f-4fee-8fe1-b492264dc7a0",
        "fromTable": "统一转账进场",
        "fromColumn": "项目编码",
        "toTable": "项目信息",
        "toColumn": "项目编码"
      },
      {
        "name": "8150836e-c35b-43d5-9e7b-fccc5b00f81a",
        "fromTable": "统一转账退场",
        "fromColumn": "项目编码",
        "toTable": "项目信息",
        "toColumn": "项目编码"
      },
      {
        "name": "5622efca-542c-49f5-9ad4-27396d23176b",
        "fromTable": "统一转账进场",
        "fromColumn": "合同编号",
        "toTable": "统一转账合同",
        "toColumn": "合同编号"
      },
      {
        "name": "02e6443c-8e13-4a23-a753-a514c79e083f",
        "fromTable": "统一转账退场",
        "fromColumn": "合同编号",
        "toTable": "统一转账合同",
        "toColumn": "合同编号"
      }
    ],
    "roles": [
      {
        "name": "数据处理",
        "modelPermission": "refresh"
      },
      {
        "name": "读者",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "CHINAONEBUILD\\yangjiahe",
            "memberId": "S-1-5-21-1606980848-1844823847-725345543-1253"
          },
          {
            "memberName": "CHINAONEBUILD\\Domain Users",
            "memberId": "S-1-5-21-1606980848-1844823847-725345543-513"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "X5数据库连接",
        "kind": "m",
        "expression": [
          "let",
          "    源 = \"172.16.8.78/oracledb\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
          "in",
          "    源"
        ]
      },
      {
        "name": "fx_List_生成字段更名列表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = (OWNER as text,TABLE_NAME as text) as list => let",
          "        源 =  #\"Oracle/172 16 8 78/oracledb\",",
          "        源1=Value.NativeQuery(源,\"select COLUMN_NAME,COMMENTS from all_col_comments where OWNER = '\" & OWNER &\"' and TABLE_NAME = '\" & TABLE_NAME & \"'\"),",
          "        替换的值 = Table.ReplaceValue(源1,null, each [COLUMN_NAME],Replacer.ReplaceValue,{\"COMMENTS\"}),",
          "        更改的类型 = Table.TransformColumnTypes(替换的值,{{\"COMMENTS\", type text}}),",
          "        删除的副本 = Table.Distinct(更改的类型, {\"COMMENTS\"}),",
          "        缩短说明字段长度=Table.TransformColumns(删除的副本, {{\"COMMENTS\", each Text.Start(_,15), type text}}),",
          "        自定义1 = List.Zip({缩短说明字段长度[COLUMN_NAME],缩短说明字段长度[COMMENTS]})",
          "    in",
          "        自定义1",
          "in",
          "    源"
        ]
      },
      {
        "name": "分包报量主表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FBBAOLIANGSHENPIBIAO = GSPM{[Name=\"GSPM_FBBAOLIANGSHENPIBIAO\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FBBAOLIANGSHENPIBIAO, each ([FDANJUZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FXIANGMUMINGCHENG\", \"FNIAN\", \"FYUE\", \"FSHIGONGZHUANYE\", \"FDANJUZHUANGTAI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FSHIGONGZHUANYE\", \"专业\"}, {\"FDANJUZHUANGTAI\", \"单据状态\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "分包报量明细",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_SHANGWUBAOLIANG = GSPM{[Name=\"GSPM_SHANGWUBAOLIANG\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_SHANGWUBAOLIANG,{\"FHETONGBIANHAO\", \"FFENBAODANWEI\", \"FSHIFOUZANGUHETONG\", \"FBAOLIANGJINE\", \"FBAOLIANGSHUIE\", \"FDQBLJIASHUIHEJI\", \"FGONGSIHEDINGDZBLJE\", \"FGONGSIHEDINGDZBLSE\", \"FGONGSIHEDINGDZBLJSHJ\", \"FSHENPIBIAOID\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FFENBAODANWEI\", \"分包名称\"}, {\"FBAOLIANGJINE\", \"报量金额1\"}, {\"FBAOLIANGSHUIE\", \"报量税额1\"}, {\"FDQBLJIASHUIHEJI\", \"报量价税合计1\"}, {\"FGONGSIHEDINGDZBLJE\", \"公司调整金额\"}, {\"FGONGSIHEDINGDZBLSE\", \"公司调整税额\"}, {\"FGONGSIHEDINGDZBLJSHJ\", \"公司调整价税合计\"}, {\"FSHIFOUZANGUHETONG\", \"是否暂估合同\"}}),",
          "    替换的值 = Table.ReplaceValue(重命名的列,null,0,Replacer.ReplaceValue,{\"报量金额1\", \"报量税额1\", \"报量价税合计1\", \"公司调整金额\", \"公司调整税额\", \"公司调整价税合计\"}),",
          "    已添加自定义 = Table.AddColumn(替换的值, \"报量金额\", each if [是否暂估合同]=\"否\" then [报量金额1] else [公司调整金额]),",
          "    已添加自定义1 = Table.AddColumn(已添加自定义, \"报量税额\", each if [是否暂估合同]=\"否\" then [报量税额1] else [公司调整税额]),",
          "    已添加自定义2 = Table.AddColumn(已添加自定义1, \"报量价税合计\", each if [是否暂估合同]=\"否\" then [报量价税合计1] else [公司调整价税合计]),",
          "    删除的列 = Table.RemoveColumns(已添加自定义2,{\"报量金额1\", \"报量税额1\", \"报量价税合计1\", \"公司调整金额\", \"公司调整税额\", \"公司调整价税合计\", \"是否暂估合同\"}),",
          "    更改的类型 = Table.TransformColumnTypes(删除的列,{{\"报量金额\", type number}, {\"报量税额\", type number}, {\"报量价税合计\", type number}})",
          "in",
          "    更改的类型"
        ]
      },
      {
        "name": "分包报量表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Table.NestedJoin(分包报量明细, {\"FSHENPIBIAOID\"}, 分包报量主表, {\"FID\"}, \"分包报量主表\", JoinKind.Inner),",
          "    #\"展开的“分包报量主表”\" = Table.ExpandTableColumn(源, \"分包报量主表\", {\"项目名称\", \"年\", \"月\", \"专业\"}, {\"项目名称\", \"年\", \"月\", \"专业\"}),",
          "    删除的列 = Table.RemoveColumns(#\"展开的“分包报量主表”\",{\"FSHENPIBIAOID\"}),",
          "    已添加自定义 = Table.AddColumn(删除的列, \"日期\", each #date([年],[月],1),type date)",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "分包合同表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_HETONGXINXI = GSPM{[Name=\"GSPM_HETONGXINXI\"]}[Data],",
          "    重命名的列 = Table.RenameColumns(GSPM_HETONGXINXI,fx_List_生成字段更名列表(\"GSPM\",\"GSPM_HETONGXINXI\")),",
          "    去除的文本 = Table.TransformColumns(重命名的列,{{\"项目名称\", Text.Trim, type text}}),",
          "    删除的列 = Table.RemoveColumns(去除的文本,{\"FID\", \"版本\", \"项目ID\", \"项目编号\", \"对应承包合同ID\", \"对应承包合同编号\", \"对应承包合同名称\", \"待签合同ID\", \"商务科目ID\", \"商务科目编码\", \"商务科目\", \"商务科目全路径ID\", \"商务科目全路径编码\", \"商务科目级次码\", \"财务科目ID\", \"财务科目编码\", \"财务科目\", \"财务科目全路径ID\", \"财务科目全路径编码\", \"财务科目级次码\", \"分包ID\", \"主表ID\", \"提交者ID\", \"提交者岗位ID\", \"提交者部门ID\", \"提交者机构ID\", \"组织全路径ID\", \"组织全路径名\", \"最后修改人标识\", \"一体化合同账户\", \"密码\"}),",
          "    提取的日期 = Table.TransformColumns(删除的列,{{\"签订时间\", DateTime.Date, type date}})",
          "in",
          "    提取的日期"
        ]
      },
      {
        "name": "分包付款主表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOGONGCHENGFUKUAN = GSPM{[Name=\"GSPM_FENBAOGONGCHENGFUKUAN\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_FENBAOGONGCHENGFUKUAN,{\"FNIAN\", \"FYUE\", \"FHETONGBIANHAO\", \"FBENQISHIJIFUKUAN\", \"FPINGSHENZHUANGTAI2\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FBENQISHIJIFUKUAN\", \"本期实际付款\"}, {\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FPINGSHENZHUANGTAI2\", \"单据状态\"}}),",
          "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1),type date)",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "分包结算",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOHETONGJIESUAN = GSPM{[Name=\"GSPM_FENBAOHETONGJIESUAN\"]}[Data],",
          "    筛选的行1 = Table.SelectRows(GSPM_FENBAOHETONGJIESUAN, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行1,{\"FHETONGBIANHAO\", \"FJIESUANJIAHS\", \"FPINGSHENZHUANGTAI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FJIESUANJIAHS\", \"含税结算额\"}, {\"FPINGSHENZHUANGTAI\", \"单据状态\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "分包减报量主表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FBJIANBAOLIANGSHENPIBIAO = GSPM{[Name=\"GSPM_FBJIANBAOLIANGSHENPIBIAO\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FBJIANBAOLIANGSHENPIBIAO, each ([FDANJUZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FXIANGMUMINGCHENG\", \"FNIAN\", \"FYUE\", \"FSHIGONGZHUANYE\", \"FDANJUZHUANGTAI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FSHIGONGZHUANYE\", \"专业\"}, {\"FDANJUZHUANGTAI\", \"单据状态\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "分包减报量明细",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_SHANGWUJIANBAOLIANG = GSPM{[Name=\"GSPM_SHANGWUJIANBAOLIANG\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_SHANGWUJIANBAOLIANG,{\"FHETONGBIANHAO\", \"FFENBAODANWEI\", \"FBAOLIANGJINE\", \"FBAOLIANGSHUIE\", \"FDQBLJIASHUIHEJI\", \"FSHENPIBIAOID\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FFENBAODANWEI\", \"分包名称\"}, {\"FBAOLIANGJINE\", \"减报量金额\"}, {\"FBAOLIANGSHUIE\", \"减报量税额\"}, {\"FDQBLJIASHUIHEJI\", \"减报量价税合计\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "分包减报量",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Table.NestedJoin(分包减报量明细,{\"FSHENPIBIAOID\"},分包减报量主表,{\"FID\"},\"分包减报量主表\",JoinKind.Inner),",
          "    #\"展开的“分包减报量主表”\" = Table.ExpandTableColumn(源, \"分包减报量主表\", {\"项目名称\", \"年\", \"月\", \"专业\"}, {\"项目名称\", \"年\", \"月\", \"专业\"}),",
          "    删除的列 = Table.RemoveColumns(#\"展开的“分包减报量主表”\",{\"FSHENPIBIAOID\"}),",
          "    已添加自定义 = Table.AddColumn(删除的列, \"日期\", each #date([年],[月],1),type date)",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "专项物资合同表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGXINXI = GSPM{[Name=\"GSPM_WUZIHETONGXINXI\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGXINXI, each ([FHETONGPINGSHENTYPE] <> \"周转材料租赁合同\")),",
          "    重命名的列 = Table.RenameColumns(筛选的行,fx_List_生成字段更名列表(\"GSPM\",\"GSPM_WUZIHETONGXINXI\")),",
          "    删除的列 = Table.RemoveColumns(重命名的列,{\"FID\", \"版本\", \"项目ID\", \"项目编号\", \"合同类型ID\", \"合同类型Code\", \"待签合同ID\", \"商务科目ID\", \"商务科目全路径ID\", \"商务科目全路径编码\", \"商务科目级次码\", \"财务科目ID\", \"财务科目全路径ID\", \"财务科目全路径编码\", \"财务科目级次码\", \"施工专业ID\", \"施工专业编码\", \"增值税发票类别ID\", \"增值税发票类别Code\", \"增值税发票类别\", \"供方ID\", \"供方类别\", \"局分供类别ID\", \"局分供类别Code\", \"定价原则ID\", \"定价原则Code\", \"填报人ID\", \"对应评审合同ID\", \"提交者ID\", \"提交者岗位ID\", \"提交者部门ID\", \"提交者机构ID\", \"组织全路径ID\", \"最后修改人标识\", \"一体化合同账户\", \"密码\"}),",
          "    提取的日期 = Table.TransformColumns(删除的列,{{\"签订时间\", DateTime.Date, type date}})",
          "in",
          "    提取的日期"
        ]
      },
      {
        "name": "专项物资进场",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIJINCHANG_ZB = GSPM{[Name=\"GSPM_WUZIJINCHANG_ZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIJINCHANG_ZB, each ([FYEWUXIAOLEI] = \"专项进场\") and ([FDANJUZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FNIAN\", \"FYUE\", \"FXIANGMUMINGCHENG\", \"FHETONGBIANHAO\", \"FHANSHUIJINCHANGJINE\", \"FBUHANSHUIJINCHANGJINE\", \"FSHUIJIN\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FHANSHUIJINCHANGJINE\", \"价税合计\"}, {\"FBUHANSHUIJINCHANGJINE\", \"金额\"}, {\"FSHUIJIN\", \"税金\"}}),",
          "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1),type date)",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "专项物资退场主表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZITUICHANG_ZB = GSPM{[Name=\"GSPM_WUZITUICHANG_ZB\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZITUICHANG_ZB,{\"FID\", \"FNIAN\", \"FYUE\", \"FDANJUZHUANGTAI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FDANJUZHUANGTAI\", \"单据状态\"}}),",
          "    筛选的行 = Table.SelectRows(重命名的列, each ([单据状态] = \"已完成\"))",
          "in",
          "    筛选的行"
        ]
      },
      {
        "name": "专项物资退场",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZITUICHANG_CB = GSPM{[Name=\"GSPM_WUZITUICHANG_CB\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZITUICHANG_CB,{\"FTUICHANGDANID\", \"FHETONGBIANHAO\", \"FJINE\", \"FSHUIE\", \"FJIASHUIHEJI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FTUICHANGDANID\", \"退场单\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FJINE\", \"金额\"}, {\"FSHUIE\", \"税金\"}, {\"FJIASHUIHEJI\", \"价税合计\"}}),",
          "    合并的查询 = Table.NestedJoin(重命名的列,{\"退场单\"},专项物资退场主表,{\"FID\"},\"专项物资退场主表\",JoinKind.Inner),",
          "    #\"展开的“专项物资退场主表”\" = Table.ExpandTableColumn(合并的查询, \"专项物资退场主表\", {\"年\", \"月\", \"单据状态\"}, {\"年\", \"月\", \"单据状态\"}),",
          "    删除的列 = Table.RemoveColumns(#\"展开的“专项物资退场主表”\",{\"退场单\"}),",
          "    已添加自定义 = Table.AddColumn(删除的列, \"日期\", each #date([年],[月],1),type date)",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "专项物资结算",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGJIESUANPS = GSPM{[Name=\"GSPM_WUZIHETONGJIESUANPS\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGJIESUANPS, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FHETONGBIANHAO\", \"FJIESUANJIAHS\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FJIESUANJIAHS\", \"含税结算额\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "专项物资付款表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_DANXIANGWUZIFUKUAN = GSPM{[Name=\"GSPM_DANXIANGWUZIFUKUAN\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_DANXIANGWUZIFUKUAN,{\"FNIAN\", \"FYUE\", \"FHETONGBIANHAO\", \"FBENQISHIJIFUKUAN\", \"FPINGSHENZHUANGTAI2\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FBENQISHIJIFUKUAN\", \"本期付款\"}, {\"FPINGSHENZHUANGTAI2\", \"单据状态\"}}),",
          "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1)),",
          "    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{\"日期\", type datetime}})",
          "in",
          "    更改的类型"
        ]
      },
      {
        "name": "租赁合同表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIHETONGXINXI = GSPM{[Name=\"GSPM_WUZIHETONGXINXI\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_WUZIHETONGXINXI, each ([FHETONGPINGSHENTYPE] = \"周转材料租赁合同\")),",
          "    重命名的列 = Table.RenameColumns(筛选的行,fx_List_生成字段更名列表(\"GSPM\",\"GSPM_WUZIHETONGXINXI\")),",
          "    删除的列 = Table.RemoveColumns(重命名的列,{\"FID\", \"版本\", \"项目ID\", \"项目编号\", \"合同类型ID\", \"合同类型Code\", \"待签合同ID\", \"商务科目ID\", \"商务科目全路径ID\", \"商务科目全路径编码\", \"商务科目级次码\", \"财务科目ID\", \"财务科目全路径ID\", \"财务科目全路径编码\", \"财务科目级次码\", \"施工专业ID\", \"施工专业编码\", \"增值税发票类别ID\", \"增值税发票类别Code\", \"增值税发票类别\", \"供方ID\", \"供方类别\", \"局分供类别ID\", \"局分供类别Code\", \"定价原则ID\", \"定价原则Code\", \"填报人ID\", \"对应评审合同ID\", \"提交者ID\", \"提交者岗位ID\", \"提交者部门ID\", \"提交者机构ID\", \"组织全路径ID\", \"最后修改人标识\", \"一体化合同账户\", \"密码\"})",
          "in",
          "    删除的列"
        ]
      },
      {
        "name": "租赁物资报量表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_ZZCAILIAOZLDQBL_ZB = GSPM{[Name=\"GSPM_ZZCAILIAOZLDQBL_ZB\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_ZZCAILIAOZLDQBL_ZB, each ([FDANJUZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FID\", \"FNIAN\", \"FYUE\", \"FXIANGMUBIANMA\", \"FXIANGMUMINGCHENG\", \"FDANJUZHUANGTAI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FDANJUZHUANGTAI\", \"单据状态\"}, {\"FXIANGMUBIANMA\", \"项目编码\"}}),",
          "    合并的查询 = Table.NestedJoin(重命名的列, {\"FID\"}, 租赁物资报量从表, {\"FBAOLIANGID\"}, \"租赁物资报量从表\", JoinKind.Inner),",
          "    #\"展开的“租赁物资报量从表”\" = Table.ExpandTableColumn(合并的查询, \"租赁物资报量从表\", {\"合同编号\", \"报量金额\", \"供方名称\", \"报量税额\", \"报量价税合计\"}, {\"合同编号\", \"报量金额\", \"供方名称\", \"报量税额\", \"报量价税合计\"}),",
          "    已添加自定义 = Table.AddColumn(#\"展开的“租赁物资报量从表”\", \"日期\", each #date([年],[月],1),type date)",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "租赁物资报量从表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_ZZZULINDQBLHT_CB = GSPM{[Name=\"GSPM_ZZZULINDQBLHT_CB\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_ZZZULINDQBLHT_CB,{\"FBAOLIANGID\", \"FHETONGBIANHAO\", \"FBAOLIANGJINE\", \"FGONGFANGMINGCHENG\", \"FBAOLIANGSHUIE\", \"FBAOLIANGJIASHUIHEJI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FBAOLIANGJINE\", \"报量金额\"}, {\"FGONGFANGMINGCHENG\", \"供方名称\"}, {\"FBAOLIANGSHUIE\", \"报量税额\"}, {\"FBAOLIANGJIASHUIHEJI\", \"报量价税合计\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "租赁物资结算",
        "kind": "m",
        "expression": [
          "let",
          "    源 = 专项物资结算",
          "in",
          "    源"
        ]
      },
      {
        "name": "租赁物资付款表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_ZZCAILIAOZULINAFK = GSPM{[Name=\"GSPM_ZZCAILIAOZULINAFK\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_ZZCAILIAOZULINAFK,{\"FNIAN\", \"FYUE\", \"FHETONGBIANHAO\", \"FBENQISHIJIFUKUAN\", \"FPINGSHENZHUANGTAI2\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FBENQISHIJIFUKUAN\", \"金额\"}, {\"FPINGSHENZHUANGTAI2\", \"单据状态\"}}),",
          "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1),type date)",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "统一转账合同",
        "kind": "m",
        "expression": [
          "let",
          "    源 = 专项物资合同表,",
          "    筛选的行 = Table.SelectRows(源, each ([合同评审类型] = \"统一转账合同\"))",
          "in",
          "    筛选的行"
        ]
      },
      {
        "name": "统一转账进场",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZIJINCHANG_ZB = GSPM{[Name=\"GSPM_WUZIJINCHANG_ZB\"]}[Data],",
          "    筛选的行1 = Table.SelectRows(GSPM_WUZIJINCHANG_ZB, each ([FWUZIJINCHANGLEIBIE] = \"统一转账物资\") and ([FDANJUZHUANGTAI] = \"已完成\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行1,{\"FNIAN\", \"FYUE\", \"FXIANGMUBIANMA\", \"FXIANGMUMINGCHENG\", \"FHETONGBIANHAO\", \"FHANSHUIJINCHANGJINE\", \"FBUHANSHUIJINCHANGJINE\", \"FSHUIJIN\", \"FFUKUANZHUANGTAI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FHANSHUIJINCHANGJINE\", \"价税合计\"}, {\"FBUHANSHUIJINCHANGJINE\", \"金额\"}, {\"FSHUIJIN\", \"税金\"}, {\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FFUKUANZHUANGTAI\", \"付款状态\"}}),",
          "    已添加自定义 = Table.AddColumn(重命名的列, \"日期\", each #date([年],[月],1),type date)",
          "in",
          "    已添加自定义"
        ]
      },
      {
        "name": "统一转账物资退场主表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZITUICHANG_ZB = GSPM{[Name=\"GSPM_WUZITUICHANG_ZB\"]}[Data],",
          "    筛选的行1 = Table.SelectRows(GSPM_WUZITUICHANG_ZB, each ([FYEWUXIAOLEI] = \"统一退场\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行1,{\"FID\", \"FNIAN\", \"FYUE\", \"FXIANGMUBIANMA\", \"FXIANGMUMINGCHENG\", \"FDANJUZHUANGTAI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNIAN\", \"年\"}, {\"FYUE\", \"月\"}, {\"FDANJUZHUANGTAI\", \"单据状态\"}, {\"FXIANGMUBIANMA\", \"项目编码\"}, {\"FXIANGMUMINGCHENG\", \"项目名称\"}}),",
          "    筛选的行 = Table.SelectRows(重命名的列, each ([单据状态] = \"已完成\"))",
          "in",
          "    筛选的行"
        ]
      },
      {
        "name": "统一转账退场",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_WUZITUICHANG_CB = GSPM{[Name=\"GSPM_WUZITUICHANG_CB\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(GSPM_WUZITUICHANG_CB,{\"FTUICHANGDANID\", \"FHETONGBIANHAO\", \"FJINE\", \"FSHUIE\", \"FJIASHUIHEJI\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FTUICHANGDANID\", \"退场单\"}, {\"FHETONGBIANHAO\", \"合同编号\"}, {\"FJINE\", \"金额\"}, {\"FSHUIE\", \"税金\"}, {\"FJIASHUIHEJI\", \"价税合计\"}}),",
          "    合并的查询 = Table.NestedJoin(重命名的列, {\"退场单\"}, 统一转账物资退场主表, {\"FID\"}, \"专项物资退场主表\", JoinKind.Inner),",
          "    #\"展开的“专项物资退场主表”\" = Table.ExpandTableColumn(合并的查询, \"专项物资退场主表\", {\"年\", \"项目编码\", \"项目名称\", \"月\"}, {\"年\", \"项目编码\", \"项目名称\", \"月\"}),",
          "    已添加自定义 = Table.AddColumn(#\"展开的“专项物资退场主表”\", \"日期\", each #date([年],[月],1)),",
          "    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{\"日期\", type datetime}})",
          "in",
          "    更改的类型"
        ]
      },
      {
        "name": "度量值表",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#\"列 1\" = _t]),",
          "    更改的类型 = Table.TransformColumnTypes(源,{{\"列 1\", type text}})",
          "in",
          "    更改的类型"
        ]
      },
      {
        "name": "统一转账度量值",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#\"列 1\" = _t]),",
          "    更改的类型 = Table.TransformColumnTypes(源,{{\"列 1\", type text}})",
          "in",
          "    更改的类型"
        ]
      },
      {
        "name": "X5数据库连接 (2)",
        "kind": "m",
        "expression": [
          "let",
          "    源 = \"172.16.8.78/oracledb\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
          "in",
          "    源"
        ]
      },
      {
        "name": "组织机构",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    X5SYS = 源{[Schema=\"X5SYS\"]}[Data],",
          "    SA_OPORG1 = X5SYS{[Name=\"SA_OPORG\"]}[Data],",
          "    // 取人员",
          "    筛选的行1 = Table.SelectRows(SA_OPORG1, each ([SORGKINDID] = \"psm\")),",
          "    // 取有效值",
          "    筛选的行 = Table.SelectRows(筛选的行1, each ([SVALIDSTATE] = 1)),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"SCODE\", \"SFCODE\"}),",
          "    重命名的列1 = Table.RenameColumns(删除的其他列,{{\"SCODE\", \"身份证\"}}),",
          "    按分隔符拆分列 = Table.SplitColumn(重命名的列1, \"SFCODE\", Splitter.SplitTextByDelimiter(\"/\", QuoteStyle.Csv), {\"SFCODE.1\", \"SFCODE.2\", \"单位类型\", \"单位编码\", \"SFCODE.5\", \"SFCODE.6\"}),",
          "    删除的其他列1 = Table.SelectColumns(按分隔符拆分列,{\"身份证\", \"单位类型\", \"单位编码\"}),",
          "    筛选的行2 = Table.SelectRows(删除的其他列1, each ([单位类型] <> \"U_ORG_DFPRY\"))",
          "in",
          "    筛选的行2"
        ]
      },
      {
        "name": "项目直管机构",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 78/oracledb\",",
          "    MD = 源{[Schema=\"MD\"]}[Data],",
          "    MD_XIANGMUXINXI = MD{[Name=\"MD_XIANGMUXINXI\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(MD_XIANGMUXINXI,{\"FXMBIANMA\", \"FZHIGUANJGXGBM\"}),",
          "    筛选的行1 = Table.SelectRows(删除的其他列, each ([FZHIGUANJGXGBM] <> null and [FZHIGUANJGXGBM] <> \"U_ORG_ZB\"))",
          "in",
          "    筛选的行1"
        ]
      },
      {
        "name": "门户账户",
        "kind": "m",
        "expression": [
          "let",
          "    源 = #\"Oracle/172 16 8 127/racdb com\",",
          "    PICC = 源{[Schema=\"PICC\"]}[Data],",
          "    SY_ORG_DEPT1 = PICC{[Name=\"SY_ORG_USER\"]}[Data],",
          "    // 取有效账号",
          "    筛选的行 = Table.SelectRows(SY_ORG_DEPT1, each ([S_FLAG] = 1)),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"USER_CODE\", \"USER_LOGIN_NAME\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"USER_CODE\", \"身份证\"}, {\"USER_LOGIN_NAME\", \"账号\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "总部帐号",
        "kind": "m",
        "expression": [
          "let",
          "    源 = 组织机构,",
          "    筛选的行 = Table.SelectRows(源, each ([单位类型] = \"U_ORG_ZB\")),",
          "    删除的副本 = Table.Distinct(筛选的行, {\"身份证\"}),",
          "    删除的列 = Table.RemoveColumns(删除的副本,{\"单位编码\"}),",
          "    替换的值 = Table.ReplaceValue(删除的列,\"U_ORG_ZB\",\"001\",Replacer.ReplaceText,{\"单位类型\"})",
          "in",
          "    替换的值"
        ]
      },
      {
        "name": "分公司帐号",
        "kind": "m",
        "expression": [
          "let",
          "    源 = 组织机构,",
          "    筛选的行 = Table.SelectRows(源, each ([单位类型] = \"U_ORG_FGS\")),",
          "    // 去掉总部人员",
          "    合并的查询 = Table.NestedJoin(筛选的行, {\"身份证\"}, 总部帐号, {\"身份证\"}, \"总部帐号\", JoinKind.LeftAnti),",
          "    删除的列 = Table.RemoveColumns(合并的查询,{\"总部帐号\"}),",
          "    合并的查询1 = Table.NestedJoin(删除的列, {\"单位编码\"}, 项目直管机构, {\"FZHIGUANJGXGBM\"}, \"项目直管机构\", JoinKind.Inner),",
          "    #\"展开的“项目直管机构”\" = Table.ExpandTableColumn(合并的查询1, \"项目直管机构\", {\"FXMBIANMA\"}, {\"项目编码\"}),",
          "    删除的列1 = Table.RemoveColumns(#\"展开的“项目直管机构”\",{\"单位编码\"}),",
          "    替换的值 = Table.ReplaceValue(删除的列1,\"U_ORG_FGS\",\"002\",Replacer.ReplaceText,{\"单位类型\"})",
          "in",
          "    替换的值"
        ]
      },
      {
        "name": "项目帐号",
        "kind": "m",
        "expression": [
          "let",
          "    源 = 组织机构,",
          "    筛选的行 = Table.SelectRows(源, each ([单位类型] = \"U_ORG_XM\")),",
          "    替换的值 = Table.ReplaceValue(筛选的行,\"U_ORG_XM\",\"003\",Replacer.ReplaceText,{\"单位类型\"}),",
          "    重命名的列 = Table.RenameColumns(替换的值,{{\"单位编码\", \"项目编码\"}})",
          "in",
          "    重命名的列"
        ]
      },
      {
        "name": "账户权限",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Table.Combine({总部帐号, 分公司帐号, 项目帐号}),",
          "    合并的查询 = Table.NestedJoin(源, {\"身份证\"}, 门户账户, {\"身份证\"}, \"门户账户\", JoinKind.RightOuter),",
          "    #\"展开的“门户账户”\" = Table.ExpandTableColumn(合并的查询, \"门户账户\", {\"账号\"}, {\"账号\"})",
          "in",
          "    #\"展开的“门户账户”\""
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  },
  "id": "SemanticModel"
}