{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"X5数据连接\",\"分包合同\",\"fx_List_生成字段更名列表\",\"分包合同补充评审\",\"分包合同结算\",\"指标表\",\"分包合同表\",\"单位\",\"维度-项目\",\"维度-责任体\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.119.986.0 (23.07)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "zh-CN",
    "cultures": [
      {
        "name": "zh-CN",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "X5数据连接",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "expression": "\"172.16.8.78/oracledb\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a7fdee74-d6d8-417a-bf75-cc6db5439f91",
        "queryGroup": "数据连接"
      },
      {
        "name": "fx_List_生成字段更名列表",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "description": [
          "用于X5数据库自动翻译表字段名，将此函数结果置于Table.RenameColumns函数的字段列表参数。",
          "参数说明：",
          "OWNER：oracle 用户名",
          "TABLE_NAME：需翻译列名的表名",
          "L：翻译后字段名字符数，过长Oracle会报错，目前15合适"
        ],
        "expression": [
          "let",
          "    源 = (OWNER as text, TABLE_NAME as text, L as number) as list => let",
          "        源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true, Query=\"select COLUMN_NAME,COMMENTS from all_col_comments where OWNER = '\" & OWNER & \"' and TABLE_NAME = '\" & TABLE_NAME & \"'\"]),",
          "        替换的值 = Table.ReplaceValue(源,null, each [COLUMN_NAME],Replacer.ReplaceValue,{\"COMMENTS\"}),",
          "        更改的类型 = Table.TransformColumnTypes(替换的值,{{\"COMMENTS\", type text}}),",
          "        缩短说明字段长度=Table.TransformColumns(更改的类型, {{\"COMMENTS\", each Text.Start(_,L), type text}}),",
          "        删除的副本 = Table.Distinct(缩短说明字段长度, {\"COMMENTS\"}),",
          "        自定义1 = List.Zip({删除的副本[COLUMN_NAME],删除的副本[COMMENTS]})",
          "    in",
          "        自定义1",
          "in",
          "    源"
        ],
        "kind": "m",
        "lineageTag": "9331195b-ef9b-42e0-829b-5d0a445a97b6",
        "queryGroup": "自定义函数"
      },
      {
        "name": "分包合同",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(X5数据连接, [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_HETONGPINGSHEN1 = GSPM{[Name=\"GSPM_HETONGPINGSHEN\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_HETONGPINGSHEN1, each ([FPINGSHENZHUANGTAI] = \"已完成\") and ([FYEWULEIBIE] <> \"集采分包框架评审\")),",
          "    重命名的列 = Table.RenameColumns(筛选的行,fx_List_生成字段更名列表(\"GSPM\",\"GSPM_HETONGPINGSHEN\",15)),",
          "    删除的其他列 = Table.SelectColumns(重命名的列,{\"合同编号\", \"合同协议号\", \"合同名称\", \"项目编码\", \"项目名称\", \"待签合同编号\", \"待签合同名称\", \"施工专业\", \"合同类型\", \"招标方式\", \"分包名称\", \"签订时间\", \"含税合同总价\"}),",
          "    提取的日期 = Table.TransformColumns(删除的其他列,{{\"签订时间\", DateTime.Date, type date}}),",
          "    已添加自定义 = Table.AddColumn(提取的日期, \"KEYID\", each Text.Combine({[合同编号],[项目编码]},\"@\"),type text),",
          "    删除的副本 = Table.Distinct(已添加自定义, {\"KEYID\"})",
          "in",
          "    删除的副本"
        ],
        "kind": "m",
        "lineageTag": "1b85e029-862d-4910-8f7f-61172e614996"
      },
      {
        "name": "分包合同结算",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    源 = Oracle.Database(X5数据连接, [HierarchicalNavigation=true]),",
          "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
          "    GSPM_FENBAOHETONGJIESUAN = GSPM{[Name=\"GSPM_FENBAOHETONGJIESUAN\"]}[Data],",
          "    筛选的行 = Table.SelectRows(GSPM_FENBAOHETONGJIESUAN, each ([FPINGSHENZHUANGTAI] = \"已完成\") and ([FJIESUANLEIXING] = \"正常结算\" or [FJIESUANLEIXING] = \"结算签约后让利\")),",
          "    删除的其他列 = Table.SelectColumns(筛选的行,{\"FXIANGMUBIANMA\", \"FHETONGBIANHAO\", \"FJIESUANJIAHS\", \"FQIANDINGSHIJIAN\", \"FPINGSHENZHUANGTAI\", \"SCREATETIME\", \"FJIESUANLEIXING\"}),",
          "    已添加自定义 = Table.AddColumn(删除的其他列, \"KEYID\", each Text.Combine({[FHETONGBIANHAO],[FXIANGMUBIANMA]},\"@\"),type text),",
          "    排序的行 = Table.Sort(已添加自定义,{{\"KEYID\", Order.Descending}, {\"SCREATETIME\", Order.Descending}}),",
          "    #\"已添加索引（稳定排序结果）\" = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
          "    删除的副本 = Table.Distinct(#\"已添加索引（稳定排序结果）\", {\"KEYID\"}),",
          "    重命名的列 = Table.RenameColumns(删除的副本,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FJIESUANJIAHS\", \"结算价含税\"}, {\"FPINGSHENZHUANGTAI\", \"单据状态\"}, {\"FQIANDINGSHIJIAN\", \"签订时间\"}}),",
          "    删除的其他列1 = Table.SelectColumns(重命名的列,{\"结算价含税\", \"签订时间\", \"单据状态\", \"KEYID\"}),",
          "    提取的日期 = Table.TransformColumns(删除的其他列1,{{\"签订时间\", DateTime.Date, type date}})",
          "in",
          "    提取的日期"
        ],
        "kind": "m",
        "lineageTag": "5cfaa93a-4dec-46f8-b962-391874a0000a"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "自定义函数"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "数据连接"
      }
    ],
    "relationships": [
      {
        "name": "968dfc1f-e01b-4752-8f93-72826f111ae9",
        "fromColumn": "结算时间",
        "fromTable": "分包合同表",
        "toColumn": "Date",
        "toTable": "日历"
      },
      {
        "name": "6c3e8ced-bd3e-4238-8065-92a10ad29676",
        "fromColumn": "项目编码",
        "fromTable": "分包合同表",
        "toColumn": "项目编码",
        "toTable": "维度-项目"
      },
      {
        "name": "083dbfa0-8192-4c0c-9179-e9a6f73018a6",
        "fromColumn": "责任体",
        "fromTable": "维度-项目",
        "toColumn": "责任体",
        "toTable": "维度-责任体"
      },
      {
        "name": "6f4a011f-e406-4f50-a384-f8798ff84279",
        "fromColumn": "KEYID",
        "fromTable": "分包合同补充评审",
        "toColumn": "KEYID",
        "toTable": "分包合同表"
      }
    ],
    "sourceQueryCulture": "zh-CN",
    "tables": [
      {
        "name": "分包合同补充评审",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "KEYID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5c789bf-46f7-4629-b5ce-5e0753042e54",
            "sourceColumn": "KEYID",
            "summarizeBy": "none"
          },
          {
            "name": "合同编号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9965a12-333d-4726-a427-74bd9a916d73",
            "sourceColumn": "合同编号",
            "summarizeBy": "none"
          },
          {
            "name": "含税合同总价",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2d6b3402-bd59-42bb-9a5e-f9d23295d5c1",
            "sourceColumn": "含税合同总价",
            "summarizeBy": "sum"
          },
          {
            "name": "签订时间",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "44ad5ec6-5c7e-4b9e-b5b7-495095d08c88",
            "sourceColumn": "签订时间",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dea94d69-dc2b-4551-921b-660f27294c16",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "02e3b96d-5050-4c20-8940-21ea593ffcbb",
        "partitions": [
          {
            "name": "分包合同补充评审-83a290ef-10b9-4709-bab0-de273f494330",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Oracle.Database(X5数据连接, [HierarchicalNavigation=true]),",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_FENBAOBUCHONGPINGSHEN1 = GSPM{[Name=\"GSPM_FENBAOBUCHONGPINGSHEN\"]}[Data],",
                "    筛选的行 = Table.SelectRows(GSPM_FENBAOBUCHONGPINGSHEN1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
                "    重命名的列 = Table.RenameColumns(筛选的行,fx_List_生成字段更名列表(\"GSPM\",\"GSPM_FENBAOBUCHONGPINGSHEN\",15)),",
                "    已添加自定义 = Table.AddColumn(重命名的列, \"签订时间\", each Date.From([签订日期]),type date),",
                "    删除的其他列 = Table.SelectColumns(已添加自定义,{\"项目编码\", \"合同编号\", \"含税合同总价\", \"签订时间\"}),",
                "    筛选的行1 = Table.SelectRows(删除的其他列, each [含税合同总价] <> 0),",
                "    已添加自定义1 = Table.AddColumn(筛选的行1, \"KEYID\", each Text.Combine({[合同编号],[项目编码]},\"@\"),type text)",
                "in",
                "    已添加自定义1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "分包合同表",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "columns": [
          {
            "name": "KEYID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50759b66-dee1-4549-a5e2-4af7c03bec12",
            "sourceColumn": "KEYID",
            "summarizeBy": "none"
          },
          {
            "name": "分包名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af17be67-b505-47db-ae97-f37081390b85",
            "sourceColumn": "分包名称",
            "summarizeBy": "none"
          },
          {
            "name": "合同协议号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d37268c0-7b9d-44d6-a2d9-a4b33bf686a2",
            "sourceColumn": "合同协议号",
            "summarizeBy": "none"
          },
          {
            "name": "合同名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "872b84a2-b492-443d-87f2-7c70e1b6b093",
            "sourceColumn": "合同名称",
            "summarizeBy": "none"
          },
          {
            "name": "合同类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3f028d2f-6638-44f2-8279-f4438810972f",
            "sourceColumn": "合同类型",
            "summarizeBy": "none"
          },
          {
            "name": "合同编号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ca865c0-67c7-4e32-b682-f2aa58d11147",
            "sourceColumn": "合同编号",
            "summarizeBy": "none"
          },
          {
            "name": "合同编号（名称）",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'分包合同表'[合同编号]&\"  （\"&'分包合同表'[合同名称]&\"）\"",
            "isDataTypeInferred": true,
            "lineageTag": "62a9cff3-6a46-481e-bbe1-4772916169dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "含税合同总价",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d44d7ba3-3efb-490a-922a-1969db0b971f",
            "sourceColumn": "含税合同总价",
            "summarizeBy": "sum"
          },
          {
            "name": "待签合同名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2519b9d-217f-4147-b9b9-0bec554975c5",
            "sourceColumn": "待签合同名称",
            "summarizeBy": "none"
          },
          {
            "name": "待签合同编号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cecaa6f5-c8d2-4e52-8119-c423904e450b",
            "sourceColumn": "待签合同编号",
            "summarizeBy": "none"
          },
          {
            "name": "招标方式",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d734116a-5fc8-417b-bfdd-69fb9035df21",
            "sourceColumn": "招标方式",
            "summarizeBy": "none"
          },
          {
            "name": "施工专业",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb89010f-a4d7-4734-820d-0afea75b64e8",
            "sourceColumn": "施工专业",
            "summarizeBy": "none"
          },
          {
            "name": "溢价率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06b52fe6-9b73-48ee-b2d0-4cb6551e4f6e",
            "sourceColumn": "溢价率",
            "summarizeBy": "sum"
          },
          {
            "name": "签订时间",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bb5e9cd3-1356-4a44-a153-67b469a0ca4f",
            "sourceColumn": "签订时间",
            "summarizeBy": "none"
          },
          {
            "name": "结算价含税",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b9d30580-db45-4396-bd55-a11b5c8e1d6c",
            "sourceColumn": "结算价含税",
            "summarizeBy": "sum"
          },
          {
            "name": "结算时间",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "abe374a9-99c4-414f-979d-65c04bf99891",
            "sourceColumn": "结算时间",
            "summarizeBy": "none"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d638408-acdc-4911-bdf3-c3741731b867",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8060ef1a-ffae-47a2-8fe4-5046d81ad65b",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2e144c31-4fda-4053-a2c6-34ec9e5fd6aa",
        "partitions": [
          {
            "name": "分包合同表-f783a942-10ea-4f58-a706-d56a61f95626",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Table.NestedJoin(分包合同, {\"KEYID\"}, 分包合同结算, {\"KEYID\"}, \"分包合同结算\", JoinKind.LeftOuter),",
                "    #\"展开的“分包合同结算”\" = Table.ExpandTableColumn(源, \"分包合同结算\", {\"结算价含税\", \"签订时间\"}, {\"结算价含税\", \"结算时间\"}),",
                "    已添加自定义 = Table.AddColumn(#\"展开的“分包合同结算”\", \"溢价率\", each ([结算价含税]-[含税合同总价])/[含税合同总价],type number)",
                "in",
                "    已添加自定义"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "单位",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "单位",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61607f5b-053d-4ac4-8251-ce94ed89da9d",
            "sourceColumn": "单位",
            "summarizeBy": "none"
          },
          {
            "name": "序号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "48136371-25bd-4a83-bd4f-5a7b52ba2a1b",
            "sourceColumn": "序号",
            "summarizeBy": "sum"
          },
          {
            "name": "系数",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4a14e0cd-2073-4f8c-ab18-502e5d0b55ae",
            "sourceColumn": "系数",
            "summarizeBy": "sum"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "73dbe268-f9b0-412c-88ea-a2636bd0f243",
        "measures": [
          {
            "name": "【单位】",
            "expression": "\"单位：\" & SELECTEDVALUE('单位'[单位],\"元\")",
            "lineageTag": "215d3164-40b4-4df9-b462-95c79cf228de"
          }
        ],
        "partitions": [
          {
            "name": "单位-1b6d6505-2542-4a72-bc71-22e68ce7fe6e",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WetrarKSjZAjGsTrRSk92tEOFDIAASBtBhHftRxKGShkrxcYCAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [单位 = _t, 系数 = _t, 序号 = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"系数\", type number}, {\"序号\", type number}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "指标表",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          }
        ],
        "columns": [
          {
            "name": "列 1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "d94833b8-6f67-40e3-b62a-15cd6b68327a",
            "sourceColumn": "列 1",
            "summarizeBy": "none"
          }
        ],
        "excludeFromModelRefresh": true,
        "lineageTag": "99d06471-af7a-4053-9cf0-35474728bbc7",
        "measures": [
          {
            "name": "【初始合同额】",
            "description": "SUM('分包合同表'[含税合同总价])/SELECTEDVALUE('单位'[系数],1)",
            "expression": "SUM('分包合同表'[含税合同总价])/SELECTEDVALUE('单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "45ab73e2-2f44-4bce-aac7-4b3edea8825a"
          },
          {
            "name": "【补充额】",
            "description": "SUM('分包合同补充评审'[含税合同总价])/SELECTEDVALUE('单位'[系数],1)",
            "expression": "SUM('分包合同补充评审'[含税合同总价])/SELECTEDVALUE('单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "3e9d3211-19e1-4551-8e9f-50d211b81038"
          },
          {
            "name": "【结算额】",
            "description": "SUM('分包合同表'[结算价含税])/SELECTEDVALUE('单位'[系数],1)",
            "expression": "SUM('分包合同表'[结算价含税])/SELECTEDVALUE('单位'[系数],1)",
            "formatString": "#,0.00",
            "lineageTag": "1cc75b2e-f6b8-48c1-8206-2d2bd6ec8432"
          },
          {
            "name": "【差额】",
            "description": "VAR a = [【结算额】] RETURN IF( a <> 0, SUMX( KEEPFILTERS( VALUES( '分包合同表'[合同编号] ) ), [【结算额】] - [【初始合同额】] ) ",
            "expression": "VAR a = [【结算额】] RETURN IF( a <> 0, SUMX( KEEPFILTERS( VALUES( '分包合同表'[合同编号] ) ), [【结算额】] - [【初始合同额】] ) )",
            "formatString": "#,0.00",
            "lineageTag": "b6e69f2c-a665-4f80-8939-764b38ef1480"
          },
          {
            "name": "【差额率】",
            "description": "DIVIDE([【差额】],[【初始合同额】])",
            "expression": "DIVIDE([【差额】],[【初始合同额】])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f762c6f8-9bde-4581-990f-d1788ff2154e"
          },
          {
            "name": "【合同额】",
            "description": "[【初始合同额】]+[【补充额】]",
            "expression": "[【初始合同额】]+[【补充额】]",
            "formatString": "#,0.00",
            "lineageTag": "ecc84a43-bf96-4827-b1d2-f48a70985bda"
          },
          {
            "name": "【项目数】",
            "description": "IF(HASONEVALUE('维度-项目'[项目名称]),BLANK(),DISTINCTCOUNT('分包合同表'[项目编码]))",
            "expression": "IF(HASONEVALUE('维度-项目'[项目名称]),BLANK(),DISTINCTCOUNT('分包合同表'[项目编码]))",
            "formatString": "0",
            "lineageTag": "189747e0-44f4-4f37-9b12-b8f5c2e8c3f0"
          },
          {
            "name": "【结算日期】",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "description": [
              "IF(",
              "    ( ISFILTERED( '分包合同表'[合同编号] ) + ISFILTERED( '分包合同表'[合同名称] ) + ISFILTERED( '分包合同表'[合同编号（名称）] ) ) > 0,",
              "    MAX( '分包合同表'[结算时间] )",
              ")"
            ],
            "expression": [
              "",
              "IF(",
              "    ( ISFILTERED( '分包合同表'[合同编号] ) + ISFILTERED( '分包合同表'[合同名称] ) + ISFILTERED( '分包合同表'[合同编号（名称）] ) ) > 0,",
              "    MAX( '分包合同表'[结算时间] )",
              ")"
            ],
            "formatString": "yyyy-mm-dd",
            "lineageTag": "ca88cc35-ff2c-46b7-8eec-5dffbfeb9570"
          }
        ],
        "partitions": [
          {
            "name": "指标表-f8d6a5dd-e0d4-487e-b90e-7506a767dac2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"列 1\" = _t])",
                "in",
                "    源"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "日历",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "1f3f1cac2db04ca0be6cd663b9c10f90"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "24ed140d-6cae-4486-abcd-a8abddae03d4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('日历'[Date],\"yyyy\")",
            "isDataTypeInferred": true,
            "lineageTag": "f263895b-77d4-4998-be1c-fee9669d0a4f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "年月",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT('日历'[Date],\"yyyy-MM\")",
            "isDataTypeInferred": true,
            "lineageTag": "16631708-e2fd-4d15-8753-492bc6c2005d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "年月层次",
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "d77786ff-0af3-4021-861e-56d1d820665a",
                "ordinal": 0
              },
              {
                "name": "年月",
                "column": "年月",
                "lineageTag": "d7cd69f8-4662-4a60-b0fd-0f41c223e92c",
                "ordinal": 1
              }
            ],
            "lineageTag": "ad43c124-86db-4260-9614-62d192596c39"
          }
        ],
        "lineageTag": "d8634cdc-96b1-4194-8d60-7b5db22425e8",
        "partitions": [
          {
            "name": "日历-3a0919e3-ca59-4df3-8bd0-67ae0ca3b8f5",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(\"2015-1-1\",TODAY())",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "维度-责任体",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "排序",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "79728547-d398-49ad-986c-7e54b6bd372e",
            "sourceColumn": "排序",
            "summarizeBy": "none"
          },
          {
            "name": "责任体",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79c94ed0-5fe4-4e1d-98e4-a43c14509367",
            "sourceColumn": "责任体",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "84a85258-5795-4917-afdb-cdc2f7ac41cd",
        "partitions": [
          {
            "name": "维度-责任体-8a6e29a0-297a-467b-83fa-b461a77333a4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wetq65mn/juezt7yYsFRJR8lQKVYnWunJjjlPe6Y/7WiDyALFjcDiT3v70MSNYeIgLUjiJnD1vSjqTcHiL5buRxM3A4s/X7PmyY6GJ7u6n+yY9bJ5BVDcHC6+qwdZ3AKhvhNZ3BIm/nT2bGRxQwOwxLOt258umQbiAz0aCwA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [责任体 = _t, 排序 = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"责任体\", type text}, {\"排序\", Int64.Type}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "维度-项目",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "专业分类",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad8fc087-3572-4a65-8b16-5758ea79e5c8",
            "sourceColumn": "专业分类",
            "summarizeBy": "none"
          },
          {
            "name": "业务板块",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c54c23f-2960-4d8f-9a25-e57eb74469ed",
            "sourceColumn": "业务板块",
            "summarizeBy": "none"
          },
          {
            "name": "京内外",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a96ff9e-15c4-4654-b9ce-f21bf6cb7cab",
            "sourceColumn": "京内外",
            "summarizeBy": "none"
          },
          {
            "name": "区县",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebec9800-8fd2-4f6b-b9d8-2595164025d6",
            "sourceColumn": "区县",
            "summarizeBy": "none"
          },
          {
            "name": "厂房事业部",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10f760b4-94b0-4340-be93-24ba52531309",
            "sourceColumn": "厂房事业部",
            "summarizeBy": "none"
          },
          {
            "name": "土建核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9d09c9be-18e6-49d5-9c5f-86bb08532469",
            "sourceColumn": "土建核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "土建甲指核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "93c1c6fa-466a-4ba6-a0ff-10f73c08576e",
            "sourceColumn": "土建甲指核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "城市",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1389ca6-2361-4d78-86f2-d3b0a6b6f495",
            "sourceColumn": "城市",
            "summarizeBy": "none"
          },
          {
            "name": "工程类别一级",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a71711a0-085e-4297-8a44-394f6c7856a2",
            "sourceColumn": "工程类别一级",
            "summarizeBy": "none"
          },
          {
            "name": "工程类别二级",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d976adcc-7905-40fd-9d23-600cca37c441",
            "sourceColumn": "工程类别二级",
            "summarizeBy": "none"
          },
          {
            "name": "所属总监团队",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85af0498-bffe-4e45-bd6a-7fd043af03b4",
            "sourceColumn": "所属总监团队",
            "summarizeBy": "none"
          },
          {
            "name": "投资非投资项目",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d748821-f558-4fd6-9383-d97dfb70473d",
            "sourceColumn": "投资非投资项目",
            "summarizeBy": "none"
          },
          {
            "name": "是否投资建造项目",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d716941-0130-46e9-b363-dba510dfad17",
            "sourceColumn": "是否投资建造项目",
            "summarizeBy": "none"
          },
          {
            "name": "机电核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "be2e6b96-b14f-4dfa-8e39-22441a740f3b",
            "sourceColumn": "机电核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "机电甲指核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "15d1b03a-efe3-473a-9b10-238679ede416",
            "sourceColumn": "机电甲指核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "直管机构",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb3fbdd4-a220-4105-81e3-8175570ee819",
            "sourceColumn": "直管机构",
            "summarizeBy": "none"
          },
          {
            "name": "省",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4ddc3b4-6d13-488a-99a2-25c035999edc",
            "sourceColumn": "省",
            "summarizeBy": "none"
          },
          {
            "name": "综合核定收益率",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1573bd6a-549e-4e8b-b074-d11ffa332794",
            "sourceColumn": "综合核定收益率",
            "summarizeBy": "sum"
          },
          {
            "name": "行政区域",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4204b084-a237-4eb7-b8e2-909acb52cd9f",
            "sourceColumn": "行政区域",
            "summarizeBy": "none"
          },
          {
            "name": "责任体",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dc8dfde3-4cf8-4d2b-880f-73bcbbb68fb8",
            "sourceColumn": "责任体",
            "summarizeBy": "none"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "126eb9c8-8182-4a6e-8fcc-99191f6e61bf",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "项目实施状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "298e2478-b371-4985-b6b9-2b6f5bb0b5fb",
            "sourceColumn": "项目实施状态",
            "summarizeBy": "none"
          },
          {
            "name": "项目性质",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b01aa028-d798-4453-9efe-03346acdf6f1",
            "sourceColumn": "项目性质",
            "summarizeBy": "none"
          },
          {
            "name": "项目总监",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f959f105-513c-49c9-93dc-664b0af54739",
            "sourceColumn": "项目总监",
            "summarizeBy": "none"
          },
          {
            "name": "项目所属大客户",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c33e9f1-a8cc-4d78-a80e-fabb18ae5c76",
            "sourceColumn": "项目所属大客户",
            "summarizeBy": "none"
          },
          {
            "name": "项目类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0776603f-1aa8-4674-a66d-9527236200e7",
            "sourceColumn": "项目类型",
            "summarizeBy": "none"
          },
          {
            "name": "项目结算状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "044497ca-0129-44d8-b075-6ef02361f422",
            "sourceColumn": "项目结算状态",
            "summarizeBy": "none"
          },
          {
            "name": "项目编码",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b54bffe9-ec03-417c-961d-11f848cd3545",
            "sourceColumn": "项目编码",
            "summarizeBy": "none"
          },
          {
            "name": "项目财务状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a0251f5-b67a-43f6-ab66-199d5fd7d98e",
            "sourceColumn": "项目财务状态",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "dc8e24be-4cc2-4d1f-9e85-6ffa519d5e3b",
        "partitions": [
          {
            "name": "维度-项目-e4a532f0-dc59-4632-9d0a-87084b931102",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Oracle.Database(X5数据连接, [HierarchicalNavigation=true]),",
                "    MD = 源{[Schema=\"MD\"]}[Data],",
                "    MD_XIANGMUXINXI1 = MD{[Name=\"MD_XIANGMUXINXI\"]}[Data],",
                "    筛选的行 = Table.SelectRows(MD_XIANGMUXINXI1, each [FXMBIANMA] <> null),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"FXMBIANMA\", \"项目编码\"}, {\"FXMQUANCHENG\", \"项目名称\"}, {\"FXMZONGJIAN\", \"项目总监\"}, {\"FZHUANYEFL\", \"专业分类\"}, {\"FXMXINGZHI\", \"项目性质\"}, {\"FJNWFB\", \"京内外\"}, {\"FQUYU\", \"行政区域\"}, {\"FSHENG\", \"省\"}, {\"FCHENGSHI\", \"城市\"}, {\"FXIAN\", \"区县\"}, {\"FXMSSZT\", \"项目实施状态\"}, {\"FGCLBYJ\", \"工程类别一级\"}, {\"FGCLBEJ\", \"工程类别二级\"}, {\"FXMJSZT\", \"项目结算状态\"}, {\"FXMSZDKH\", \"项目所属大客户\"}, {\"FSFTZJZXM\", \"是否投资建造项目\"}, {\"FPINGSHENZHUANGTAIID\", \"FPINGSHENZHUANGTAIID\"}, {\"FZHIGUANJGXG\", \"直管机构\"}, {\"FXIANGMULEIXING\", \"项目类型\"}, {\"FZONGJIANTUANDUI\", \"所属总监团队\"}, {\"FXMCAIWUZHUANGTAI\", \"项目财务状态\"}, {\"FYWBK\", \"业务板块\"}, {\"FTUJIANHEDINGSYL\", \"土建核定收益率\"}, {\"FJIDIANHEDINGSYL\", \"机电核定收益率\"}, {\"FZONGHEHEDINGSYL\", \"综合核定收益率\"}, {\"FTUJIANHEDINGSYLJZ\", \"土建甲指核定收益率\"}, {\"FJIDIANHEDINGSYLJZ\", \"机电甲指核定收益率\"}, {\"FCHANGFANGSHIYEBU\", \"厂房事业部\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"项目编码\", \"项目名称\", \"项目总监\", \"专业分类\", \"项目性质\", \"京内外\", \"行政区域\", \"省\", \"城市\", \"区县\", \"项目实施状态\", \"工程类别一级\", \"工程类别二级\", \"项目结算状态\", \"项目所属大客户\", \"是否投资建造项目\", \"土建核定收益率\", \"机电核定收益率\", \"综合核定收益率\", \"项目类型\", \"直管机构\", \"土建甲指核定收益率\", \"机电甲指核定收益率\", \"厂房事业部\", \"所属总监团队\", \"项目财务状态\", \"业务板块\"}),",
                "    缓存表 = Table.Buffer(删除的其他列),",
                "    已添加条件列 = Table.AddColumn(缓存表, \"责任体\", each if [京内外] = \"国际\" then \"海外\" else if [厂房事业部] <> null then [厂房事业部] else if [直管机构] <> \"公司\" then [直管机构] else \"公司直营\",type text),",
                "    已添加条件列1 = Table.AddColumn(已添加条件列, \"投资非投资项目\", each if [是否投资建造项目] = \"是\" then \"投资项目\" else \"非投资项目\",type text),",
                "    替换的值 = Table.ReplaceValue(已添加条件列1,\"机电\",\"机电总包\",Replacer.ReplaceValue,{\"业务板块\"}),",
                "    替换的值1 = Table.ReplaceValue(替换的值,\"基础设施-公路工程\",\"其他\",Replacer.ReplaceText,{\"项目类型\"}),",
                "    替换的值2 = Table.ReplaceValue(替换的值1,\"基础设施-市政工程\",\"其他\",Replacer.ReplaceText,{\"项目类型\"})",
                "in",
                "    替换的值2"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}