{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.684.0 (23.11)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"业主结算状态\",\"主表\",\"项目表\",\"合同表\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "zh-CN",
    "cultures": [
      {
        "name": "zh-CN",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "table.column": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "合同表",
                    "ConceptualProperty": "施工专业"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "施工专业": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "合同表",
                    "ConceptualProperty": "结算状态"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "结算状态": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column2": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "合同表",
                    "ConceptualProperty": "合同分类"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "合同分类": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "table.column3": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "合同表",
                    "ConceptualProperty": "合同类型"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "合同类型": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "80bcb13b-30b8-41d0-9870-379b126bfd64",
        "fromColumn": "FZBID",
        "fromTable": "项目表",
        "toColumn": "FID",
        "toTable": "主表"
      },
      {
        "name": "285f0049-8953-414e-aa17-77fc775a5994",
        "fromColumn": "FC1BFID",
        "fromTable": "合同表",
        "toColumn": "FID",
        "toTable": "项目表"
      },
      {
        "name": "892ad0fc-4ef3-48cd-9f56-113fc93e15a4",
        "fromColumn": "下游预计结算日期",
        "fromTable": "业主结算状态",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e35944b9-c82e-4337-9ff1-c9879053d99e"
      },
      {
        "name": "9f12de22-de4f-492a-8373-b6986e6e71aa",
        "fromColumn": "业务日期",
        "fromTable": "主表",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8beef923-69c0-4971-b852-f826d5e61bdb"
      },
      {
        "name": "deb6e243-ff44-4a2f-91c3-f233f9d33a37",
        "fromColumn": "实际考核完工日期",
        "fromTable": "项目表",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_21faf501-65d0-4399-a25a-10ee0ebe17e6"
      },
      {
        "name": "cafe07e1-31e8-4bd8-b837-fdc6ae158763",
        "fromColumn": "实际完工日期",
        "fromTable": "合同表",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c9ce12f7-0d34-45dc-974a-3bb240d35cac"
      },
      {
        "name": "d8b8a254-2b7f-4c99-8fad-c360f1b8d155",
        "fromColumn": "结算完成时间",
        "fromTable": "合同表",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_46a9f85c-2ee5-44b8-a986-7db3c384f396"
      }
    ],
    "sourceQueryCulture": "zh-CN",
    "tables": [
      {
        "name": "业主结算状态",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FXIANGMUBIANMA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4a9fd870-d122-4bf3-8a4c-2a5b89c096da",
            "sourceColumn": "FXIANGMUBIANMA",
            "summarizeBy": "none"
          },
          {
            "name": "FXIANGMUMINGCHENG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f93f5021-f303-42b4-9821-f911bed3af04",
            "sourceColumn": "FXIANGMUMINGCHENG",
            "summarizeBy": "none"
          },
          {
            "name": "下游预计结算日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ec553dca-6e28-4db2-8455-dde570a8baa1",
            "sourceColumn": "下游预计结算日期",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "变体",
                "defaultHierarchy": {
                  "hierarchy": "日期层次结构",
                  "table": "LocalDateTable_e35944b9-c82e-4337-9ff1-c9879053d99e"
                },
                "isDefault": true,
                "relationship": "892ad0fc-4ef3-48cd-9f56-113fc93e15a4"
              }
            ]
          }
        ],
        "lineageTag": "875fa336-734f-4aba-bdac-e74b37f004a2",
        "partitions": [
          {
            "name": "业主结算状态",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_YEZHUJIESUANJINZHAN1 = GSPM{[Name=\"GSPM_YEZHUJIESUANJINZHAN\"]}[Data],",
                "    筛选的行 = Table.SelectRows(GSPM_YEZHUJIESUANJINZHAN1, each ([FPINGSHENZHUANGTAI] = \"已完成\")),",
                "    排序的行 = Table.Sort(筛选的行,{{\"FXIANGMUBIANMA\", Order.Ascending}, {\"SCREATETIME\", Order.Descending}}),",
                "    已添加索引 = Table.AddIndexColumn(排序的行, \"索引\", 0, 1, Int64.Type),",
                "    删除的副本 = Table.Distinct(已添加索引, {\"FXIANGMUBIANMA\"}),",
                "    删除的其他列 = Table.SelectColumns(删除的副本,{\"FXIANGMUBIANMA\", \"FXIANGMUMINGCHENG\", \"FFGFGYJJSSJ\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FFGFGYJJSSJ\", \"下游预计结算日期\"}})",
                "in",
                "    重命名的列"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "主表",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "224d6243-6883-44e6-b824-7bca02fda884",
            "sourceColumn": "FID",
            "summarizeBy": "none"
          },
          {
            "name": "业务单号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "768bac83-aea6-45ae-8127-3592e838d7bd",
            "sourceColumn": "业务单号",
            "summarizeBy": "none"
          },
          {
            "name": "业务日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "f810b90a-bd12-4b8b-a1ef-233a45ac48e6",
            "sourceColumn": "业务日期",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "变体",
                "defaultHierarchy": {
                  "hierarchy": "日期层次结构",
                  "table": "LocalDateTable_8beef923-69c0-4971-b852-f826d5e61bdb"
                },
                "isDefault": true,
                "relationship": "9f12de22-de4f-492a-8373-b6986e6e71aa"
              }
            ]
          }
        ],
        "lineageTag": "62c3e167-c63e-4e79-81b2-6995efc38be0",
        "measures": [
          {
            "name": "M.业务日期",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": "MAX('主表'[业务日期])",
            "formatString": "yyyy-m-d",
            "lineageTag": "94b136c9-8a55-4e2c-bd76-5bf0a6350b2d"
          }
        ],
        "partitions": [
          {
            "name": "主表",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_FBFGHTJSZB1 = GSPM{[Name=\"GSPM_FBFGHTJSZB\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(GSPM_FBFGHTJSZB1,{\"FID\", \"FYEWUDANHAO\", \"FYWRQ\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FYEWUDANHAO\", \"业务单号\"}, {\"FYWRQ\", \"业务日期\"}}),",
                "    提取的日期 = Table.TransformColumns(重命名的列,{{\"业务日期\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "项目表",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dea5fa0a-7b9a-4421-a3ea-b82b54eee9dc",
            "sourceColumn": "FID",
            "summarizeBy": "none"
          },
          {
            "name": "项目名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "efc8798f-310b-4547-84bf-737b20927721",
            "sourceColumn": "项目名称",
            "summarizeBy": "none"
          },
          {
            "name": "直管机构",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b14c956-d0f6-4f57-afc1-53ee507a6f9a",
            "sourceColumn": "直管机构",
            "summarizeBy": "none"
          },
          {
            "name": "专业类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c648c8d-6dd1-4088-be7d-7f7f4878b91f",
            "sourceColumn": "专业类型",
            "summarizeBy": "none"
          },
          {
            "name": "实际考核完工日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c5603dfd-60c5-4b3c-b8af-e91e15c5293d",
            "sourceColumn": "实际考核完工日期",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "变体",
                "defaultHierarchy": {
                  "hierarchy": "日期层次结构",
                  "table": "LocalDateTable_21faf501-65d0-4399-a25a-10ee0ebe17e6"
                },
                "isDefault": true,
                "relationship": "deb6e243-ff44-4a2f-91c3-f233f9d33a37"
              }
            ]
          },
          {
            "name": "新增合同个数",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb7a2eba-42ea-4153-b296-c9776a57cd22",
            "sourceColumn": "新增合同个数",
            "summarizeBy": "sum"
          },
          {
            "name": "业主结算状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77ff7250-028c-46b5-ad97-e5e3e94e416b",
            "sourceColumn": "业主结算状态",
            "summarizeBy": "none"
          },
          {
            "name": "分包分供结算状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d25484d-6f37-495b-9a5d-95d928fa3f53",
            "sourceColumn": "分包分供结算状态",
            "summarizeBy": "none"
          },
          {
            "name": "全部合同份数合计",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b4ecd46d-39d3-45f0-833a-144dec2eaa38",
            "sourceColumn": "全部合同份数合计",
            "summarizeBy": "sum"
          },
          {
            "name": "全部合同份数未结",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "23eb10c5-8021-430c-90f1-8f5623ef6aa5",
            "sourceColumn": "全部合同份数未结",
            "summarizeBy": "sum"
          },
          {
            "name": "FZBID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f273aee-d47f-406f-adf0-1c8df2dad6da",
            "sourceColumn": "FZBID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "164e41cf-2b99-4a4e-b04a-dc5862b9f28b",
        "partitions": [
          {
            "name": "项目表",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_FBFGHTJSXMCB1 = GSPM{[Name=\"GSPM_FBFGHTJSXMCB\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(GSPM_FBFGHTJSXMCB1,{\"FID\", \"FXIANGMUMINGCHENG\", \"FZGJG\", \"FZYLX\", \"FKAOHEWANGONGRIQI\", \"FXZHTGS\", \"FYZJSZT\", \"FXTFBFGJSZT\", \"FQBHTFSHJ\", \"FQBHTFSWJ\", \"FZBID\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FXIANGMUMINGCHENG\", \"项目名称\"}, {\"FZGJG\", \"直管机构\"}, {\"FZYLX\", \"专业类型\"}, {\"FKAOHEWANGONGRIQI\", \"实际考核完工日期\"}, {\"FXZHTGS\", \"新增合同个数\"}, {\"FYZJSZT\", \"业主结算状态\"}, {\"FXTFBFGJSZT\", \"分包分供结算状态\"}, {\"FQBHTFSHJ\", \"全部合同份数合计\"}, {\"FQBHTFSWJ\", \"全部合同份数未结\"}}),",
                "    提取的日期 = Table.TransformColumns(重命名的列,{{\"实际考核完工日期\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "合同表",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "导航"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FC1BFID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1af4bfcc-c062-49ad-9aa9-c279ddccbc78",
            "sourceColumn": "FC1BFID",
            "summarizeBy": "none"
          },
          {
            "name": "合同编号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc6d67ad-f524-4b63-839f-667bfec82511",
            "sourceColumn": "合同编号",
            "summarizeBy": "none"
          },
          {
            "name": "合同名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2a49f63-aff1-4d4e-b207-800b6bb4a8b9",
            "sourceColumn": "合同名称",
            "summarizeBy": "none"
          },
          {
            "name": "施工专业",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d2060a5-2c80-40b3-b3d3-21c4612495b4",
            "sourceColumn": "施工专业",
            "summarizeBy": "none"
          },
          {
            "name": "合同类型",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e802a6a7-c0e5-4e19-b659-580e8c724715",
            "sourceColumn": "合同类型",
            "summarizeBy": "none"
          },
          {
            "name": "合同分类",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c397d0ca-1334-4fb0-be89-522a73074e2d",
            "sourceColumn": "合同分类",
            "summarizeBy": "none"
          },
          {
            "name": "分包名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c0e310c-88f6-481f-bd11-2a1046ee9825",
            "sourceColumn": "分包名称",
            "summarizeBy": "none"
          },
          {
            "name": "标准合同编号",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8848eaf-d802-44e8-b9e4-473df269fedd",
            "sourceColumn": "标准合同编号",
            "summarizeBy": "none"
          },
          {
            "name": "标准合同名称",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e14ec7d-363e-4da8-838a-5df07e19950c",
            "sourceColumn": "标准合同名称",
            "summarizeBy": "none"
          },
          {
            "name": "结算状态",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85675d38-2923-4f46-ab66-5ee03dd842d8",
            "sourceColumn": "结算状态",
            "summarizeBy": "none"
          },
          {
            "name": "是否已定数",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39996072-4a29-42f3-97b5-1dfb57a7ac45",
            "sourceColumn": "是否已定数",
            "summarizeBy": "none"
          },
          {
            "name": "实际完工日期",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "9ec16d9f-68b8-4213-9e2e-19e5b679c714",
            "sourceColumn": "实际完工日期",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "变体",
                "defaultHierarchy": {
                  "hierarchy": "日期层次结构",
                  "table": "LocalDateTable_c9ce12f7-0d34-45dc-974a-3bb240d35cac"
                },
                "isDefault": true,
                "relationship": "cafe07e1-31e8-4bd8-b837-fdc6ae158763"
              }
            ]
          },
          {
            "name": "结算完成时间",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "aa3ff2f9-5db4-4e8d-9c19-1c4dfe54e501",
            "sourceColumn": "结算完成时间",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "变体",
                "defaultHierarchy": {
                  "hierarchy": "日期层次结构",
                  "table": "LocalDateTable_46a9f85c-2ee5-44b8-a986-7db3c384f396"
                },
                "isDefault": true,
                "relationship": "d8b8a254-2b7f-4c99-8fad-c360f1b8d155"
              }
            ]
          }
        ],
        "lineageTag": "6b17bd83-d80b-423a-b0e3-9471ef729705",
        "measures": [
          {
            "name": "M.计数.合同号",
            "expression": "DISTINCTCOUNT('合同表'[合同编号])",
            "formatString": "0",
            "lineageTag": "d97de81f-882a-4f2b-bdd7-c6886fbf252a"
          },
          {
            "name": "M.最后结算日期",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "expression": "MAX('合同表'[结算完成时间])",
            "formatString": "yyyy-m-d",
            "lineageTag": "b50ec7f4-f2a2-41a2-91bb-b44bb27c28bb"
          }
        ],
        "partitions": [
          {
            "name": "合同表",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Oracle.Database(\"172.16.8.78/oracledb\", [HierarchicalNavigation=true]),",
                "    GSPM = 源{[Schema=\"GSPM\"]}[Data],",
                "    GSPM_FBFGHTJSXMHTCB1 = GSPM{[Name=\"GSPM_FBFGHTJSXMHTCB\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(GSPM_FBFGHTJSXMHTCB1,{\"FC1BFID\", \"FHETONGBIANHAO\", \"FHETONGMINGCHENG\", \"FSHIGONGZHUANYE\", \"FHETONGLEIXING\", \"FHTFL\", \"FFENBAOMINGCHENG\", \"FBIAOZHUNHETONGCODE\", \"FBIAOZHUNHETONGNAME\", \"FJIESUANZHUANGTAI\", \"FSFYDS\", \"FSHIJIWANGONGRIQI\", \"FJSWCSJXT\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FHETONGBIANHAO\", \"合同编号\"}, {\"FHETONGMINGCHENG\", \"合同名称\"}, {\"FSHIGONGZHUANYE\", \"施工专业\"}, {\"FHETONGLEIXING\", \"合同类型\"}, {\"FHTFL\", \"合同分类\"}, {\"FFENBAOMINGCHENG\", \"分包名称\"}, {\"FBIAOZHUNHETONGCODE\", \"标准合同编号\"}, {\"FBIAOZHUNHETONGNAME\", \"标准合同名称\"}, {\"FJIESUANZHUANGTAI\", \"结算状态\"}, {\"FSFYDS\", \"是否已定数\"}, {\"FSHIJIWANGONGRIQI\", \"实际完工日期\"}, {\"FJSWCSJXT\", \"结算完成时间\"}}),",
                "    提取的日期 = Table.TransformColumns(重命名的列,{{\"实际完工日期\", DateTime.Date, type date}, {\"结算完成时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_faf22890-80bf-4156-b3a0-53288a387c7b",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1518eb39-7677-4912-8a86-77bcdd289515",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "84b42637-110c-47ff-a2d9-6afa83698351",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9534770f-6be9-4b20-9493-70ae30ab6e95",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f7c0038d-75be-47e9-b275-7f77477db6b9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "883a2242-27d1-4009-abf5-b721f19202de",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "4491ee90-0c80-44fc-920d-7dbd2aa90642",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2fa9d919-f72b-4107-beb1-d1c64e665c4e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "b1c51993-32a2-44b7-b998-b9554a1a754f",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "08acdbba-519e-4665-8068-62f47e0becf4",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "866e78f1-9e53-43e2-8573-35c153acfb61",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "ae37d54a-a25b-49d3-905e-388ad5156c51",
                "ordinal": 3
              }
            ],
            "lineageTag": "d514b254-3d82-4825-8d50-b1a43a467f69"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "c393654e-9bbd-43c0-a7f6-63fe42b20610",
        "partitions": [
          {
            "name": "DateTableTemplate_faf22890-80bf-4156-b3a0-53288a387c7b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e35944b9-c82e-4337-9ff1-c9879053d99e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "feffba9f-261c-4292-802b-617eb0dad9ae",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "6ed6d408-53ce-4952-9463-30ade6206b67",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "97e913c8-9e50-4cc8-b344-c59fcf6f4034",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "363fad92-f3bd-492e-a9ab-79dbbdb43407",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5184aca2-ece5-4045-a9b3-f00ab1af0480",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "28ad9e50-a001-4c10-af00-c0ec8ce1b4ff",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "57be87ae-a6b0-4259-9554-9d99f2803424",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "3d1197e6-65b1-472e-85af-3399a570843e",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "09af4578-df4e-48ce-8f9a-fe585e8d0222",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "ac8e1a76-0d9e-4922-af81-e5db98482ac1",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "eee15af3-84b8-4554-90fd-da7fefa2d280",
                "ordinal": 3
              }
            ],
            "lineageTag": "8b448ca8-8149-4864-b644-27734943d7a3"
          }
        ],
        "isHidden": true,
        "lineageTag": "dedf7dd7-ebd7-4ce3-8cf1-728968fc0be4",
        "partitions": [
          {
            "name": "LocalDateTable_e35944b9-c82e-4337-9ff1-c9879053d99e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('业主结算状态'[下游预计结算日期])), 1, 1), Date(Year(MAX('业主结算状态'[下游预计结算日期])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8beef923-69c0-4971-b852-f826d5e61bdb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "55f856eb-0888-4171-9627-2d38a6c682ec",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a5a03627-1374-4e1b-b730-a26bf7c4ffda",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "dbb8d9b0-7a9c-41ee-8ee5-9cbfdb92c6b6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6d736d6f-002e-4264-8ed6-73b2db39f8c0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "98bad1fe-c304-46cc-b32e-1c01c119df2a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f116040f-7084-4c87-843f-9299259dba01",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "06cfca00-f565-492a-bbf2-db56fd780f7e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "a4beed53-d33a-4ad7-96e4-3ce3d0990a3e",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "360166b4-e755-4815-8af7-0df230480fd3",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "55fcef5a-ec57-4517-957c-e118f063104b",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "90095d27-6270-4fa1-9557-bfa38fcd51d5",
                "ordinal": 3
              }
            ],
            "lineageTag": "5d0e1d89-d50f-4ab2-ada7-32c4dc986fc8"
          }
        ],
        "isHidden": true,
        "lineageTag": "d9731baa-cdc4-4a8f-9107-3a42bcc10793",
        "partitions": [
          {
            "name": "LocalDateTable_8beef923-69c0-4971-b852-f826d5e61bdb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('主表'[业务日期])), 1, 1), Date(Year(MAX('主表'[业务日期])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_21faf501-65d0-4399-a25a-10ee0ebe17e6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0da11ef8-6b9f-4166-8181-be9de95f324e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d473d401-f373-4ba6-94fa-7a6fc1f6364f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7ce57aa5-a100-4f88-baea-23520bd756f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8d8d5928-46f4-4fe2-aefe-eed5a511109d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "97bdebd7-8f0e-45f9-b78f-f66f505bb588",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d6f49920-42e6-47b8-951c-d70e09248866",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c0697af2-5338-46af-93bc-4ea005b5781c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "ebfe8552-0d1c-4a88-9a20-57413fd3bf32",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "ffc9dab3-6ba9-4999-b9ce-541d1c2c423a",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "d4cbd8a1-f3e3-4f11-96e4-2b7ade02e10b",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "10a3ee91-0e86-4218-a0e6-bce83eea7d54",
                "ordinal": 3
              }
            ],
            "lineageTag": "5ef96adc-6972-45e0-a4b8-11fffa5fba9c"
          }
        ],
        "isHidden": true,
        "lineageTag": "97038269-276b-4fb2-bca1-a87723711636",
        "partitions": [
          {
            "name": "LocalDateTable_21faf501-65d0-4399-a25a-10ee0ebe17e6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('项目表'[实际考核完工日期])), 1, 1), Date(Year(MAX('项目表'[实际考核完工日期])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c9ce12f7-0d34-45dc-974a-3bb240d35cac",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4860e533-589d-4c4a-9261-75a34bea019d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3fd7ed03-6da3-45ce-b1cb-f355f00b9101",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8160143c-ee5e-434e-a92e-99afc76f8c78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "768b2cc7-1c38-4fbd-80c4-3c17e3ea728b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a3eca162-70e5-49ec-b9c9-2204bb05ef1f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f2898782-683e-419b-857c-f6ea546f4bfb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "08274276-4274-4cc8-86b3-517a65b5a772",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "7fb4f88e-e9bd-4ffc-b05f-5acaad176ad1",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "dc502cb9-0c30-459f-8ab3-f7e875117b11",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "16dc8d87-276c-48d8-80f4-8cbb3d349781",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "758cadfa-5499-4e26-8fe2-76346d7b83b1",
                "ordinal": 3
              }
            ],
            "lineageTag": "9e3d6f23-fa9f-443d-951b-b8de152c37f1"
          }
        ],
        "isHidden": true,
        "lineageTag": "8d5715d7-251f-41ad-ab21-02e8b464216a",
        "partitions": [
          {
            "name": "LocalDateTable_c9ce12f7-0d34-45dc-974a-3bb240d35cac",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('合同表'[实际完工日期])), 1, 1), Date(Year(MAX('合同表'[实际完工日期])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_46a9f85c-2ee5-44b8-a986-7db3c384f396",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1a320d57-90d7-4876-8150-6c27d921e16c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff90eebe-2617-4edf-8005-704f65cab1a5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f41dbc5e-38de-4ce7-91ef-5c3b01f7d0f6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "5353c4a6-707f-48e6-a47b-33d72da64cf1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a17ad14a-e1fa-4c68-ac06-da5656bd73b7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "315644e7-98a4-460f-9107-9c2aaef4bd13",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "572b6d67-2237-4a8b-9645-55b1589c4134",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "99932797-d9cc-4ee8-a8f2-db40d50b3731",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "e63ad7e6-f580-4467-a7d5-7b1af8330c95",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "a64071a9-a191-49ea-9ec4-12a6786c0017",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "011abb30-063f-4a1c-bb40-71d887a965ed",
                "ordinal": 3
              }
            ],
            "lineageTag": "8e1e94a6-5309-4ca0-8572-7c3c6983f795"
          }
        ],
        "isHidden": true,
        "lineageTag": "1ea9c72c-269a-49ef-a2cd-0f34a46e06b8",
        "partitions": [
          {
            "name": "LocalDateTable_46a9f85c-2ee5-44b8-a986-7db3c384f396",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('合同表'[结算完成时间])), 1, 1), Date(Year(MAX('合同表'[结算完成时间])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "行内容",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "64cf98f15df245f1ae6980239bf1c313"
          }
        ],
        "columns": [
          {
            "name": "行内容",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "06841f5c-3017-45e0-b2b1-5fd9e64446cf",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "行内容 个字段"
                }
              ]
            },
            "sortByColumn": "行内容 个订单",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "行内容 个字段",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "2f0b700c-32b2-4905-abcd-07b64241be94",
            "sortByColumn": "行内容 个订单",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "行内容 个订单",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "ec0b4b15-357f-471b-868b-ba77787cb85f",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "38355f87-e47d-495c-a7a2-112a12e276b2",
        "partitions": [
          {
            "name": "行内容",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"合同分类\", NAMEOF('合同表'[合同分类]), 0),",
                "    (\"合同类型\", NAMEOF('合同表'[合同类型]), 1),",
                "    (\"施工专业\", NAMEOF('合同表'[施工专业]), 2),",
                "    (\"结算状态\", NAMEOF('合同表'[结算状态]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}